/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimengine\src\nimcache\affine2.o C:\Users\Desktop-P1NKA\Desktop\nimengine\src\nimcache\affine2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw;
typedef struct tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
typedef tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ tyArray_lyzHzk9aModN4FAni3DbC4Q[2];
struct tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw {
tyArray_lyzHzk9aModN4FAni3DbC4Q data;
};
struct tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w {
NF x;
NF y;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initAffine2_HkU9b8hEpERxwbgBWllafBw)(void);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initTrn_Icnys4pAARytXILfwGowsw)(NF tx, NF ty);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initScl_84eF6t3Ad7lTYc7g1UlDnA)(NF sx, NF sy);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initRot_9auw1pzlEje6Bk9aoEPDAzdw)(NF rads);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, product_jrscvUED4NPoKHtt02iSEQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* left, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* right);
N_LIB_PRIVATE N_NIMCALL(NF, det_p9bSgaQ0eMHu6Ykd9cpwd9cug)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, inv_rHG0mH4xWEVZ9aFDPU6FhgQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, mul_RgJ9a9ayQVggHe2rYxWmgGng)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* other);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, trn_KtcIlianA9cBWtuFxek3DBw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF tx, NF ty);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, scl_QAwj9c14NoZ5U318weiZWZQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF sx, NF sy);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, rot_2zuzpUSW5Nm9cVTa5PV7Mjw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF rads);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, apply_p2hhysjrPPCLAqoXUm4Bdw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* m, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_WGoxMDI3T5RNt1Vzmu0Hiw_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
TNimType NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_;
TNimType NTI_lyzHzk9aModN4FAni3DbC4Q_;
NIM_CONST tyArray_lyzHzk9aModN4FAni3DbC4Q TM_DsiWuGy48krXxtfllLQbKg_2 = {{1.0000000000000000e+000,
0.0,
0.0}
,
{0.0,
1.0000000000000000e+000,
0.0}
}
;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initAffine2_HkU9b8hEpERxwbgBWllafBw)(void) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("initAffine2", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(9, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	memcpy((void*)result.data, (NIM_CONST void*)TM_DsiWuGy48krXxtfllLQbKg_2, sizeof(tyArray_lyzHzk9aModN4FAni3DbC4Q));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initTrn_Icnys4pAARytXILfwGowsw)(NF tx, NF ty) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("initTrn", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(15, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.data[0][0] = 1.0000000000000000e+000;
	result.data[0][1] = 0.0;
	result.data[0][2] = tx;
	result.data[1][0] = 0.0;
	result.data[1][1] = 1.0000000000000000e+000;
	result.data[1][2] = ty;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initScl_84eF6t3Ad7lTYc7g1UlDnA)(NF sx, NF sy) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("initScl", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(21, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.data[0][0] = sx;
	result.data[0][1] = 0.0;
	result.data[0][2] = 0.0;
	result.data[1][0] = 0.0;
	result.data[1][1] = sy;
	result.data[1][2] = 0.0;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initRot_9auw1pzlEje6Bk9aoEPDAzdw)(NF rads) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	NF c;
	NF s;
	nimfr_("initRot", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(27, "affine2.nim");
	c = cos(rads);
	nimln_(28, "affine2.nim");
	s = sin(rads);
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.data[0][0] = c;
	nimln_(31, "affine2.nim");
	result.data[0][1] = -(s);
	result.data[0][2] = 0.0;
	result.data[1][0] = s;
	result.data[1][1] = c;
	result.data[1][2] = 0.0;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, product_jrscvUED4NPoKHtt02iSEQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* left, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* right) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("product", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(36, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	nimln_(41, "affine2.nim");
	result.data[0][0] = ((NF)(((NF)((*left).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*right).data[(((NI) 0))- 0][(((NI) 0))- 0]))) + (NF)(((NF)((*left).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*right).data[(((NI) 1))- 0][(((NI) 0))- 0]))));
	nimln_(42, "affine2.nim");
	result.data[0][1] = ((NF)(((NF)((*left).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*right).data[(((NI) 0))- 0][(((NI) 1))- 0]))) + (NF)(((NF)((*left).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*right).data[(((NI) 1))- 0][(((NI) 1))- 0]))));
	nimln_(43, "affine2.nim");
	result.data[0][2] = ((NF)(((NF)(((NF)((*left).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*right).data[(((NI) 0))- 0][(((NI) 2))- 0]))) + (NF)(((NF)((*left).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*right).data[(((NI) 1))- 0][(((NI) 2))- 0]))))) + (NF)((*left).data[(((NI) 0))- 0][(((NI) 2))- 0]));
	nimln_(46, "affine2.nim");
	result.data[1][0] = ((NF)(((NF)((*left).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)((*right).data[(((NI) 0))- 0][(((NI) 0))- 0]))) + (NF)(((NF)((*left).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)((*right).data[(((NI) 1))- 0][(((NI) 0))- 0]))));
	nimln_(47, "affine2.nim");
	result.data[1][1] = ((NF)(((NF)((*left).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)((*right).data[(((NI) 0))- 0][(((NI) 1))- 0]))) + (NF)(((NF)((*left).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)((*right).data[(((NI) 1))- 0][(((NI) 1))- 0]))));
	nimln_(48, "affine2.nim");
	result.data[1][2] = ((NF)(((NF)(((NF)((*left).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)((*right).data[(((NI) 0))- 0][(((NI) 2))- 0]))) + (NF)(((NF)((*left).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)((*right).data[(((NI) 1))- 0][(((NI) 2))- 0]))))) + (NF)((*left).data[(((NI) 1))- 0][(((NI) 2))- 0]));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, det_p9bSgaQ0eMHu6Ykd9cpwd9cug)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat) {
	NF result;
	nimfr_("det", "affine2.nim");
{	result = (NF)0;
	nimln_(53, "affine2.nim");
	result = ((NF)(((NF)((*mat).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*mat).data[(((NI) 1))- 0][(((NI) 1))- 0]))) - (NF)(((NF)((*mat).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*mat).data[(((NI) 1))- 0][(((NI) 0))- 0]))));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, inv_rHG0mH4xWEVZ9aFDPU6FhgQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	NF det;
	NF invDet;
	nimfr_("inv", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(56, "affine2.nim");
	det = det_p9bSgaQ0eMHu6Ykd9cpwd9cug(mat);
	nimln_(57, "affine2.nim");
	invDet = ((NF)(1.0000000000000000e+000) / (NF)(det));
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	nimln_(62, "affine2.nim");
	result.data[0][0] = ((NF)(invDet) * (NF)((*mat).data[(((NI) 1))- 0][(((NI) 1))- 0]));
	nimln_(63, "affine2.nim");
	result.data[0][1] = ((NF)(invDet) * (NF)(-((*mat).data[(((NI) 0))- 0][(((NI) 1))- 0])));
	nimln_(64, "affine2.nim");
	result.data[0][2] = ((NF)(invDet) * (NF)(((NF)(((NF)((*mat).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*mat).data[(((NI) 1))- 0][(((NI) 2))- 0]))) - (NF)(((NF)((*mat).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)((*mat).data[(((NI) 0))- 0][(((NI) 2))- 0]))))));
	nimln_(67, "affine2.nim");
	result.data[1][0] = ((NF)(invDet) * (NF)(-((*mat).data[(((NI) 1))- 0][(((NI) 0))- 0])));
	nimln_(68, "affine2.nim");
	result.data[1][1] = ((NF)(invDet) * (NF)((*mat).data[(((NI) 0))- 0][(((NI) 0))- 0]));
	nimln_(69, "affine2.nim");
	result.data[1][2] = ((NF)(invDet) * (NF)(((NF)(((NF)((*mat).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)((*mat).data[(((NI) 0))- 0][(((NI) 2))- 0]))) - (NF)(((NF)((*mat).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*mat).data[(((NI) 1))- 0][(((NI) 2))- 0]))))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, mul_RgJ9a9ayQVggHe2rYxWmgGng)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* other) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("mul", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(73, "affine2.nim");
	result = product_jrscvUED4NPoKHtt02iSEQ(mat, other);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, trn_KtcIlianA9cBWtuFxek3DBw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF tx, NF ty) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T1_;
	nimfr_("trn", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(76, "affine2.nim");
	T1_ = initTrn_Icnys4pAARytXILfwGowsw(tx, ty);
	result = mul_RgJ9a9ayQVggHe2rYxWmgGng(mat, (&T1_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, scl_QAwj9c14NoZ5U318weiZWZQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF sx, NF sy) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T1_;
	nimfr_("scl", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(79, "affine2.nim");
	T1_ = initScl_84eF6t3Ad7lTYc7g1UlDnA(sx, sy);
	result = mul_RgJ9a9ayQVggHe2rYxWmgGng(mat, (&T1_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, rot_2zuzpUSW5Nm9cVTa5PV7Mjw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF rads) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T1_;
	nimfr_("rot", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(82, "affine2.nim");
	T1_ = initRot_9auw1pzlEje6Bk9aoEPDAzdw(rads);
	result = mul_RgJ9a9ayQVggHe2rYxWmgGng(mat, (&T1_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, apply_p2hhysjrPPCLAqoXUm4Bdw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* m, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	nimfr_("apply", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(85, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	nimln_(86, "affine2.nim");
	result.x = ((NF)(((NF)(((NF)((*m).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)(v.x))) + (NF)(((NF)((*m).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)(v.y))))) + (NF)((*m).data[(((NI) 0))- 0][(((NI) 2))- 0]));
	nimln_(87, "affine2.nim");
	result.y = ((NF)(((NF)(((NF)((*m).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)(v.x))) + (NF)(((NF)((*m).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)(v.y))))) + (NF)((*m).data[(((NI) 1))- 0][(((NI) 2))- 0]));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_affine2Init000)(void) {
	nimfr_("affine2", "affine2.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_affine2DatInit000)(void) {
static TNimNode TM_DsiWuGy48krXxtfllLQbKg_0[1];
NTI_WGoxMDI3T5RNt1Vzmu0Hiw_.size = sizeof(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw);
NTI_WGoxMDI3T5RNt1Vzmu0Hiw_.kind = 18;
NTI_WGoxMDI3T5RNt1Vzmu0Hiw_.base = 0;
NTI_WGoxMDI3T5RNt1Vzmu0Hiw_.flags = 3;
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.size = sizeof(tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ);
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.kind = 16;
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.base = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_.flags = 3;
NTI_lyzHzk9aModN4FAni3DbC4Q_.size = sizeof(tyArray_lyzHzk9aModN4FAni3DbC4Q);
NTI_lyzHzk9aModN4FAni3DbC4Q_.kind = 16;
NTI_lyzHzk9aModN4FAni3DbC4Q_.base = (&NTI_9ce69c9a1NzlPVqY9aKHS79b5IQ_);
NTI_lyzHzk9aModN4FAni3DbC4Q_.flags = 3;
TM_DsiWuGy48krXxtfllLQbKg_0[0].kind = 1;
TM_DsiWuGy48krXxtfllLQbKg_0[0].offset = offsetof(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, data);
TM_DsiWuGy48krXxtfllLQbKg_0[0].typ = (&NTI_lyzHzk9aModN4FAni3DbC4Q_);
TM_DsiWuGy48krXxtfllLQbKg_0[0].name = "data";
NTI_WGoxMDI3T5RNt1Vzmu0Hiw_.node = &TM_DsiWuGy48krXxtfllLQbKg_0[0];
}

