/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimengine\src\nimcache\glfw_glfw3.o C:\Users\Desktop-P1NKA\Desktop\nimengine\src\nimcache\glfw_glfw3.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct TGenericSeq TGenericSeq;
typedef struct NimStringDesc NimStringDesc;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_CDECL_PTR(int, tyProc_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef N_CDECL_PTR(void*, tyProc_xjK2Jbm9aCJ7DEn7DKl9ceYg) (int width, int height, NCSTRING title, void* monitor, void* share);
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* window);
typedef N_CDECL_PTR(int, tyProc_fbYpjfe38x3ujjAmVRbI1Q) (void* window);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(int, tyProc_AbsnR49cK1X9a2Wblez5VQWQ) (void* window, int key);
typedef N_CDECL_PTR(void, tyProc_9cBAJsQgOiAekcR9ctCN5urQ) (void* window, int value);
typedef N_CDECL_PTR(void, tyProc_xmqN0ZWK4lw72DZ4V9b09cTw) (void* window, int* width, int* height);
N_NIMCALL(void*, nimLoadLibrary)(NimStringDesc* path);
N_NOINLINE(void, nimLoadLibraryError)(NimStringDesc* path);
N_NIMCALL(void*, nimGetProcAddr)(void* lib, NCSTRING name);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static void* TM_injeBGAl3jmLKj2dAN2OSQ_2;
tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_108855_;
tyProc_xjK2Jbm9aCJ7DEn7DKl9ceYg Dl_108928_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_109195_;
tyProc_fbYpjfe38x3ujjAmVRbI1Q Dl_108938_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_109073_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_109200_;
tyProc_AbsnR49cK1X9a2Wblez5VQWQ Dl_109091_;
tyProc_9cBAJsQgOiAekcR9ctCN5urQ Dl_108941_;
tyProc_xmqN0ZWK4lw72DZ4V9b09cTw Dl_108990_;
tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_108935_;
tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_108857_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
STRING_LITERAL(TM_injeBGAl3jmLKj2dAN2OSQ_4, "glfw3.dll", 9);
STRING_LITERAL(TM_injeBGAl3jmLKj2dAN2OSQ_5, "glfw3.dll", 9);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, glfw_glfw3Init000)(void) {
	nimfr_("glfw3", "glfw3.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, glfw_glfw3DatInit000)(void) {
if (!((TM_injeBGAl3jmLKj2dAN2OSQ_2 = nimLoadLibrary((NimStringDesc*) &TM_injeBGAl3jmLKj2dAN2OSQ_4))
)) nimLoadLibraryError((NimStringDesc*) &TM_injeBGAl3jmLKj2dAN2OSQ_5);
	Dl_108855_ = (tyProc_cez8YhJI0vaCUcjGg6z4zA) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwInit");
	Dl_108928_ = (tyProc_xjK2Jbm9aCJ7DEn7DKl9ceYg) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwCreateWindow");
	Dl_109195_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwMakeContextCurrent");
	Dl_108938_ = (tyProc_fbYpjfe38x3ujjAmVRbI1Q) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwWindowShouldClose");
	Dl_109073_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwPollEvents");
	Dl_109200_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwSwapBuffers");
	Dl_109091_ = (tyProc_AbsnR49cK1X9a2Wblez5VQWQ) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwGetKey");
	Dl_108941_ = (tyProc_9cBAJsQgOiAekcR9ctCN5urQ) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwSetWindowShouldClose");
	Dl_108990_ = (tyProc_xmqN0ZWK4lw72DZ4V9b09cTw) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwGetFramebufferSize");
	Dl_108935_ = (tyProc_32w2ZypAyMWuajvi2Jt79cg) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwDestroyWindow");
	Dl_108857_ = (tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) nimGetProcAddr(TM_injeBGAl3jmLKj2dAN2OSQ_2, "glfwTerminate");
}

