/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\mathutils.o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\mathutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Region_qDqbve6hasFbbcoIpab4Lg tyObject_Region_qDqbve6hasFbbcoIpab4Lg;
typedef struct tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ;
typedef struct tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw;
struct tyObject_Region_qDqbve6hasFbbcoIpab4Lg {
NF x0;
NF y0;
NF x1;
NF y1;
};
struct tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ {
NF x;
NF y;
NF width;
NF height;
};
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
typedef tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ tyArray_lyzHzk9aModN4FAni3DbC4Q[2];
struct tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw {
tyArray_lyzHzk9aModN4FAni3DbC4Q data;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_Region_qDqbve6hasFbbcoIpab4Lg, region_oI9ba6hzKQWMzcfPyhoWedg)(NF x0, NF y0, NF x1, NF y1);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ, rect_u75sIkoNvHL9cvgR9b2R0X7A)(NF x, NF y, NF width, NF height);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_GimFFVXCBo1O0b7hc2EPZQ)(tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ* r, NF x, NF y);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, overlaps_oTJZ0pcf3PDNr5B9cXjcXaw)(tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ* r1, tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ* r2);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, map_tcJaJlmc3vBjg9cZeSydtYw)(tyObject_Region_qDqbve6hasFbbcoIpab4Lg* src, tyObject_Region_qDqbve6hasFbbcoIpab4Lg* dest);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Region_qDqbve6hasFbbcoIpab4Lg, region_oI9ba6hzKQWMzcfPyhoWedg)(NF x0, NF y0, NF x1, NF y1) {
	tyObject_Region_qDqbve6hasFbbcoIpab4Lg result;
	nimfr_("region", "mathutils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(12, "mathutils.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x0 = x0;
	result.y0 = y0;
	result.x1 = x1;
	result.y1 = y1;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ, rect_u75sIkoNvHL9cvgR9b2R0X7A)(NF x, NF y, NF width, NF height) {
	tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ result;
	nimfr_("rect", "mathutils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(20, "mathutils.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x = x;
	result.y = y;
	result.width = width;
	result.height = height;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, contains_GimFFVXCBo1O0b7hc2EPZQ)(tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ* r, NF x, NF y) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_BOOL T3_;
	nimfr_("contains", "mathutils.nim");
	result = (NIM_BOOL)0;
	nimln_(30, "mathutils.nim");
	T1_ = (NIM_BOOL)0;
	nimln_(29, "mathutils.nim");
	T2_ = (NIM_BOOL)0;
	T3_ = (NIM_BOOL)0;
	T3_ = ((*r).x <= x);
	if (!(T3_)) goto LA4_;
	nimln_(30, "mathutils.nim");
	T3_ = ((*r).y <= y);
	LA4_: ;
	T2_ = T3_;
	if (!(T2_)) goto LA5_;
	nimln_(31, "mathutils.nim");
	T2_ = (x < ((NF)((*r).x) + (NF)((*r).width)));
	LA5_: ;
	T1_ = T2_;
	if (!(T1_)) goto LA6_;
	nimln_(32, "mathutils.nim");
	T1_ = (y < ((NF)((*r).y) + (NF)((*r).height)));
	LA6_: ;
	result = T1_;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, overlaps_oTJZ0pcf3PDNr5B9cXjcXaw)(tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ* r1, tyObject_Rect_CcJYbOdXWLg4tlAT9aFe9ciQ* r2) {
	NIM_BOOL result;
	NIM_BOOL T1_;
	NIM_BOOL T2_;
	NIM_BOOL T3_;
	nimfr_("overlaps", "mathutils.nim");
	result = (NIM_BOOL)0;
	nimln_(38, "mathutils.nim");
	nimln_(37, "mathutils.nim");
	T1_ = (NIM_BOOL)0;
	nimln_(36, "mathutils.nim");
	T2_ = (NIM_BOOL)0;
	T3_ = (NIM_BOOL)0;
	T3_ = (((NF)((*r2).x) + (NF)((*r2).width)) < (*r1).x);
	if (T3_) goto LA4_;
	nimln_(37, "mathutils.nim");
	T3_ = (((NF)((*r2).y) + (NF)((*r2).height)) < (*r1).y);
	LA4_: ;
	T2_ = T3_;
	if (T2_) goto LA5_;
	nimln_(38, "mathutils.nim");
	T2_ = (((NF)((*r1).x) + (NF)((*r1).width)) < (*r2).x);
	LA5_: ;
	T1_ = T2_;
	if (T1_) goto LA6_;
	nimln_(39, "mathutils.nim");
	T1_ = (((NF)((*r1).x) + (NF)((*r1).height)) < (*r2).y);
	LA6_: ;
	result = !(T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, map_tcJaJlmc3vBjg9cZeSydtYw)(tyObject_Region_qDqbve6hasFbbcoIpab4Lg* src, tyObject_Region_qDqbve6hasFbbcoIpab4Lg* dest) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	NF kx;
	NF ky;
	nimfr_("map", "mathutils.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(43, "mathutils.nim");
	kx = ((NF)(((NF)((*dest).x1) - (NF)((*dest).x0))) / (NF)(((NF)((*src).x1) - (NF)((*src).x0))));
	nimln_(44, "mathutils.nim");
	ky = ((NF)(((NF)((*dest).y1) - (NF)((*dest).y0))) / (NF)(((NF)((*src).y1) - (NF)((*src).y0))));
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.data[0][0] = kx;
	result.data[0][1] = 0.0;
	nimln_(47, "mathutils.nim");
	result.data[0][2] = ((NF)((*dest).x0) - (NF)(((NF)((*src).x0) * (NF)(kx))));
	result.data[1][0] = 0.0;
	result.data[1][1] = ky;
	nimln_(48, "mathutils.nim");
	result.data[1][2] = ((NF)((*dest).y0) - (NF)(((NF)((*src).y0) * (NF)(ky))));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_mathutilsInit000)(void) {
	nimfr_("mathutils", "mathutils.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_mathutilsDatInit000)(void) {
}

