/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\nimPNG_buffer.o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\nimPNG_buffer.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg {
NimStringDesc* data;
NI offset;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_sflb9aWnophQqZhIF3xzdCg_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(void, subbuffer_CJq2QvCkG9anJo9arrEHuLmw)(tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg b, NI offset, tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg* Result) {
	NI TM_BmQMqGTG4BLSjpCm79awG5A_3;
	nimfr_("subbuffer", "buffer.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_sflb9aWnophQqZhIF3xzdCg_));
	nimln_(20, "buffer.nim");
	unsureAsgnRef((void**) (&(*Result).data), b.data);
	nimln_(21, "buffer.nim");
	TM_BmQMqGTG4BLSjpCm79awG5A_3 = addInt(b.offset, offset);
	(*Result).offset = (NI)(TM_BmQMqGTG4BLSjpCm79awG5A_3);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initBuffer_Z9bCY3WvXXok7r8z88NuwNw)(NimStringDesc* d, tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg* Result) {
	nimfr_("initBuffer", "buffer.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_sflb9aWnophQqZhIF3xzdCg_));
	nimln_(17, "buffer.nim");
	unsureAsgnRef((void**) (&(*Result).data), d);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, nimPNG_bufferInit000)(void) {
	nimfr_("buffer", "buffer.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, nimPNG_bufferDatInit000)(void) {
static TNimNode* TM_BmQMqGTG4BLSjpCm79awG5A_2[2];
static TNimNode TM_BmQMqGTG4BLSjpCm79awG5A_0[3];
NTI_sflb9aWnophQqZhIF3xzdCg_.size = sizeof(tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg);
NTI_sflb9aWnophQqZhIF3xzdCg_.kind = 18;
NTI_sflb9aWnophQqZhIF3xzdCg_.base = 0;
NTI_sflb9aWnophQqZhIF3xzdCg_.flags = 2;
TM_BmQMqGTG4BLSjpCm79awG5A_2[0] = &TM_BmQMqGTG4BLSjpCm79awG5A_0[1];
TM_BmQMqGTG4BLSjpCm79awG5A_0[1].kind = 1;
TM_BmQMqGTG4BLSjpCm79awG5A_0[1].offset = offsetof(tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg, data);
TM_BmQMqGTG4BLSjpCm79awG5A_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_BmQMqGTG4BLSjpCm79awG5A_0[1].name = "data";
TM_BmQMqGTG4BLSjpCm79awG5A_2[1] = &TM_BmQMqGTG4BLSjpCm79awG5A_0[2];
TM_BmQMqGTG4BLSjpCm79awG5A_0[2].kind = 1;
TM_BmQMqGTG4BLSjpCm79awG5A_0[2].offset = offsetof(tyObject_Buffer_sflb9aWnophQqZhIF3xzdCg, offset);
TM_BmQMqGTG4BLSjpCm79awG5A_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_BmQMqGTG4BLSjpCm79awG5A_0[2].name = "offset";
TM_BmQMqGTG4BLSjpCm79awG5A_0[0].len = 2; TM_BmQMqGTG4BLSjpCm79awG5A_0[0].kind = 2; TM_BmQMqGTG4BLSjpCm79awG5A_0[0].sons = &TM_BmQMqGTG4BLSjpCm79awG5A_2[0];
NTI_sflb9aWnophQqZhIF3xzdCg_.node = &TM_BmQMqGTG4BLSjpCm79awG5A_0[0];
}

