/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\spritebatch.o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\spritebatch.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg;
typedef struct tyObject_Program_5U307oTET301CaFCP809big tyObject_Program_5U307oTET301CaFCP809big;
typedef struct tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw;
typedef struct tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw;
typedef struct tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ;
typedef struct tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w;
typedef struct tyTuple_2U9aQqMEBcSEoidI9cRa4P0A tyTuple_2U9aQqMEBcSEoidI9cRa4P0A;
typedef struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ;
typedef struct tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NF32 tyArray_oyZrYU9bPA1n9b1MM23cnzzQ[12288];
typedef NU8 tyArray_tWovyCrDXxvtzvQ5q9awdWA[24576];
struct tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw {
NI32 coords;
NI32 colors;
NI32 tex_coords;
NI32 texture;
};
struct tyObject_Program_5U307oTET301CaFCP809big {
NU32 handle;
tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw locations;
};
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
typedef tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ tyArray_lyzHzk9aModN4FAni3DbC4Q[2];
struct tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw {
tyArray_lyzHzk9aModN4FAni3DbC4Q data;
};
struct tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg {
NI coordIdx;
NI colorIdx;
NI texCoordIdx;
tyArray_oyZrYU9bPA1n9b1MM23cnzzQ coordData;
tyArray_tWovyCrDXxvtzvQ5q9awdWA colorData;
tyArray_oyZrYU9bPA1n9b1MM23cnzzQ texCoordData;
NU32 coordBuff;
NU32 colorBuff;
NU32 texCoordBuff;
tyObject_Program_5U307oTET301CaFCP809big program;
NU32 lastTexHandle;
tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw projection;
};
struct tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w {
NF x;
NF y;
};
struct tyTuple_2U9aQqMEBcSEoidI9cRa4P0A {
NF32 Field0;
NF32 Field1;
};
struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ {
NI width;
NI height;
NU32 handle;
};
struct tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ {
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ texture;
NF u0;
NF v0;
NF u1;
NF v1;
};
struct tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw {
NF u0;
NF v0;
NF u1;
NF v1;
NI width;
NI height;
NI logicalWidth;
NI logicalHeight;
NI xoffs;
NI yoffs;
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex;
NI page;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg, newSpriteBatch_Rx4s9cI3qy4Qwal5QjiqUBw)(tyObject_Program_5U307oTET301CaFCP809big program);
N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(NU32, createVbo_19cMypki1TDjfDJ6InDUeaw)(NF32* data, NI dataLen_0, NU32 usage);
N_LIB_PRIVATE N_NIMCALL(NU32, createVbo_BgyX5TYbUOhVcBnHDSpA1g)(NU8* data, NI dataLen_0, NU32 usage);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, initAffine2_HkU9b8hEpERxwbgBWllafBw)(void);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, pushCoord_rWY5hfKDJ5nUzCfafTrWww)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NF32 x, NF32 y);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, pushColor_UGVLPOtXjGhsMJEIckr1uQ)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NU8 r, NU8 g, NU8 b, NU8 a);
N_LIB_PRIVATE N_NIMCALL(void, pushTexCoord_j6cjWlq1IbBd6e8gADiUgw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NF32 u, NF32 v);
N_LIB_PRIVATE N_NIMCALL(void, flush_GHonqE9aQDzibr6yQNKdk3A)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch);
N_LIB_PRIVATE N_STDCALL(void, glBindBuffer_3rtrqe5eYHMVBLzlqTY63w)(NU32 target, NU32 buffer);
N_LIB_PRIVATE N_STDCALL(void, glBufferSubData_ZuBlSQcG0v7PWXIwsqHIEQ)(NU32 target, NI offset, NI size, void* data);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_LIB_PRIVATE N_STDCALL(void, glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA)(NU32 index);
N_LIB_PRIVATE N_STDCALL(void, glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer);
N_LIB_PRIVATE N_STDCALL(void, glUseProgram_bYudX2ps2dTBClLz2NbyzA_2)(NU32 program);
N_LIB_PRIVATE N_STDCALL(void, glUniform1i_JXFx8pP9cft9ayhvOovLEZsg)(NI32 location, NI32 v0);
N_LIB_PRIVATE N_STDCALL(void, glDrawArrays_Bw7cKcZtx9bAbZdj5Iw9af9ag)(NU32 mode, NI32 first, NI32 count);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(void, draw_pQ5brsoK64QeCTY9a7fPMKw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ* reg, NF x, NF y, NF w, NF h, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, mul_RgJ9a9ayQVggHe2rYxWmgGng)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* other);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, trn_KtcIlianA9cBWtuFxek3DBw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF tx, NF ty);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, apply_p2hhysjrPPCLAqoXUm4Bdw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* m, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, vec2_z7NVGxkcNytqrcErd3MEzg)(NF x, NF y);
N_LIB_PRIVATE N_STDCALL(void, glBindTexture_shJfrHWoymy1BbmsKpC7Xg)(NU32 target, NU32 texture);
N_LIB_PRIVATE N_NIMCALL(void, draw_8xKkap9cO7xaeq4Nsva9aaIQ)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NF x, NF y, NF w, NF h, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, scl_QAwj9c14NoZ5U318weiZWZQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF sx, NF sy);
N_LIB_PRIVATE N_NIMCALL(void, draw_kECRGozRSj9clVJ3HQ1JilQ)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NF x, NF y, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf);
N_LIB_PRIVATE N_NIMCALL(void, drawWithWidth_UMT1TcZSLBXL02XpBZ7afg)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NF x, NF y, NF width, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf);
N_LIB_PRIVATE N_NIMCALL(void, drawWithHeight_D2yWkvgoJyig8G5uEkNi4A)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NF x, NF y, NF height, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf);
N_LIB_PRIVATE N_NIMCALL(void, draw_NIwQSRD025UZcYXZogXm6g)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NF x, NF y, NF width, NF height);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ, makeTextureRegion_10Ua2psAivWdjmRBQsvDtA)(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NI x, NI y, NI width, NI height);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_5U307oTET301CaFCP809big_;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_;
TNimType NTI_w5LtLI9bobxLoIavQIQCGAw_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg, newSpriteBatch_Rx4s9cI3qy4Qwal5QjiqUBw)(tyObject_Program_5U307oTET301CaFCP809big program) {
	tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg result;
	tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg batch;
	nimfr_("newSpriteBatch", "spritebatch.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(41, "spritebatch.nim");
	chckNil((void*)(&batch));
	memset((void*)(&batch), 0, sizeof(batch));
	nimln_(42, "spritebatch.nim");
	batch.coordBuff = createVbo_19cMypki1TDjfDJ6InDUeaw(batch.coordData, 12288, ((NU32) 35048));
	nimln_(43, "spritebatch.nim");
	batch.colorBuff = createVbo_BgyX5TYbUOhVcBnHDSpA1g(batch.colorData, 24576, ((NU32) 35048));
	nimln_(44, "spritebatch.nim");
	batch.texCoordBuff = createVbo_19cMypki1TDjfDJ6InDUeaw(batch.texCoordData, 12288, ((NU32) 35048));
	nimln_(45, "spritebatch.nim");
	batch.program = program;
	nimln_(46, "spritebatch.nim");
	batch.projection = initAffine2_HkU9b8hEpERxwbgBWllafBw();
	nimln_(47, "spritebatch.nim");
	result = batch;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, pushCoord_rWY5hfKDJ5nUzCfafTrWww)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NF32 x, NF32 y) {
	NI TM_DRmnSAPZdQrD3q2oC62tTA_2;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_3;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_4;
	nimfr_("pushCoord", "spritebatch.nim");
	nimln_(50, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_2 = addInt((*batch).coordIdx, ((NI) 0));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_2)) > (NU)(12287)) raiseIndexError();
	(*batch).coordData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_2))- 0] = x;
	nimln_(51, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_3 = addInt((*batch).coordIdx, ((NI) 1));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_3)) > (NU)(12287)) raiseIndexError();
	(*batch).coordData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_3))- 0] = y;
	nimln_(52, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_4 = addInt((*batch).coordIdx, ((NI) 2));
	(*batch).coordIdx = (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_4);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, pushColor_UGVLPOtXjGhsMJEIckr1uQ)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NU8 r, NU8 g, NU8 b, NU8 a) {
	NI TM_DRmnSAPZdQrD3q2oC62tTA_5;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_6;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_7;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_8;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_9;
	nimfr_("pushColor", "spritebatch.nim");
	nimln_(55, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_5 = addInt((*batch).colorIdx, ((NI) 0));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_5)) > (NU)(24575)) raiseIndexError();
	(*batch).colorData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_5))- 0] = r;
	nimln_(56, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_6 = addInt((*batch).colorIdx, ((NI) 1));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_6)) > (NU)(24575)) raiseIndexError();
	(*batch).colorData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_6))- 0] = g;
	nimln_(57, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_7 = addInt((*batch).colorIdx, ((NI) 2));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_7)) > (NU)(24575)) raiseIndexError();
	(*batch).colorData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_7))- 0] = b;
	nimln_(58, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_8 = addInt((*batch).colorIdx, ((NI) 3));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_8)) > (NU)(24575)) raiseIndexError();
	(*batch).colorData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_8))- 0] = a;
	nimln_(59, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_9 = addInt((*batch).colorIdx, ((NI) 4));
	(*batch).colorIdx = (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_9);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, pushTexCoord_j6cjWlq1IbBd6e8gADiUgw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NF32 u, NF32 v) {
	NI TM_DRmnSAPZdQrD3q2oC62tTA_10;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_11;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_12;
	nimfr_("pushTexCoord", "spritebatch.nim");
	nimln_(62, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_10 = addInt((*batch).texCoordIdx, ((NI) 0));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_10)) > (NU)(12287)) raiseIndexError();
	(*batch).texCoordData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_10))- 0] = u;
	nimln_(63, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_11 = addInt((*batch).texCoordIdx, ((NI) 1));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_11)) > (NU)(12287)) raiseIndexError();
	(*batch).texCoordData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_11))- 0] = v;
	nimln_(64, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_12 = addInt((*batch).texCoordIdx, ((NI) 2));
	(*batch).texCoordIdx = (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_12);
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, flush_GHonqE9aQDzibr6yQNKdk3A)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch) {
	tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw* locs;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_13;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_15;
	nimfr_("flush", "spritebatch.nim");
{	nimln_(67, "spritebatch.nim");
	{
		if (!((*batch).coordIdx == ((NI) 0))) goto LA3_;
		nimln_(68, "spritebatch.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(70, "spritebatch.nim");
	locs = (&(*batch).program.locations);
	nimln_(72, "spritebatch.nim");
	glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), (*batch).coordBuff);
	nimln_(73, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_13 = mulInt((*batch).coordIdx, ((NI) 4));
	glBufferSubData_ZuBlSQcG0v7PWXIwsqHIEQ(((NU32) 34962), ((NI) 0), (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_13), ((void*) ((*batch).coordData)));
	nimln_(74, "spritebatch.nim");
	glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(((NU32) ((*locs).coords)));
	nimln_(75, "spritebatch.nim");
	glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(((NU32) ((*locs).coords)), ((NI32) 2), ((NU32) 5126), NIM_FALSE, ((NI32) 0), NIM_NIL);
	nimln_(77, "spritebatch.nim");
	{
		nimln_(398, "system.nim");
		nimln_(77, "spritebatch.nim");
		if (!!(((*locs).colors == ((NI32) -1)))) goto LA7_;
		nimln_(78, "spritebatch.nim");
		glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), (*batch).colorBuff);
		nimln_(79, "spritebatch.nim");
		glBufferSubData_ZuBlSQcG0v7PWXIwsqHIEQ(((NU32) 34962), ((NI) 0), (*batch).colorIdx, ((void*) ((*batch).colorData)));
		nimln_(80, "spritebatch.nim");
		glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(((NU32) ((*locs).colors)));
		nimln_(81, "spritebatch.nim");
		glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(((NU32) ((*locs).colors)), ((NI32) 4), ((NU32) 5121), NIM_TRUE, ((NI32) 0), NIM_NIL);
	}
	LA7_: ;
	nimln_(83, "spritebatch.nim");
	{
		NI TM_DRmnSAPZdQrD3q2oC62tTA_14;
		nimln_(398, "system.nim");
		nimln_(83, "spritebatch.nim");
		if (!!(((*locs).tex_coords == ((NI32) -1)))) goto LA11_;
		nimln_(84, "spritebatch.nim");
		glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), (*batch).texCoordBuff);
		nimln_(85, "spritebatch.nim");
		TM_DRmnSAPZdQrD3q2oC62tTA_14 = mulInt((*batch).texCoordIdx, ((NI) 4));
		glBufferSubData_ZuBlSQcG0v7PWXIwsqHIEQ(((NU32) 34962), ((NI) 0), (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_14), ((void*) ((*batch).texCoordData)));
		nimln_(86, "spritebatch.nim");
		glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(((NU32) ((*locs).tex_coords)));
		nimln_(87, "spritebatch.nim");
		glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(((NU32) ((*locs).tex_coords)), ((NI32) 2), ((NU32) 5126), NIM_FALSE, ((NI32) 0), NIM_NIL);
	}
	LA11_: ;
	nimln_(89, "spritebatch.nim");
	glUseProgram_bYudX2ps2dTBClLz2NbyzA_2((*batch).program.handle);
	nimln_(90, "spritebatch.nim");
	glUniform1i_JXFx8pP9cft9ayhvOovLEZsg((*locs).texture, ((NI32) 0));
	nimln_(91, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_15 = divInt((*batch).coordIdx, ((NI) 2));
	glDrawArrays_Bw7cKcZtx9bAbZdj5Iw9af9ag(((NU32) 4), ((NI32) 0), ((NI32)chckRange((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_15), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
	nimln_(93, "spritebatch.nim");
	(*batch).coordIdx = ((NI) 0);
	nimln_(94, "spritebatch.nim");
	(*batch).colorIdx = ((NI) 0);
	nimln_(95, "spritebatch.nim");
	(*batch).texCoordIdx = ((NI) 0);
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_pQ5brsoK64QeCTY9a7fPMKw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ* reg, NF x, NF y, NF w, NF h, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw m;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T1_;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v0;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T2_;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v1;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T3_;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v2;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T4_;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v3;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T5_;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T6_;
	NF32 x0;
	NF32 y0;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T7_;
	NF32 x1;
	NF32 y1;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T8_;
	NF32 x2;
	NF32 y2;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T9_;
	NF32 x3;
	NF32 y3;
	nimfr_("draw", "spritebatch.nim");
	nimln_(100, "spritebatch.nim");
	T1_ = trn_KtcIlianA9cBWtuFxek3DBw((&(*batch).projection), x, y);
	m = mul_RgJ9a9ayQVggHe2rYxWmgGng((&T1_), transf);
	nimln_(101, "spritebatch.nim");
	T2_ = vec2_z7NVGxkcNytqrcErd3MEzg(0.0, 0.0);
	v0 = apply_p2hhysjrPPCLAqoXUm4Bdw((&m), T2_);
	nimln_(102, "spritebatch.nim");
	T3_ = vec2_z7NVGxkcNytqrcErd3MEzg(w, 0.0);
	v1 = apply_p2hhysjrPPCLAqoXUm4Bdw((&m), T3_);
	nimln_(103, "spritebatch.nim");
	T4_ = vec2_z7NVGxkcNytqrcErd3MEzg(w, h);
	v2 = apply_p2hhysjrPPCLAqoXUm4Bdw((&m), T4_);
	nimln_(104, "spritebatch.nim");
	T5_ = vec2_z7NVGxkcNytqrcErd3MEzg(0.0, h);
	v3 = apply_p2hhysjrPPCLAqoXUm4Bdw((&m), T5_);
	nimln_(106, "spritebatch.nim");
	T6_.Field0 = ((NF32) (v0.x));
	T6_.Field1 = ((NF32) (v0.y));
	x0 = T6_.Field0;
	y0 = T6_.Field1;
	nimln_(107, "spritebatch.nim");
	T7_.Field0 = ((NF32) (v1.x));
	T7_.Field1 = ((NF32) (v1.y));
	x1 = T7_.Field0;
	y1 = T7_.Field1;
	nimln_(108, "spritebatch.nim");
	T8_.Field0 = ((NF32) (v2.x));
	T8_.Field1 = ((NF32) (v2.y));
	x2 = T8_.Field0;
	y2 = T8_.Field1;
	nimln_(109, "spritebatch.nim");
	T9_.Field0 = ((NF32) (v3.x));
	T9_.Field1 = ((NF32) (v3.y));
	x3 = T9_.Field0;
	y3 = T9_.Field1;
	nimln_(111, "spritebatch.nim");
	{
		nimln_(398, "system.nim");
		nimln_(111, "spritebatch.nim");
		if (!!(((*reg).texture.handle == (*batch).lastTexHandle))) goto LA12_;
		nimln_(112, "spritebatch.nim");
		flush_GHonqE9aQDzibr6yQNKdk3A(batch);
		nimln_(113, "spritebatch.nim");
		(*batch).lastTexHandle = (*reg).texture.handle;
		nimln_(114, "spritebatch.nim");
		glBindTexture_shJfrHWoymy1BbmsKpC7Xg(((NU32) 3553), (*reg).texture.handle);
	}
	LA12_: ;
	nimln_(116, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x0, y0);
	nimln_(117, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(118, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v0)));
	nimln_(120, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x1, y1);
	nimln_(121, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(122, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v0)));
	nimln_(124, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x2, y2);
	nimln_(125, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(126, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v1)));
	nimln_(128, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x2, y2);
	nimln_(129, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(130, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v1)));
	nimln_(132, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x3, y3);
	nimln_(133, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(134, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v1)));
	nimln_(136, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x0, y0);
	nimln_(137, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(138, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v0)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_8xKkap9cO7xaeq4Nsva9aaIQ)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NF x, NF y, NF w, NF h, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw m;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T1_;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T2_;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v0;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T3_;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v1;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_16;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T4_;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v2;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_17;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_18;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T5_;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v3;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_19;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T6_;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T7_;
	NF32 x0;
	NF32 y0;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T8_;
	NF32 x1;
	NF32 y1;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T9_;
	NF32 x2;
	NF32 y2;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T10_;
	NF32 x3;
	NF32 y3;
	nimfr_("draw", "spritebatch.nim");
	nimln_(142, "spritebatch.nim");
	T1_ = trn_KtcIlianA9cBWtuFxek3DBw((&(*batch).projection), x, y);
	T2_ = mul_RgJ9a9ayQVggHe2rYxWmgGng((&T1_), transf);
	nimln_(145, "spritebatch.nim");
	m = scl_QAwj9c14NoZ5U318weiZWZQ((&T2_), ((NF)(w) / (NF)(((NF) ((*reg).logicalWidth)))), ((NF)(h) / (NF)(((NF) ((*reg).logicalHeight)))));
	nimln_(147, "spritebatch.nim");
	T3_ = vec2_z7NVGxkcNytqrcErd3MEzg(((NF) ((*reg).xoffs)), ((NF) ((*reg).yoffs)));
	v0 = apply_p2hhysjrPPCLAqoXUm4Bdw((&m), T3_);
	nimln_(148, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_16 = addInt((*reg).xoffs, (*reg).width);
	T4_ = vec2_z7NVGxkcNytqrcErd3MEzg(((NF) ((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_16))), ((NF) ((*reg).yoffs)));
	v1 = apply_p2hhysjrPPCLAqoXUm4Bdw((&m), T4_);
	nimln_(149, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_17 = addInt((*reg).xoffs, (*reg).width);
	TM_DRmnSAPZdQrD3q2oC62tTA_18 = addInt((*reg).yoffs, (*reg).height);
	T5_ = vec2_z7NVGxkcNytqrcErd3MEzg(((NF) ((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_17))), ((NF) ((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_18))));
	v2 = apply_p2hhysjrPPCLAqoXUm4Bdw((&m), T5_);
	nimln_(150, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_19 = addInt((*reg).yoffs, (*reg).height);
	T6_ = vec2_z7NVGxkcNytqrcErd3MEzg(((NF) ((*reg).xoffs)), ((NF) ((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_19))));
	v3 = apply_p2hhysjrPPCLAqoXUm4Bdw((&m), T6_);
	nimln_(152, "spritebatch.nim");
	T7_.Field0 = ((NF32) (v0.x));
	T7_.Field1 = ((NF32) (v0.y));
	x0 = T7_.Field0;
	y0 = T7_.Field1;
	nimln_(153, "spritebatch.nim");
	T8_.Field0 = ((NF32) (v1.x));
	T8_.Field1 = ((NF32) (v1.y));
	x1 = T8_.Field0;
	y1 = T8_.Field1;
	nimln_(154, "spritebatch.nim");
	T9_.Field0 = ((NF32) (v2.x));
	T9_.Field1 = ((NF32) (v2.y));
	x2 = T9_.Field0;
	y2 = T9_.Field1;
	nimln_(155, "spritebatch.nim");
	T10_.Field0 = ((NF32) (v3.x));
	T10_.Field1 = ((NF32) (v3.y));
	x3 = T10_.Field0;
	y3 = T10_.Field1;
	nimln_(157, "spritebatch.nim");
	{
		nimln_(398, "system.nim");
		nimln_(157, "spritebatch.nim");
		if (!!(((*reg).tex.handle == (*batch).lastTexHandle))) goto LA13_;
		nimln_(158, "spritebatch.nim");
		flush_GHonqE9aQDzibr6yQNKdk3A(batch);
		nimln_(159, "spritebatch.nim");
		(*batch).lastTexHandle = (*reg).tex.handle;
		nimln_(160, "spritebatch.nim");
		glBindTexture_shJfrHWoymy1BbmsKpC7Xg(((NU32) 3553), (*reg).tex.handle);
	}
	LA13_: ;
	nimln_(162, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x0, y0);
	nimln_(163, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(164, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v0)));
	nimln_(166, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x1, y1);
	nimln_(167, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(168, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v0)));
	nimln_(170, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x2, y2);
	nimln_(171, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(172, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v1)));
	nimln_(174, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x2, y2);
	nimln_(175, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(176, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v1)));
	nimln_(178, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x3, y3);
	nimln_(179, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(180, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v1)));
	nimln_(182, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x0, y0);
	nimln_(183, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(184, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v0)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_kECRGozRSj9clVJ3HQ1JilQ)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NF x, NF y, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf) {
	nimfr_("draw", "spritebatch.nim");
	nimln_(192, "spritebatch.nim");
	draw_8xKkap9cO7xaeq4Nsva9aaIQ(batch, reg, x, y, ((NF) ((*reg).logicalWidth)), ((NF) ((*reg).logicalHeight)), transf);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, drawWithWidth_UMT1TcZSLBXL02XpBZ7afg)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NF x, NF y, NF width, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf) {
	nimfr_("drawWithWidth", "spritebatch.nim");
	nimln_(196, "spritebatch.nim");
	draw_8xKkap9cO7xaeq4Nsva9aaIQ(batch, reg, x, y, width, ((NF)(((NF)(((NF) ((*reg).logicalHeight))) * (NF)(width))) / (NF)(((NF) ((*reg).logicalWidth)))), transf);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, drawWithHeight_D2yWkvgoJyig8G5uEkNi4A)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NF x, NF y, NF height, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* transf) {
	nimfr_("drawWithHeight", "spritebatch.nim");
	nimln_(200, "spritebatch.nim");
	draw_8xKkap9cO7xaeq4Nsva9aaIQ(batch, reg, x, y, ((NF)(((NF)(((NF) ((*reg).logicalWidth))) * (NF)(height))) / (NF)(((NF) ((*reg).logicalHeight)))), height, transf);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_NIwQSRD025UZcYXZogXm6g)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NF x, NF y, NF width, NF height) {
	tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ T1_;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T2_;
	nimfr_("draw", "spritebatch.nim");
	nimln_(203, "spritebatch.nim");
	T1_ = makeTextureRegion_10Ua2psAivWdjmRBQsvDtA(tex, ((NI) 0), ((NI) 0), tex.width, tex.height);
	nimln_(99, "spritebatch.nim");
	T2_ = initAffine2_HkU9b8hEpERxwbgBWllafBw();
	draw_pQ5brsoK64QeCTY9a7fPMKw(batch, (&T1_), x, y, width, height, (&T2_));
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, unknown_spritebatchInit000)(void) {
	nimfr_("spritebatch", "spritebatch.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_spritebatchDatInit000)(void) {
static TNimNode* TM_DRmnSAPZdQrD3q2oC62tTA_20[2];
static TNimNode* TM_DRmnSAPZdQrD3q2oC62tTA_21[4];
static TNimNode TM_DRmnSAPZdQrD3q2oC62tTA_0[8];
NTI_5U307oTET301CaFCP809big_.size = sizeof(tyObject_Program_5U307oTET301CaFCP809big);
NTI_5U307oTET301CaFCP809big_.kind = 18;
NTI_5U307oTET301CaFCP809big_.base = 0;
NTI_5U307oTET301CaFCP809big_.flags = 3;
TM_DRmnSAPZdQrD3q2oC62tTA_20[0] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[1];
TM_DRmnSAPZdQrD3q2oC62tTA_0[1].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[1].offset = offsetof(tyObject_Program_5U307oTET301CaFCP809big, handle);
TM_DRmnSAPZdQrD3q2oC62tTA_0[1].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[1].name = "handle";
TM_DRmnSAPZdQrD3q2oC62tTA_20[1] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[2];
NTI_w5LtLI9bobxLoIavQIQCGAw_.size = sizeof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw);
NTI_w5LtLI9bobxLoIavQIQCGAw_.kind = 18;
NTI_w5LtLI9bobxLoIavQIQCGAw_.base = 0;
NTI_w5LtLI9bobxLoIavQIQCGAw_.flags = 3;
TM_DRmnSAPZdQrD3q2oC62tTA_21[0] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[4];
TM_DRmnSAPZdQrD3q2oC62tTA_0[4].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[4].offset = offsetof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, coords);
TM_DRmnSAPZdQrD3q2oC62tTA_0[4].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[4].name = "coords";
TM_DRmnSAPZdQrD3q2oC62tTA_21[1] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[5];
TM_DRmnSAPZdQrD3q2oC62tTA_0[5].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[5].offset = offsetof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, colors);
TM_DRmnSAPZdQrD3q2oC62tTA_0[5].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[5].name = "colors";
TM_DRmnSAPZdQrD3q2oC62tTA_21[2] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[6];
TM_DRmnSAPZdQrD3q2oC62tTA_0[6].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[6].offset = offsetof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, tex_coords);
TM_DRmnSAPZdQrD3q2oC62tTA_0[6].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[6].name = "tex_coords";
TM_DRmnSAPZdQrD3q2oC62tTA_21[3] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[7];
TM_DRmnSAPZdQrD3q2oC62tTA_0[7].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[7].offset = offsetof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, texture);
TM_DRmnSAPZdQrD3q2oC62tTA_0[7].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[7].name = "texture";
TM_DRmnSAPZdQrD3q2oC62tTA_0[3].len = 4; TM_DRmnSAPZdQrD3q2oC62tTA_0[3].kind = 2; TM_DRmnSAPZdQrD3q2oC62tTA_0[3].sons = &TM_DRmnSAPZdQrD3q2oC62tTA_21[0];
NTI_w5LtLI9bobxLoIavQIQCGAw_.node = &TM_DRmnSAPZdQrD3q2oC62tTA_0[3];
TM_DRmnSAPZdQrD3q2oC62tTA_0[2].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[2].offset = offsetof(tyObject_Program_5U307oTET301CaFCP809big, locations);
TM_DRmnSAPZdQrD3q2oC62tTA_0[2].typ = (&NTI_w5LtLI9bobxLoIavQIQCGAw_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[2].name = "locations";
TM_DRmnSAPZdQrD3q2oC62tTA_0[0].len = 2; TM_DRmnSAPZdQrD3q2oC62tTA_0[0].kind = 2; TM_DRmnSAPZdQrD3q2oC62tTA_0[0].sons = &TM_DRmnSAPZdQrD3q2oC62tTA_20[0];
NTI_5U307oTET301CaFCP809big_.node = &TM_DRmnSAPZdQrD3q2oC62tTA_0[0];
}

