/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\spriteatlasloader.o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\spriteatlasloader.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q;
typedef struct tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw;
typedef struct tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ;
typedef struct tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A;
typedef struct tySequence_uTDAVJgt4heRKwc9cJkhwhw tySequence_uTDAVJgt4heRKwc9cJkhwhw;
typedef struct tySequence_fQOhtRDCMDpsajodiC1WLg tySequence_fQOhtRDCMDpsajodiC1WLg;
typedef struct tyObject_RegDesc_S7CGpRr9aRGBYfCm5btR88w tyObject_RegDesc_S7CGpRr9aRGBYfCm5btR88w;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_SpriteAtlas_Dr8eFJ8wQTh9bq2RTD6JXyg tyObject_SpriteAtlas_Dr8eFJ8wQTh9bq2RTD6JXyg;
typedef struct tySequence_WzvE7PdLW9bdyTHkZUG6C0Q tySequence_WzvE7PdLW9bdyTHkZUG6C0Q;
typedef struct tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g;
typedef struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyTuple_C80qVni9bN9alMWam2oML36Q tyTuple_C80qVni9bN9alMWam2oML36Q;
typedef struct tyTuple_PlkGsuz7STQxey5DAiEKnQ tyTuple_PlkGsuz7STQxey5DAiEKnQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw {
NimStringDesc* data;
NI pos;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A {
tySequence_uTDAVJgt4heRKwc9cJkhwhw* data;
NI counter;
};
struct tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q {
tySequence_fQOhtRDCMDpsajodiC1WLg* data;
NI counter;
};
struct tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ {
NIM_BOOL leaf;
union{
struct {tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A regs;
} S1;
struct {tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q dir;
} S2;
} leafU;
};
struct tyObject_RegDesc_S7CGpRr9aRGBYfCm5btR88w {
NimStringDesc* name;
NI x;
NI y;
NI width;
NI height;
NI logicalWidth;
NI logicalHeight;
NI xoffs;
NI yoffs;
NI index;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_SpriteAtlas_Dr8eFJ8wQTh9bq2RTD6JXyg {
tySequence_WzvE7PdLW9bdyTHkZUG6C0Q* pages;
tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q dir;
};
struct tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g {
NI width;
NI height;
NimStringDesc* path;
};
struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ {
NI width;
NI height;
NU32 handle;
};
struct tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw {
NF u0;
NF v0;
NF u1;
NF v1;
NI width;
NI height;
NI logicalWidth;
NI logicalHeight;
NI xoffs;
NI yoffs;
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex;
NI page;
};
struct tyTuple_C80qVni9bN9alMWam2oML36Q {
NI Field0;
NimStringDesc* Field1;
tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ Field2;
};
typedef NimStringDesc* tyArray_24KAM9afIUgUaqBaEBB6r9bg[3];
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
struct tyTuple_PlkGsuz7STQxey5DAiEKnQ {
NI Field0;
NI Field1;
tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw Field2;
};
typedef struct {
N_NIMCALL_PTR(NI, ClP_0) (NI x, NI y, void* ClE_0);
void* ClE_0;
} tyProc_fDD7zVPPl59bNBu4ChTEQeQ;
typedef NU8 tyEnum_SortOrder_8iBc6wlNqBa9cju9cUAhUAxA;
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_WzvE7PdLW9bdyTHkZUG6C0Q {
  TGenericSeq Sup;
  tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_uTDAVJgt4heRKwc9cJkhwhw {
  TGenericSeq Sup;
  tyTuple_PlkGsuz7STQxey5DAiEKnQ data[SEQ_DECL_SIZE];
};
struct tySequence_fQOhtRDCMDpsajodiC1WLg {
  TGenericSeq Sup;
  tyTuple_C80qVni9bN9alMWam2oML36Q data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atEnd_NVY9c8Pn0NAkURXlVXSRJqA)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw stream);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, readChar_TsojS3Vt9cSwkBauw4qpvLA)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* stream);
N_NOINLINE(void, raiseIndexError)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine_9aOHgpnIHcRo6QFN509cEkJQ)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* s, NimStringDesc** line);
N_NIMCALL(NimStringDesc*, setLengthStr)(NimStringDesc* s, NI newLen);
N_NIMCALL(NimStringDesc*, addChar)(NimStringDesc* s, NIM_CHAR c);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, peekLine_9aOHgpnIHcRo6QFN509cEkJQ_2)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* s, NimStringDesc** line);
N_LIB_PRIVATE N_NIMCALL(void, initCtsStream_cZEwPPJU9c9aBg5RB9bg9bmPAw)(NimStringDesc* data, tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* Result);
N_NOINLINE(void, chckNil)(void* p);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_LIB_PRIVATE N_NIMCALL(void, insertReg_cCItPLlEVf9boS51TDye5Yg)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* root, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NI index, NimStringDesc** path, NI pathLen_0, NI start);
static N_INLINE(NI, subInt)(NI a, NI b);
N_LIB_PRIVATE N_NIMCALL(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ*, mgetOrPut_72R8U6ss4ZI9cxlHSH5N1hw)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* t, NimStringDesc* key, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ val);
N_LIB_PRIVATE N_NIMCALL(void, initTable_VpFKAGy3QS4KetRNn6XNlQ)(NI initialSize, tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* Result);
N_NOINLINE(void, raiseFieldError)(NimStringDesc* f);
N_LIB_PRIVATE N_NIMCALL(void, add_xdjKC0QLjR9bZBTz9ct9a1XyQ)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* t, NI key, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* val);
N_LIB_PRIVATE N_NIMCALL(void, initTable_9bEe79bLaUXK1rbPlj69c5wOQ)(NI initialSize, tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* Result);
N_LIB_PRIVATE N_NIMCALL(void, parseRegBlock_GQRA5uv7ZveovWyM6jSlmQ)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* stream, NI* lineCount, tyObject_RegDesc_S7CGpRr9aRGBYfCm5btR88w* reg);
static N_INLINE(NI, parseUntil_g9cfzCBmR6LwC5faTMHN5Ggspriteatlasloader)(NimStringDesc* s, NimStringDesc** token, NimStringDesc* until, NI start);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI start, NI last);
N_NIMCALL(NimStringDesc*, copyStrLast)(NimStringDesc* s, NI first, NI last);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
static N_INLINE(NI, skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader)(NimStringDesc* s, NimStringDesc* token, NI start);
N_LIB_PRIVATE N_NIMCALL(NI, parseIdent_tLWlhTCVyzkdnYs1ielKLg)(NimStringDesc* s, NimStringDesc** ident, NI start);
N_LIB_PRIVATE N_NIMCALL(NI, npuParseInt)(NimStringDesc* s, NI* number, NI start);
N_LIB_PRIVATE N_NIMCALL(void, parseAtlas_jZe5Up9b04IWS0NiqOlmF9cw)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* stream, tyObject_SpriteAtlas_Dr8eFJ8wQTh9bq2RTD6JXyg* atlas);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_WzvE7PdLW9bdyTHkZUG6C0Q)(void* p, NI op);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(tySequence_sM4lkSb7zS6F7OVMvW9cffQ*, nsuSplitString)(NimStringDesc* s, NimStringDesc* sep, NI maxsplit);
N_NIMCALL(TGenericSeq*, incrSeqV2)(TGenericSeq* seq, NI elemSize);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__lm5gTpG3wpvJqfh17uCCpA)(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ entry);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__AL4x9c75I1uxEnKAciW3OAA)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__mX8pQU7600LRrHVD6HOR9ag)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t);
N_LIB_PRIVATE N_NIMCALL(void, printDir_UBqDBxP3vzRgEEi1d3CCTw)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q dir, NimStringDesc* ind);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, X5BX5D__zcwPTNhPAum8RGgySuB6yw)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ* Result);
N_LIB_PRIVATE N_NIMCALL(void, printEntry_Ck1bmhzHeGCkUY6B0DzDuQ)(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ entry, NimStringDesc* ind);
static N_INLINE(NI, rawGet_OVftIzDoNNg1ML9adNJj9a2Qtables)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_9cBIHqYsh1oBSF5JO1TUMWQ)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_bRZGA9b9bqLuN3RTworf2D7Q)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* t, tySequence_fQOhtRDCMDpsajodiC1WLg** data, NimStringDesc* key, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_S9bfN6OPlbXf79cIz23P9cYAgtables)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_4Xl8scbDVmcdOPmoARONhA)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_pp6pu3dJY59cSOuBTSSB9cMQ)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* t, tySequence_uTDAVJgt4heRKwc9cJkhwhw** data, NI key, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* val, NI hc, NI h);
static N_INLINE(NI, rawGetDeep_9aeDPbhxF26fhAXAucq5Bgwtables)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key, NI* hc);
static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, len_O8KbWIdPuGdKZNJ8im9aOPw)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_P15pMNpPzeOrboQYn9b8YEQ)(NimStringDesc** s, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__4YDRv7sRJbqLmrh0coQr9cg)(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_uYpHostkmAgm4RjFRNh9cFA)(NimStringDesc** s, NF x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_qvv0VU7iDTo57MVp79aSbLw)(NimStringDesc** s, tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ x);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__RC2Ml9aESq3J2P79a9ciVC3MA)(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_tCZeWzrovTI04dLNbzimow)(NimStringDesc** s, NU32 x);
N_LIB_PRIVATE N_NIMCALL(NI, len_7XbOL9aqlP4K5ktPo2C4K1g)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_KHwyPEV6PV8Q9aS88ENydhw)(NimStringDesc** s, NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_UQQwT01he1jqp0OpJpqgzg)(NimStringDesc** s, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ x);
N_LIB_PRIVATE N_NIMCALL(NI, cmp_8Eruo47qvrfENwO9aWPZfBQ_3)(NI x, NI y);
N_LIB_PRIVATE N_NIMCALL(void, sort_84EnBzTXl9c1maQcyvYsKBQ)(NI* a, NI aLen_0, tyProc_fDD7zVPPl59bNBu4ChTEQeQ cmp, tyEnum_SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_LIB_PRIVATE N_NIMCALL(void, merge_3YlxpxWbu7ggyWNi6G1FdQ)(NI* a, NI aLen_0, NI* b, NI bLen_0, NI lo, NI m, NI hi, tyProc_fDD7zVPPl59bNBu4ChTEQeQ cmp, tyEnum_SortOrder_8iBc6wlNqBa9cju9cUAhUAxA order);
N_LIB_PRIVATE N_NIMCALL(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, X5BX5D__4A4fcN6iwGdI4Dri653RXA)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key);
static N_INLINE(NI, rawGet_9aeDPbhxF26fhAXAucq5Bgw_2tables)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key, NI* hc);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_FObehHmSKwAl6Yz9bwTsjiw_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
TNimType NTI_NdvWyrh1mMPCgDSZoEuCZQ_;
extern TNimType NTI_VaVACK0bpYmqIQ0mKcHfQQ_;
extern TNimType NTI_s9a6JMyQZ55Jz5fGce9aWo0A_;
extern TNimType NTI_VYUBB7iQgr6JV9bHeS0Ht7Q_;
extern TNimType NTI_yCEN9anxCD6mzBxGjuaRBdg_;
extern TNimType NTI_Gi06FkNeykJn7mrqRZYrkA_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TNimType NTI_PUESnDTGwFKYB1Hds1Rg6g_;
TNimType NTI_WzvE7PdLW9bdyTHkZUG6C0Q_;
TNimNode* NimDT__NdvWyrh1mMPCgDSZoEuCZQ_leaf[3];
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_5, "dir", 3);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_7, "regs", 4);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_8, "", 0);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_16, "scanl failed on line #", 22);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_18, "$*", 2);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_22, "  rotate: ", 10);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_26, "  rotate: $w", 12);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_28, "  xy: ", 6);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_31, ", ", 2);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_35, "  xy: $i, $i", 12);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_37, "  size: ", 8);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_43, "  size: $i, $i", 14);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_45, "  orig: ", 8);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_51, "  orig: $i, $i", 14);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_53, "  offset: ", 10);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_59, "  offset: $i, $i", 16);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_61, "  index: ", 9);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_65, "  index: $i", 11);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_72, "size: ", 6);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_75, ",", 1);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_79, "size: $i,$i", 11);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_91, "/", 1);
STRING_LITERAL(TM_THCNEHkyG9b0BQ4nXMJumiQ_92, ":", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, atEnd_NVY9c8Pn0NAkURXlVXSRJqA)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw stream) {
	NIM_BOOL result;
	nimfr_("atEnd", "spriteatlasloader.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "spriteatlasloader.nim");
	result = ((stream.data ? stream.data->Sup.len : 0) <= stream.pos);
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_CHAR, readChar_TsojS3Vt9cSwkBauw4qpvLA)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* stream) {
	NIM_CHAR result;
	nimfr_("readChar", "spriteatlasloader.nim");
	result = (NIM_CHAR)0;
	nimln_(21, "spriteatlasloader.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = atEnd_NVY9c8Pn0NAkURXlVXSRJqA((*stream));
		if (!T3_) goto LA4_;
		nimln_(22, "spriteatlasloader.nim");
		result = 0;
	}
	goto LA1_;
	LA4_: ;
	{
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_2;
		nimln_(24, "spriteatlasloader.nim");
		if ((NU)((*stream).pos) > (NU)((*stream).data->Sup.len)) raiseIndexError();
		result = (*stream).data->data[(*stream).pos];
		nimln_(25, "spriteatlasloader.nim");
		TM_THCNEHkyG9b0BQ4nXMJumiQ_2 = addInt((*stream).pos, ((NI) 1));
		(*stream).pos = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_2);
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, readLine_9aOHgpnIHcRo6QFN509cEkJQ)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* s, NimStringDesc** line) {
	NIM_BOOL result;
	nimfr_("readLine", "spriteatlasloader.nim");
{	result = (NIM_BOOL)0;
	nimln_(28, "spriteatlasloader.nim");
	(*line) = setLengthStr((*line), ((NI) 0));
	{
		nimln_(29, "spriteatlasloader.nim");
		while (1) {
			NIM_CHAR c;
			nimln_(30, "spriteatlasloader.nim");
			c = readChar_TsojS3Vt9cSwkBauw4qpvLA(s);
			nimln_(31, "spriteatlasloader.nim");
			{
				if (!((NU8)(c) == (NU8)(13))) goto LA5_;
				nimln_(32, "spriteatlasloader.nim");
				c = readChar_TsojS3Vt9cSwkBauw4qpvLA(s);
				nimln_(33, "spriteatlasloader.nim");
				goto LA1;
			}
			goto LA3_;
			LA5_: ;
			{
				nimln_(34, "spriteatlasloader.nim");
				if (!((NU8)(c) == (NU8)(10))) goto LA8_;
				goto LA1;
			}
			goto LA3_;
			LA8_: ;
			{
				nimln_(35, "spriteatlasloader.nim");
				if (!((NU8)(c) == (NU8)(0))) goto LA11_;
				nimln_(36, "spriteatlasloader.nim");
				{
					if (!(((NI) 0) < ((*line) ? (*line)->Sup.len : 0))) goto LA15_;
					goto LA1;
				}
				goto LA13_;
				LA15_: ;
				{
					nimln_(37, "spriteatlasloader.nim");
					result = NIM_FALSE;
					goto BeforeRet_;
				}
				LA13_: ;
			}
			goto LA3_;
			LA11_: ;
			LA3_: ;
			nimln_(38, "spriteatlasloader.nim");
			(*line) = addChar((*line), c);
		}
	} LA1: ;
	nimln_(39, "spriteatlasloader.nim");
	result = NIM_TRUE;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, peekLine_9aOHgpnIHcRo6QFN509cEkJQ_2)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* s, NimStringDesc** line) {
	NIM_BOOL result;
	NI oldPos;
	nimfr_("peekLine", "spriteatlasloader.nim");
	result = (NIM_BOOL)0;
	nimln_(42, "spriteatlasloader.nim");
	oldPos = (*s).pos;
	nimln_(43, "spriteatlasloader.nim");
	result = readLine_9aOHgpnIHcRo6QFN509cEkJQ(s, line);
	nimln_(44, "spriteatlasloader.nim");
	(*s).pos = oldPos;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initCtsStream_cZEwPPJU9c9aBg5RB9bg9bmPAw)(NimStringDesc* data, tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* Result) {
	nimfr_("initCtsStream", "spriteatlasloader.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_FObehHmSKwAl6Yz9bwTsjiw_));
	nimln_(47, "spriteatlasloader.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_FObehHmSKwAl6Yz9bwTsjiw_));
	(*Result).pos = ((NI) 0);
	unsureAsgnRef((void**) (&(*Result).data), copyString(data));
	popFrame();
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, insertReg_cCItPLlEVf9boS51TDye5Yg)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* root, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* reg, NI index, NimStringDesc** path, NI pathLen_0, NI start) {
	nimfr_("insertReg", "spriteatlasloader.nim");
	nimln_(85, "spriteatlasloader.nim");
	{
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_4;
		tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ T5_;
		tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ* T6_;
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_6;
		TM_THCNEHkyG9b0BQ4nXMJumiQ_4 = subInt(pathLen_0, ((NI) 1));
		if (!(start < (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_4))) goto LA3_;
		nimln_(89, "spriteatlasloader.nim");
		nimln_(86, "spriteatlasloader.nim");
		if ((NU)(start) >= (NU)(pathLen_0)) raiseIndexError();
		memset((void*)(&T5_), 0, sizeof(T5_));
		memset((void*)(&T5_), 0, sizeof(T5_));
		T5_.leaf = NIM_FALSE;
		nimln_(318, "tables.nim");
		initTable_VpFKAGy3QS4KetRNn6XNlQ(((NI) 64), (&T5_.leafU.S2.dir));
		T6_ = (tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ*)0;
		T6_ = mgetOrPut_72R8U6ss4ZI9cxlHSH5N1hw(root, path[start], T5_);
		if (!(((1 &(1U<<((NU)((*T6_).leaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_5));
		nimln_(89, "spriteatlasloader.nim");
		TM_THCNEHkyG9b0BQ4nXMJumiQ_6 = addInt(start, ((NI) 1));
		insertReg_cCItPLlEVf9boS51TDye5Yg((&(*T6_).leafU.S2.dir), reg, index, path, pathLen_0, (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_6));
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ T8_;
		tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ* T9_;
		nimln_(94, "spriteatlasloader.nim");
		nimln_(91, "spriteatlasloader.nim");
		if ((NU)(start) >= (NU)(pathLen_0)) raiseIndexError();
		memset((void*)(&T8_), 0, sizeof(T8_));
		memset((void*)(&T8_), 0, sizeof(T8_));
		T8_.leaf = NIM_TRUE;
		nimln_(318, "tables.nim");
		initTable_9bEe79bLaUXK1rbPlj69c5wOQ(((NI) 64), (&T8_.leafU.S1.regs));
		T9_ = (tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ*)0;
		T9_ = mgetOrPut_72R8U6ss4ZI9cxlHSH5N1hw(root, path[start], T8_);
		if (!(((2 &(1U<<((NU)((*T9_).leaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_7));
		add_xdjKC0QLjR9bZBTz9ct9a1XyQ((&(*T9_).leafU.S1.regs), index, reg);
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(NI, parseUntil_g9cfzCBmR6LwC5faTMHN5Ggspriteatlasloader)(NimStringDesc* s, NimStringDesc** token, NimStringDesc* until, NI start) {
	NI result;
	NI i;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_13;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_14;
	nimfr_("parseUntil", "parseutils.nim");
	result = (NI)0;
	nimln_(200, "parseutils.nim");
	i = start;
	{
		nimln_(201, "parseutils.nim");
		while (1) {
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_12;
			if (!(i < (s ? s->Sup.len : 0))) goto LA2;
			nimln_(202, "parseutils.nim");
			{
				NI u;
				if ((NU)(i) > (NU)(s->Sup.len)) raiseIndexError();
				if ((NU)(((NI) 0)) > (NU)(until->Sup.len)) raiseIndexError();
				if (!((NU8)(s->data[i]) == (NU8)(until->data[((NI) 0)]))) goto LA5_;
				nimln_(203, "parseutils.nim");
				u = ((NI) 1);
				{
					nimln_(204, "parseutils.nim");
					while (1) {
						NIM_BOOL T9_;
						NIM_BOOL T10_;
						NI TM_THCNEHkyG9b0BQ4nXMJumiQ_9;
						NI TM_THCNEHkyG9b0BQ4nXMJumiQ_10;
						NI TM_THCNEHkyG9b0BQ4nXMJumiQ_11;
						T9_ = (NIM_BOOL)0;
						T10_ = (NIM_BOOL)0;
						TM_THCNEHkyG9b0BQ4nXMJumiQ_9 = addInt(i, u);
						T10_ = ((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_9) < (s ? s->Sup.len : 0));
						if (!(T10_)) goto LA11_;
						T10_ = (u < (until ? until->Sup.len : 0));
						LA11_: ;
						T9_ = T10_;
						if (!(T9_)) goto LA12_;
						TM_THCNEHkyG9b0BQ4nXMJumiQ_10 = addInt(i, u);
						if ((NU)((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_10)) > (NU)(s->Sup.len)) raiseIndexError();
						if ((NU)(u) > (NU)(until->Sup.len)) raiseIndexError();
						T9_ = ((NU8)(s->data[(NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_10)]) == (NU8)(until->data[u]));
						LA12_: ;
						if (!T9_) goto LA8;
						nimln_(205, "parseutils.nim");
						TM_THCNEHkyG9b0BQ4nXMJumiQ_11 = addInt(u, ((NI) 1));
						u = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_11);
					} LA8: ;
				}
				nimln_(206, "parseutils.nim");
				{
					if (!((until ? until->Sup.len : 0) <= u)) goto LA15_;
					goto LA1;
				}
				LA15_: ;
			}
			LA5_: ;
			nimln_(207, "parseutils.nim");
			TM_THCNEHkyG9b0BQ4nXMJumiQ_12 = addInt(i, ((NI) 1));
			i = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_12);
		} LA2: ;
	} LA1: ;
	nimln_(208, "parseutils.nim");
	TM_THCNEHkyG9b0BQ4nXMJumiQ_13 = subInt(i, start);
	result = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_13);
	nimln_(209, "parseutils.nim");
	TM_THCNEHkyG9b0BQ4nXMJumiQ_14 = subInt(i, ((NI) 1));
	unsureAsgnRef((void**) (&(*token)), copyStrLast(s, start, (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_14)));
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(NI, skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader)(NimStringDesc* s, NimStringDesc* token, NI start) {
	NI result;
	nimfr_("skip", "parseutils.nim");
	result = (NI)0;
	{
		nimln_(149, "parseutils.nim");
		while (1) {
			NIM_BOOL T3_;
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_20;
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_21;
			T3_ = (NIM_BOOL)0;
			T3_ = (result < (token ? token->Sup.len : 0));
			if (!(T3_)) goto LA4_;
			TM_THCNEHkyG9b0BQ4nXMJumiQ_20 = addInt(result, start);
			if ((NU)((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_20)) > (NU)(s->Sup.len)) raiseIndexError();
			if ((NU)(result) > (NU)(token->Sup.len)) raiseIndexError();
			T3_ = ((NU8)(s->data[(NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_20)]) == (NU8)(token->data[result]));
			LA4_: ;
			if (!T3_) goto LA2;
			TM_THCNEHkyG9b0BQ4nXMJumiQ_21 = addInt(result, ((NI) 1));
			result = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_21);
		} LA2: ;
	}
	nimln_(150, "parseutils.nim");
	{
		nimln_(398, "system.nim");
		nimln_(150, "parseutils.nim");
		if (!!((result == (token ? token->Sup.len : 0)))) goto LA7_;
		result = ((NI) 0);
	}
	LA7_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, parseRegBlock_GQRA5uv7ZveovWyM6jSlmQ)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* stream, NI* lineCount, tyObject_RegDesc_S7CGpRr9aRGBYfCm5btR88w* reg) {
	NimStringDesc* tmp;
	NimStringDesc* line;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_19;
	NimStringDesc* line_2;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_27;
	NimStringDesc* line_3;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_36;
	NimStringDesc* line_4;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_44;
	NimStringDesc* line_5;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_52;
	NimStringDesc* line_6;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_60;
	NimStringDesc* line_7;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_66;
	nimfr_("parseRegBlock", "spriteatlasloader.nim");
	tmp = (NimStringDesc*)0;
	nimln_(99, "spriteatlasloader.nim");
	unsureAsgnRef((void**) (&(*reg).name), copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8)));
	nimln_(53, "spriteatlasloader.nim");
	line = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
	nimln_(55, "spriteatlasloader.nim");
	{
		NIM_BOOL T3_;
		NimStringDesc* inp;
		NI idx;
		NIM_BOOL res;
		NI resLen;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
		NimStringDesc* T11_;
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_17;
		NimStringDesc* T12_;
		T3_ = (NIM_BOOL)0;
		T3_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line));
		if (!(T3_)) goto LA4_;
		inp = line;
		idx = ((NI) 0);
		res = NIM_FALSE;
		resLen = parseUntil_g9cfzCBmR6LwC5faTMHN5Ggspriteatlasloader(inp, (&(*reg).name), ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8), idx);
		{
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_15;
			nimln_(398, "system.nim");
			nimln_(388, "strscans.nim");
			if (!!((resLen == ((NI) 0)))) goto LA7_;
			nimln_(320, "strscans.nim");
			TM_THCNEHkyG9b0BQ4nXMJumiQ_15 = addInt(idx, resLen);
			idx = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_15);
			nimln_(539, "macros.nim");
			res = NIM_TRUE;
		}
		LA7_: ;
		T3_ = res;
		LA4_: ;
		if (!!(T3_)) goto LA9_;
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(100, "spriteatlasloader.nim");
		e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T11_ = (NimStringDesc*)0;
		TM_THCNEHkyG9b0BQ4nXMJumiQ_17 = addInt((*lineCount), ((NI) 1));
		T12_ = (NimStringDesc*)0;
		T12_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_17));
		T11_ = rawNewString(T12_->Sup.len + line->Sup.len + 24);
appendString(T11_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T11_, T12_);
appendString(T11_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_18));
appendString(T11_, line);
		asgnRefNoCycle((void**) (&(*e).Sup.message), T11_);
		asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
		raiseException((Exception*)e, "ValueError");
	}
	LA9_: ;
	TM_THCNEHkyG9b0BQ4nXMJumiQ_19 = addInt((*lineCount), ((NI) 1));
	(*lineCount) = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_19);
	nimln_(53, "spriteatlasloader.nim");
	line_2 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
	nimln_(55, "spriteatlasloader.nim");
	{
		NIM_BOOL T15_;
		NimStringDesc* inp_2;
		NI idx_2;
		NIM_BOOL res_2;
		NI resLen_2;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_2;
		NimStringDesc* T27_;
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_25;
		NimStringDesc* T28_;
		T15_ = (NIM_BOOL)0;
		T15_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_2));
		if (!(T15_)) goto LA16_;
		inp_2 = line_2;
		idx_2 = ((NI) 0);
		res_2 = NIM_FALSE;
		resLen_2 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_2, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_22), idx_2);
		{
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_23;
			NI resLen_3;
			nimln_(398, "system.nim");
			nimln_(441, "strscans.nim");
			if (!!((resLen_2 == ((NI) 0)))) goto LA19_;
			nimln_(320, "strscans.nim");
			TM_THCNEHkyG9b0BQ4nXMJumiQ_23 = addInt(idx_2, resLen_2);
			idx_2 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_23);
			nimln_(55, "spriteatlasloader.nim");
			resLen_3 = parseIdent_tLWlhTCVyzkdnYs1ielKLg(inp_2, (&tmp), idx_2);
			{
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_24;
				nimln_(398, "system.nim");
				nimln_(313, "strscans.nim");
				if (!!((resLen_3 == ((NI) 0)))) goto LA23_;
				nimln_(320, "strscans.nim");
				TM_THCNEHkyG9b0BQ4nXMJumiQ_24 = addInt(idx_2, resLen_3);
				idx_2 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_24);
				nimln_(539, "macros.nim");
				res_2 = NIM_TRUE;
			}
			LA23_: ;
		}
		LA19_: ;
		T15_ = res_2;
		LA16_: ;
		if (!!(T15_)) goto LA25_;
		e_2 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(101, "spriteatlasloader.nim");
		e_2 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e_2).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T27_ = (NimStringDesc*)0;
		TM_THCNEHkyG9b0BQ4nXMJumiQ_25 = addInt((*lineCount), ((NI) 1));
		T28_ = (NimStringDesc*)0;
		T28_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_25));
		T27_ = rawNewString(T28_->Sup.len + line_2->Sup.len + 34);
appendString(T27_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T27_, T28_);
appendString(T27_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_26));
appendString(T27_, line_2);
		asgnRefNoCycle((void**) (&(*e_2).Sup.message), T27_);
		asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
		raiseException((Exception*)e_2, "ValueError");
	}
	LA25_: ;
	TM_THCNEHkyG9b0BQ4nXMJumiQ_27 = addInt((*lineCount), ((NI) 1));
	(*lineCount) = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_27);
	nimln_(53, "spriteatlasloader.nim");
	line_3 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
	nimln_(55, "spriteatlasloader.nim");
	{
		NIM_BOOL T31_;
		NimStringDesc* inp_3;
		NI idx_3;
		NIM_BOOL res_3;
		NI resLen_4;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_3;
		NimStringDesc* T51_;
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_34;
		NimStringDesc* T52_;
		T31_ = (NIM_BOOL)0;
		T31_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_3));
		if (!(T31_)) goto LA32_;
		inp_3 = line_3;
		idx_3 = ((NI) 0);
		res_3 = NIM_FALSE;
		resLen_4 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_3, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_28), idx_3);
		{
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_29;
			NI resLen_5;
			nimln_(398, "system.nim");
			nimln_(441, "strscans.nim");
			if (!!((resLen_4 == ((NI) 0)))) goto LA35_;
			nimln_(320, "strscans.nim");
			TM_THCNEHkyG9b0BQ4nXMJumiQ_29 = addInt(idx_3, resLen_4);
			idx_3 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_29);
			nimln_(55, "spriteatlasloader.nim");
			resLen_5 = npuParseInt(inp_3, (&(*reg).x), idx_3);
			{
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_30;
				NI resLen_6;
				nimln_(398, "system.nim");
				nimln_(313, "strscans.nim");
				if (!!((resLen_5 == ((NI) 0)))) goto LA39_;
				nimln_(320, "strscans.nim");
				TM_THCNEHkyG9b0BQ4nXMJumiQ_30 = addInt(idx_3, resLen_5);
				idx_3 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_30);
				nimln_(55, "spriteatlasloader.nim");
				resLen_6 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_3, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_31), idx_3);
				{
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_32;
					NI resLen_7;
					nimln_(398, "system.nim");
					nimln_(441, "strscans.nim");
					if (!!((resLen_6 == ((NI) 0)))) goto LA43_;
					nimln_(320, "strscans.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_32 = addInt(idx_3, resLen_6);
					idx_3 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_32);
					nimln_(55, "spriteatlasloader.nim");
					resLen_7 = npuParseInt(inp_3, (&(*reg).y), idx_3);
					{
						NI TM_THCNEHkyG9b0BQ4nXMJumiQ_33;
						nimln_(398, "system.nim");
						nimln_(313, "strscans.nim");
						if (!!((resLen_7 == ((NI) 0)))) goto LA47_;
						nimln_(320, "strscans.nim");
						TM_THCNEHkyG9b0BQ4nXMJumiQ_33 = addInt(idx_3, resLen_7);
						idx_3 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_33);
						nimln_(539, "macros.nim");
						res_3 = NIM_TRUE;
					}
					LA47_: ;
				}
				LA43_: ;
			}
			LA39_: ;
		}
		LA35_: ;
		T31_ = res_3;
		LA32_: ;
		if (!!(T31_)) goto LA49_;
		e_3 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(102, "spriteatlasloader.nim");
		e_3 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e_3).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T51_ = (NimStringDesc*)0;
		TM_THCNEHkyG9b0BQ4nXMJumiQ_34 = addInt((*lineCount), ((NI) 1));
		T52_ = (NimStringDesc*)0;
		T52_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_34));
		T51_ = rawNewString(T52_->Sup.len + line_3->Sup.len + 34);
appendString(T51_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T51_, T52_);
appendString(T51_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_35));
appendString(T51_, line_3);
		asgnRefNoCycle((void**) (&(*e_3).Sup.message), T51_);
		asgnRef((void**) (&(*e_3).Sup.parent), NIM_NIL);
		raiseException((Exception*)e_3, "ValueError");
	}
	LA49_: ;
	TM_THCNEHkyG9b0BQ4nXMJumiQ_36 = addInt((*lineCount), ((NI) 1));
	(*lineCount) = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_36);
	nimln_(53, "spriteatlasloader.nim");
	line_4 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
	nimln_(55, "spriteatlasloader.nim");
	{
		NIM_BOOL T55_;
		NimStringDesc* inp_4;
		NI idx_4;
		NIM_BOOL res_4;
		NI resLen_8;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_4;
		NimStringDesc* T75_;
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_42;
		NimStringDesc* T76_;
		T55_ = (NIM_BOOL)0;
		T55_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_4));
		if (!(T55_)) goto LA56_;
		inp_4 = line_4;
		idx_4 = ((NI) 0);
		res_4 = NIM_FALSE;
		resLen_8 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_4, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_37), idx_4);
		{
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_38;
			NI resLen_9;
			nimln_(398, "system.nim");
			nimln_(441, "strscans.nim");
			if (!!((resLen_8 == ((NI) 0)))) goto LA59_;
			nimln_(320, "strscans.nim");
			TM_THCNEHkyG9b0BQ4nXMJumiQ_38 = addInt(idx_4, resLen_8);
			idx_4 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_38);
			nimln_(55, "spriteatlasloader.nim");
			resLen_9 = npuParseInt(inp_4, (&(*reg).width), idx_4);
			{
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_39;
				NI resLen_10;
				nimln_(398, "system.nim");
				nimln_(313, "strscans.nim");
				if (!!((resLen_9 == ((NI) 0)))) goto LA63_;
				nimln_(320, "strscans.nim");
				TM_THCNEHkyG9b0BQ4nXMJumiQ_39 = addInt(idx_4, resLen_9);
				idx_4 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_39);
				nimln_(55, "spriteatlasloader.nim");
				resLen_10 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_4, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_31), idx_4);
				{
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_40;
					NI resLen_11;
					nimln_(398, "system.nim");
					nimln_(441, "strscans.nim");
					if (!!((resLen_10 == ((NI) 0)))) goto LA67_;
					nimln_(320, "strscans.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_40 = addInt(idx_4, resLen_10);
					idx_4 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_40);
					nimln_(55, "spriteatlasloader.nim");
					resLen_11 = npuParseInt(inp_4, (&(*reg).height), idx_4);
					{
						NI TM_THCNEHkyG9b0BQ4nXMJumiQ_41;
						nimln_(398, "system.nim");
						nimln_(313, "strscans.nim");
						if (!!((resLen_11 == ((NI) 0)))) goto LA71_;
						nimln_(320, "strscans.nim");
						TM_THCNEHkyG9b0BQ4nXMJumiQ_41 = addInt(idx_4, resLen_11);
						idx_4 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_41);
						nimln_(539, "macros.nim");
						res_4 = NIM_TRUE;
					}
					LA71_: ;
				}
				LA67_: ;
			}
			LA63_: ;
		}
		LA59_: ;
		T55_ = res_4;
		LA56_: ;
		if (!!(T55_)) goto LA73_;
		e_4 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(103, "spriteatlasloader.nim");
		e_4 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e_4).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T75_ = (NimStringDesc*)0;
		TM_THCNEHkyG9b0BQ4nXMJumiQ_42 = addInt((*lineCount), ((NI) 1));
		T76_ = (NimStringDesc*)0;
		T76_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_42));
		T75_ = rawNewString(T76_->Sup.len + line_4->Sup.len + 36);
appendString(T75_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T75_, T76_);
appendString(T75_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_43));
appendString(T75_, line_4);
		asgnRefNoCycle((void**) (&(*e_4).Sup.message), T75_);
		asgnRef((void**) (&(*e_4).Sup.parent), NIM_NIL);
		raiseException((Exception*)e_4, "ValueError");
	}
	LA73_: ;
	TM_THCNEHkyG9b0BQ4nXMJumiQ_44 = addInt((*lineCount), ((NI) 1));
	(*lineCount) = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_44);
	nimln_(53, "spriteatlasloader.nim");
	line_5 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
	nimln_(55, "spriteatlasloader.nim");
	{
		NIM_BOOL T79_;
		NimStringDesc* inp_5;
		NI idx_5;
		NIM_BOOL res_5;
		NI resLen_12;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_5;
		NimStringDesc* T99_;
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_50;
		NimStringDesc* T100_;
		T79_ = (NIM_BOOL)0;
		T79_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_5));
		if (!(T79_)) goto LA80_;
		inp_5 = line_5;
		idx_5 = ((NI) 0);
		res_5 = NIM_FALSE;
		resLen_12 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_5, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_45), idx_5);
		{
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_46;
			NI resLen_13;
			nimln_(398, "system.nim");
			nimln_(441, "strscans.nim");
			if (!!((resLen_12 == ((NI) 0)))) goto LA83_;
			nimln_(320, "strscans.nim");
			TM_THCNEHkyG9b0BQ4nXMJumiQ_46 = addInt(idx_5, resLen_12);
			idx_5 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_46);
			nimln_(55, "spriteatlasloader.nim");
			resLen_13 = npuParseInt(inp_5, (&(*reg).logicalWidth), idx_5);
			{
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_47;
				NI resLen_14;
				nimln_(398, "system.nim");
				nimln_(313, "strscans.nim");
				if (!!((resLen_13 == ((NI) 0)))) goto LA87_;
				nimln_(320, "strscans.nim");
				TM_THCNEHkyG9b0BQ4nXMJumiQ_47 = addInt(idx_5, resLen_13);
				idx_5 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_47);
				nimln_(55, "spriteatlasloader.nim");
				resLen_14 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_5, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_31), idx_5);
				{
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_48;
					NI resLen_15;
					nimln_(398, "system.nim");
					nimln_(441, "strscans.nim");
					if (!!((resLen_14 == ((NI) 0)))) goto LA91_;
					nimln_(320, "strscans.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_48 = addInt(idx_5, resLen_14);
					idx_5 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_48);
					nimln_(55, "spriteatlasloader.nim");
					resLen_15 = npuParseInt(inp_5, (&(*reg).logicalHeight), idx_5);
					{
						NI TM_THCNEHkyG9b0BQ4nXMJumiQ_49;
						nimln_(398, "system.nim");
						nimln_(313, "strscans.nim");
						if (!!((resLen_15 == ((NI) 0)))) goto LA95_;
						nimln_(320, "strscans.nim");
						TM_THCNEHkyG9b0BQ4nXMJumiQ_49 = addInt(idx_5, resLen_15);
						idx_5 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_49);
						nimln_(539, "macros.nim");
						res_5 = NIM_TRUE;
					}
					LA95_: ;
				}
				LA91_: ;
			}
			LA87_: ;
		}
		LA83_: ;
		T79_ = res_5;
		LA80_: ;
		if (!!(T79_)) goto LA97_;
		e_5 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(104, "spriteatlasloader.nim");
		e_5 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e_5).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T99_ = (NimStringDesc*)0;
		TM_THCNEHkyG9b0BQ4nXMJumiQ_50 = addInt((*lineCount), ((NI) 1));
		T100_ = (NimStringDesc*)0;
		T100_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_50));
		T99_ = rawNewString(T100_->Sup.len + line_5->Sup.len + 36);
appendString(T99_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T99_, T100_);
appendString(T99_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_51));
appendString(T99_, line_5);
		asgnRefNoCycle((void**) (&(*e_5).Sup.message), T99_);
		asgnRef((void**) (&(*e_5).Sup.parent), NIM_NIL);
		raiseException((Exception*)e_5, "ValueError");
	}
	LA97_: ;
	TM_THCNEHkyG9b0BQ4nXMJumiQ_52 = addInt((*lineCount), ((NI) 1));
	(*lineCount) = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_52);
	nimln_(53, "spriteatlasloader.nim");
	line_6 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
	nimln_(55, "spriteatlasloader.nim");
	{
		NIM_BOOL T103_;
		NimStringDesc* inp_6;
		NI idx_6;
		NIM_BOOL res_6;
		NI resLen_16;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_6;
		NimStringDesc* T123_;
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_58;
		NimStringDesc* T124_;
		T103_ = (NIM_BOOL)0;
		T103_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_6));
		if (!(T103_)) goto LA104_;
		inp_6 = line_6;
		idx_6 = ((NI) 0);
		res_6 = NIM_FALSE;
		resLen_16 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_6, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_53), idx_6);
		{
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_54;
			NI resLen_17;
			nimln_(398, "system.nim");
			nimln_(441, "strscans.nim");
			if (!!((resLen_16 == ((NI) 0)))) goto LA107_;
			nimln_(320, "strscans.nim");
			TM_THCNEHkyG9b0BQ4nXMJumiQ_54 = addInt(idx_6, resLen_16);
			idx_6 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_54);
			nimln_(55, "spriteatlasloader.nim");
			resLen_17 = npuParseInt(inp_6, (&(*reg).xoffs), idx_6);
			{
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_55;
				NI resLen_18;
				nimln_(398, "system.nim");
				nimln_(313, "strscans.nim");
				if (!!((resLen_17 == ((NI) 0)))) goto LA111_;
				nimln_(320, "strscans.nim");
				TM_THCNEHkyG9b0BQ4nXMJumiQ_55 = addInt(idx_6, resLen_17);
				idx_6 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_55);
				nimln_(55, "spriteatlasloader.nim");
				resLen_18 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_6, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_31), idx_6);
				{
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_56;
					NI resLen_19;
					nimln_(398, "system.nim");
					nimln_(441, "strscans.nim");
					if (!!((resLen_18 == ((NI) 0)))) goto LA115_;
					nimln_(320, "strscans.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_56 = addInt(idx_6, resLen_18);
					idx_6 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_56);
					nimln_(55, "spriteatlasloader.nim");
					resLen_19 = npuParseInt(inp_6, (&(*reg).yoffs), idx_6);
					{
						NI TM_THCNEHkyG9b0BQ4nXMJumiQ_57;
						nimln_(398, "system.nim");
						nimln_(313, "strscans.nim");
						if (!!((resLen_19 == ((NI) 0)))) goto LA119_;
						nimln_(320, "strscans.nim");
						TM_THCNEHkyG9b0BQ4nXMJumiQ_57 = addInt(idx_6, resLen_19);
						idx_6 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_57);
						nimln_(539, "macros.nim");
						res_6 = NIM_TRUE;
					}
					LA119_: ;
				}
				LA115_: ;
			}
			LA111_: ;
		}
		LA107_: ;
		T103_ = res_6;
		LA104_: ;
		if (!!(T103_)) goto LA121_;
		e_6 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(105, "spriteatlasloader.nim");
		e_6 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e_6).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T123_ = (NimStringDesc*)0;
		TM_THCNEHkyG9b0BQ4nXMJumiQ_58 = addInt((*lineCount), ((NI) 1));
		T124_ = (NimStringDesc*)0;
		T124_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_58));
		T123_ = rawNewString(T124_->Sup.len + line_6->Sup.len + 38);
appendString(T123_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T123_, T124_);
appendString(T123_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_59));
appendString(T123_, line_6);
		asgnRefNoCycle((void**) (&(*e_6).Sup.message), T123_);
		asgnRef((void**) (&(*e_6).Sup.parent), NIM_NIL);
		raiseException((Exception*)e_6, "ValueError");
	}
	LA121_: ;
	TM_THCNEHkyG9b0BQ4nXMJumiQ_60 = addInt((*lineCount), ((NI) 1));
	(*lineCount) = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_60);
	nimln_(53, "spriteatlasloader.nim");
	line_7 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
	nimln_(55, "spriteatlasloader.nim");
	{
		NIM_BOOL T127_;
		NimStringDesc* inp_7;
		NI idx_7;
		NIM_BOOL res_7;
		NI resLen_20;
		tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_7;
		NimStringDesc* T139_;
		NI TM_THCNEHkyG9b0BQ4nXMJumiQ_64;
		NimStringDesc* T140_;
		T127_ = (NIM_BOOL)0;
		T127_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_7));
		if (!(T127_)) goto LA128_;
		inp_7 = line_7;
		idx_7 = ((NI) 0);
		res_7 = NIM_FALSE;
		resLen_20 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_7, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_61), idx_7);
		{
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_62;
			NI resLen_21;
			nimln_(398, "system.nim");
			nimln_(441, "strscans.nim");
			if (!!((resLen_20 == ((NI) 0)))) goto LA131_;
			nimln_(320, "strscans.nim");
			TM_THCNEHkyG9b0BQ4nXMJumiQ_62 = addInt(idx_7, resLen_20);
			idx_7 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_62);
			nimln_(55, "spriteatlasloader.nim");
			resLen_21 = npuParseInt(inp_7, (&(*reg).index), idx_7);
			{
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_63;
				nimln_(398, "system.nim");
				nimln_(313, "strscans.nim");
				if (!!((resLen_21 == ((NI) 0)))) goto LA135_;
				nimln_(320, "strscans.nim");
				TM_THCNEHkyG9b0BQ4nXMJumiQ_63 = addInt(idx_7, resLen_21);
				idx_7 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_63);
				nimln_(539, "macros.nim");
				res_7 = NIM_TRUE;
			}
			LA135_: ;
		}
		LA131_: ;
		T127_ = res_7;
		LA128_: ;
		if (!!(T127_)) goto LA137_;
		e_7 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
		nimln_(106, "spriteatlasloader.nim");
		e_7 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
		(*e_7).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
		T139_ = (NimStringDesc*)0;
		TM_THCNEHkyG9b0BQ4nXMJumiQ_64 = addInt((*lineCount), ((NI) 1));
		T140_ = (NimStringDesc*)0;
		T140_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_64));
		T139_ = rawNewString(T140_->Sup.len + line_7->Sup.len + 33);
appendString(T139_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T139_, T140_);
appendString(T139_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_65));
appendString(T139_, line_7);
		asgnRefNoCycle((void**) (&(*e_7).Sup.message), T139_);
		asgnRef((void**) (&(*e_7).Sup.parent), NIM_NIL);
		raiseException((Exception*)e_7, "ValueError");
	}
	LA137_: ;
	TM_THCNEHkyG9b0BQ4nXMJumiQ_66 = addInt((*lineCount), ((NI) 1));
	(*lineCount) = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_66);
	popFrame();
}
static N_NIMCALL(void, Marker_tySequence_WzvE7PdLW9bdyTHkZUG6C0Q)(void* p, NI op) {
	tySequence_WzvE7PdLW9bdyTHkZUG6C0Q* a;
	NI T1_;
	a = (tySequence_WzvE7PdLW9bdyTHkZUG6C0Q*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].path, op);
	}
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3498, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, parseAtlas_jZe5Up9b04IWS0NiqOlmF9cw)(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw* stream, tyObject_SpriteAtlas_Dr8eFJ8wQTh9bq2RTD6JXyg* atlas) {
	NimStringDesc* line;
	NI lineCount;
	nimfr_("parseAtlas", "spriteatlasloader.nim");
	nimln_(109, "spriteatlasloader.nim");
	line = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
	nimln_(110, "spriteatlasloader.nim");
	lineCount = ((NI) 0);
	nimln_(111, "spriteatlasloader.nim");
	unsureAsgnRef((void**) (&(*atlas).pages), (tySequence_WzvE7PdLW9bdyTHkZUG6C0Q*) newSeq((&NTI_WzvE7PdLW9bdyTHkZUG6C0Q_), 0));
	nimln_(318, "tables.nim");
	initTable_VpFKAGy3QS4KetRNn6XNlQ(((NI) 64), (&(*atlas).dir));
	{
		nimln_(114, "spriteatlasloader.nim");
		while (1) {
			NIM_BOOL T3_;
			tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g page;
			NimStringDesc* line_2;
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_68;
			NimStringDesc* line_3;
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_71;
			NimStringDesc* line_4;
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_80;
			NimStringDesc* line_5;
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_82;
			NimStringDesc* line_6;
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_84;
			NimStringDesc* line_7;
			NI TM_THCNEHkyG9b0BQ4nXMJumiQ_86;
			NI T81_;
			NimStringDesc* T82_;
			T3_ = (NIM_BOOL)0;
			T3_ = atEnd_NVY9c8Pn0NAkURXlVXSRJqA((*stream));
			if (!!(T3_)) goto LA2;
			memset((void*)(&page), 0, sizeof(page));
			nimln_(116, "spriteatlasloader.nim");
			chckNil((void*)(&page));
			memset((void*)(&page), 0, sizeof(page));
			nimln_(117, "spriteatlasloader.nim");
			page.path = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
			nimln_(53, "spriteatlasloader.nim");
			line_2 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
			nimln_(55, "spriteatlasloader.nim");
			{
				NIM_BOOL T6_;
				NimStringDesc* inp;
				NI idx;
				NIM_BOOL res;
				tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e;
				NimStringDesc* T10_;
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_67;
				NimStringDesc* T11_;
				T6_ = (NIM_BOOL)0;
				T6_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_2));
				if (!(T6_)) goto LA7_;
				inp = line_2;
				idx = ((NI) 0);
				res = NIM_FALSE;
				nimln_(539, "macros.nim");
				res = NIM_TRUE;
				T6_ = res;
				LA7_: ;
				if (!!(T6_)) goto LA8_;
				e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
				nimln_(119, "spriteatlasloader.nim");
				e = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
				(*e).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
				T10_ = (NimStringDesc*)0;
				TM_THCNEHkyG9b0BQ4nXMJumiQ_67 = addInt(lineCount, ((NI) 1));
				T11_ = (NimStringDesc*)0;
				T11_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_67));
				T10_ = rawNewString(T11_->Sup.len + line_2->Sup.len + 22);
appendString(T10_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T10_, T11_);
appendString(T10_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
appendString(T10_, line_2);
				asgnRefNoCycle((void**) (&(*e).Sup.message), T10_);
				asgnRef((void**) (&(*e).Sup.parent), NIM_NIL);
				raiseException((Exception*)e, "ValueError");
			}
			LA8_: ;
			TM_THCNEHkyG9b0BQ4nXMJumiQ_68 = addInt(lineCount, ((NI) 1));
			lineCount = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_68);
			nimln_(53, "spriteatlasloader.nim");
			line_3 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
			nimln_(55, "spriteatlasloader.nim");
			{
				NIM_BOOL T14_;
				NimStringDesc* inp_2;
				NI idx_2;
				NIM_BOOL res_2;
				NI resLen;
				tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_2;
				NimStringDesc* T22_;
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_70;
				NimStringDesc* T23_;
				T14_ = (NIM_BOOL)0;
				T14_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_3));
				if (!(T14_)) goto LA15_;
				inp_2 = line_3;
				idx_2 = ((NI) 0);
				res_2 = NIM_FALSE;
				resLen = parseUntil_g9cfzCBmR6LwC5faTMHN5Ggspriteatlasloader(inp_2, (&page.path), ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8), idx_2);
				{
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_69;
					nimln_(398, "system.nim");
					nimln_(388, "strscans.nim");
					if (!!((resLen == ((NI) 0)))) goto LA18_;
					nimln_(320, "strscans.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_69 = addInt(idx_2, resLen);
					idx_2 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_69);
					nimln_(539, "macros.nim");
					res_2 = NIM_TRUE;
				}
				LA18_: ;
				T14_ = res_2;
				LA15_: ;
				if (!!(T14_)) goto LA20_;
				e_2 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
				nimln_(120, "spriteatlasloader.nim");
				e_2 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
				(*e_2).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
				T22_ = (NimStringDesc*)0;
				TM_THCNEHkyG9b0BQ4nXMJumiQ_70 = addInt(lineCount, ((NI) 1));
				T23_ = (NimStringDesc*)0;
				T23_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_70));
				T22_ = rawNewString(T23_->Sup.len + line_3->Sup.len + 24);
appendString(T22_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T22_, T23_);
appendString(T22_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_18));
appendString(T22_, line_3);
				asgnRefNoCycle((void**) (&(*e_2).Sup.message), T22_);
				asgnRef((void**) (&(*e_2).Sup.parent), NIM_NIL);
				raiseException((Exception*)e_2, "ValueError");
			}
			LA20_: ;
			TM_THCNEHkyG9b0BQ4nXMJumiQ_71 = addInt(lineCount, ((NI) 1));
			lineCount = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_71);
			nimln_(53, "spriteatlasloader.nim");
			line_4 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
			nimln_(55, "spriteatlasloader.nim");
			{
				NIM_BOOL T26_;
				NimStringDesc* inp_3;
				NI idx_3;
				NIM_BOOL res_3;
				NI resLen_2;
				tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_3;
				NimStringDesc* T46_;
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_78;
				NimStringDesc* T47_;
				T26_ = (NIM_BOOL)0;
				T26_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_4));
				if (!(T26_)) goto LA27_;
				inp_3 = line_4;
				idx_3 = ((NI) 0);
				res_3 = NIM_FALSE;
				resLen_2 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_3, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_72), idx_3);
				{
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_73;
					NI resLen_3;
					nimln_(398, "system.nim");
					nimln_(441, "strscans.nim");
					if (!!((resLen_2 == ((NI) 0)))) goto LA30_;
					nimln_(320, "strscans.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_73 = addInt(idx_3, resLen_2);
					idx_3 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_73);
					nimln_(55, "spriteatlasloader.nim");
					resLen_3 = npuParseInt(inp_3, (&page.width), idx_3);
					{
						NI TM_THCNEHkyG9b0BQ4nXMJumiQ_74;
						NI resLen_4;
						nimln_(398, "system.nim");
						nimln_(313, "strscans.nim");
						if (!!((resLen_3 == ((NI) 0)))) goto LA34_;
						nimln_(320, "strscans.nim");
						TM_THCNEHkyG9b0BQ4nXMJumiQ_74 = addInt(idx_3, resLen_3);
						idx_3 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_74);
						nimln_(55, "spriteatlasloader.nim");
						resLen_4 = skip_fc5TW1DhtYsNnpWwsjrW5Aspriteatlasloader(inp_3, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_75), idx_3);
						{
							NI TM_THCNEHkyG9b0BQ4nXMJumiQ_76;
							NI resLen_5;
							nimln_(398, "system.nim");
							nimln_(441, "strscans.nim");
							if (!!((resLen_4 == ((NI) 0)))) goto LA38_;
							nimln_(320, "strscans.nim");
							TM_THCNEHkyG9b0BQ4nXMJumiQ_76 = addInt(idx_3, resLen_4);
							idx_3 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_76);
							nimln_(55, "spriteatlasloader.nim");
							resLen_5 = npuParseInt(inp_3, (&page.height), idx_3);
							{
								NI TM_THCNEHkyG9b0BQ4nXMJumiQ_77;
								nimln_(398, "system.nim");
								nimln_(313, "strscans.nim");
								if (!!((resLen_5 == ((NI) 0)))) goto LA42_;
								nimln_(320, "strscans.nim");
								TM_THCNEHkyG9b0BQ4nXMJumiQ_77 = addInt(idx_3, resLen_5);
								idx_3 = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_77);
								nimln_(539, "macros.nim");
								res_3 = NIM_TRUE;
							}
							LA42_: ;
						}
						LA38_: ;
					}
					LA34_: ;
				}
				LA30_: ;
				T26_ = res_3;
				LA27_: ;
				if (!!(T26_)) goto LA44_;
				e_3 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
				nimln_(121, "spriteatlasloader.nim");
				e_3 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
				(*e_3).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
				T46_ = (NimStringDesc*)0;
				TM_THCNEHkyG9b0BQ4nXMJumiQ_78 = addInt(lineCount, ((NI) 1));
				T47_ = (NimStringDesc*)0;
				T47_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_78));
				T46_ = rawNewString(T47_->Sup.len + line_4->Sup.len + 33);
appendString(T46_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T46_, T47_);
appendString(T46_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_79));
appendString(T46_, line_4);
				asgnRefNoCycle((void**) (&(*e_3).Sup.message), T46_);
				asgnRef((void**) (&(*e_3).Sup.parent), NIM_NIL);
				raiseException((Exception*)e_3, "ValueError");
			}
			LA44_: ;
			TM_THCNEHkyG9b0BQ4nXMJumiQ_80 = addInt(lineCount, ((NI) 1));
			lineCount = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_80);
			nimln_(53, "spriteatlasloader.nim");
			line_5 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
			nimln_(55, "spriteatlasloader.nim");
			{
				NIM_BOOL T50_;
				NimStringDesc* inp_4;
				NI idx_4;
				NIM_BOOL res_4;
				tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_4;
				NimStringDesc* T54_;
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_81;
				NimStringDesc* T55_;
				T50_ = (NIM_BOOL)0;
				T50_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_5));
				if (!(T50_)) goto LA51_;
				inp_4 = line_5;
				idx_4 = ((NI) 0);
				res_4 = NIM_FALSE;
				nimln_(539, "macros.nim");
				res_4 = NIM_TRUE;
				T50_ = res_4;
				LA51_: ;
				if (!!(T50_)) goto LA52_;
				e_4 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
				nimln_(122, "spriteatlasloader.nim");
				e_4 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
				(*e_4).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
				T54_ = (NimStringDesc*)0;
				TM_THCNEHkyG9b0BQ4nXMJumiQ_81 = addInt(lineCount, ((NI) 1));
				T55_ = (NimStringDesc*)0;
				T55_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_81));
				T54_ = rawNewString(T55_->Sup.len + line_5->Sup.len + 22);
appendString(T54_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T54_, T55_);
appendString(T54_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
appendString(T54_, line_5);
				asgnRefNoCycle((void**) (&(*e_4).Sup.message), T54_);
				asgnRef((void**) (&(*e_4).Sup.parent), NIM_NIL);
				raiseException((Exception*)e_4, "ValueError");
			}
			LA52_: ;
			TM_THCNEHkyG9b0BQ4nXMJumiQ_82 = addInt(lineCount, ((NI) 1));
			lineCount = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_82);
			nimln_(53, "spriteatlasloader.nim");
			line_6 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
			nimln_(55, "spriteatlasloader.nim");
			{
				NIM_BOOL T58_;
				NimStringDesc* inp_5;
				NI idx_5;
				NIM_BOOL res_5;
				tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_5;
				NimStringDesc* T62_;
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_83;
				NimStringDesc* T63_;
				T58_ = (NIM_BOOL)0;
				T58_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_6));
				if (!(T58_)) goto LA59_;
				inp_5 = line_6;
				idx_5 = ((NI) 0);
				res_5 = NIM_FALSE;
				nimln_(539, "macros.nim");
				res_5 = NIM_TRUE;
				T58_ = res_5;
				LA59_: ;
				if (!!(T58_)) goto LA60_;
				e_5 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
				nimln_(123, "spriteatlasloader.nim");
				e_5 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
				(*e_5).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
				T62_ = (NimStringDesc*)0;
				TM_THCNEHkyG9b0BQ4nXMJumiQ_83 = addInt(lineCount, ((NI) 1));
				T63_ = (NimStringDesc*)0;
				T63_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_83));
				T62_ = rawNewString(T63_->Sup.len + line_6->Sup.len + 22);
appendString(T62_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T62_, T63_);
appendString(T62_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
appendString(T62_, line_6);
				asgnRefNoCycle((void**) (&(*e_5).Sup.message), T62_);
				asgnRef((void**) (&(*e_5).Sup.parent), NIM_NIL);
				raiseException((Exception*)e_5, "ValueError");
			}
			LA60_: ;
			TM_THCNEHkyG9b0BQ4nXMJumiQ_84 = addInt(lineCount, ((NI) 1));
			lineCount = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_84);
			nimln_(53, "spriteatlasloader.nim");
			line_7 = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
			nimln_(55, "spriteatlasloader.nim");
			{
				NIM_BOOL T66_;
				NimStringDesc* inp_6;
				NI idx_6;
				NIM_BOOL res_6;
				tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA* e_6;
				NimStringDesc* T70_;
				NI TM_THCNEHkyG9b0BQ4nXMJumiQ_85;
				NimStringDesc* T71_;
				T66_ = (NIM_BOOL)0;
				T66_ = readLine_9aOHgpnIHcRo6QFN509cEkJQ(stream, (&line_7));
				if (!(T66_)) goto LA67_;
				inp_6 = line_7;
				idx_6 = ((NI) 0);
				res_6 = NIM_FALSE;
				nimln_(539, "macros.nim");
				res_6 = NIM_TRUE;
				T66_ = res_6;
				LA67_: ;
				if (!!(T66_)) goto LA68_;
				e_6 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*)0;
				nimln_(124, "spriteatlasloader.nim");
				e_6 = (tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA*) newObj((&NTI_yCEN9anxCD6mzBxGjuaRBdg_), sizeof(tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA));
				(*e_6).Sup.Sup.m_type = (&NTI_Gi06FkNeykJn7mrqRZYrkA_);
				T70_ = (NimStringDesc*)0;
				TM_THCNEHkyG9b0BQ4nXMJumiQ_85 = addInt(lineCount, ((NI) 1));
				T71_ = (NimStringDesc*)0;
				T71_ = nimIntToStr((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_85));
				T70_ = rawNewString(T71_->Sup.len + line_7->Sup.len + 22);
appendString(T70_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_16));
appendString(T70_, T71_);
appendString(T70_, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_8));
appendString(T70_, line_7);
				asgnRefNoCycle((void**) (&(*e_6).Sup.message), T70_);
				asgnRef((void**) (&(*e_6).Sup.parent), NIM_NIL);
				raiseException((Exception*)e_6, "ValueError");
			}
			LA68_: ;
			TM_THCNEHkyG9b0BQ4nXMJumiQ_86 = addInt(lineCount, ((NI) 1));
			lineCount = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_86);
			{
				nimln_(126, "spriteatlasloader.nim");
				while (1) {
					NIM_BOOL T74_;
					tyObject_RegDesc_S7CGpRr9aRGBYfCm5btR88w desc;
					tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw T76_;
					NF T77_;
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_87;
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_88;
					NF T78_;
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_89;
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_90;
					NI T79_;
					tySequence_sM4lkSb7zS6F7OVMvW9cffQ* T80_;
					T74_ = (NIM_BOOL)0;
					T74_ = peekLine_9aOHgpnIHcRo6QFN509cEkJQ_2(stream, (&line));
					if (!(T74_)) goto LA75_;
					nimln_(398, "system.nim");
					nimln_(126, "spriteatlasloader.nim");
					T74_ = !(((line) && (line)->Sup.len == 0));
					LA75_: ;
					if (!T74_) goto LA73;
					memset((void*)(&desc), 0, sizeof(desc));
					nimln_(129, "spriteatlasloader.nim");
					parseRegBlock_GQRA5uv7ZveovWyM6jSlmQ(stream, (&lineCount), (&desc));
					nimln_(131, "spriteatlasloader.nim");
					memset((void*)(&T76_), 0, sizeof(T76_));
					nimln_(132, "spriteatlasloader.nim");
					T76_.u0 = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(desc.x, page.width);
					nimln_(133, "spriteatlasloader.nim");
					T77_ = (NF)0;
					T77_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(desc.y, page.height);
					T76_.v0 = ((NF)(1.0000000000000000e+000) - (NF)(T77_));
					nimln_(134, "spriteatlasloader.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_87 = addInt(desc.x, desc.width);
					T76_.u1 = slash__fu0hCFNNw3xnGgcs2KwTWgsystem((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_87), page.width);
					nimln_(135, "spriteatlasloader.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_88 = addInt(desc.y, desc.height);
					T78_ = (NF)0;
					T78_ = slash__fu0hCFNNw3xnGgcs2KwTWgsystem((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_88), page.height);
					T76_.v1 = ((NF)(1.0000000000000000e+000) - (NF)(T78_));
					T76_.logicalWidth = desc.logicalWidth;
					T76_.logicalHeight = desc.logicalHeight;
					T76_.width = desc.width;
					T76_.height = desc.height;
					T76_.xoffs = desc.xoffs;
					nimln_(141, "spriteatlasloader.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_89 = subInt(desc.logicalHeight, desc.yoffs);
					TM_THCNEHkyG9b0BQ4nXMJumiQ_90 = subInt((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_89), desc.height);
					T76_.yoffs = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_90);
					nimln_(142, "spriteatlasloader.nim");
					T79_ = ((*atlas).pages ? (*atlas).pages->Sup.len : 0);
					T76_.page = T79_;
					nimln_(143, "spriteatlasloader.nim");
					T80_ = (tySequence_sM4lkSb7zS6F7OVMvW9cffQ*)0;
					T80_ = nsuSplitString(desc.name, ((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_91), ((NI) -1));
					insertReg_cCItPLlEVf9boS51TDye5Yg((&(*atlas).dir), (&T76_), desc.index, T80_->data, T80_->Sup.len, ((NI) 0));
				} LA73: ;
			}
			nimln_(145, "spriteatlasloader.nim");
			(*atlas).pages = (tySequence_WzvE7PdLW9bdyTHkZUG6C0Q*) incrSeqV2(&((*atlas).pages)->Sup, sizeof(tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g));
			T81_ = (*atlas).pages->Sup.len++;
			(*atlas).pages->data[T81_].width = page.width;
			(*atlas).pages->data[T81_].height = page.height;
			T82_ = (NimStringDesc*)0;
			T82_ = (*atlas).pages->data[T81_].path; (*atlas).pages->data[T81_].path = copyStringRC1(page.path);
			if (T82_) nimGCunrefNoCycle(T82_);
		} LA2: ;
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__lm5gTpG3wpvJqfh17uCCpA)(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ entry) {
	NimStringDesc* result;
	nimfr_("$", "spriteatlasloader.nim");
	result = (NimStringDesc*)0;
	nimln_(152, "spriteatlasloader.nim");
	{
		if (!entry.leaf) goto LA3_;
		nimln_(153, "spriteatlasloader.nim");
		if (!(((2 &(1U<<((NU)(entry.leaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_7));
		result = dollar__AL4x9c75I1uxEnKAciW3OAA(entry.leafU.S1.regs);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(155, "spriteatlasloader.nim");
		if (!(((1 &(1U<<((NU)(entry.leaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_5));
		result = dollar__mX8pQU7600LRrHVD6HOR9ag(entry.leafU.S2.dir);
	}
	LA1_: ;
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, printDir_UBqDBxP3vzRgEEi1d3CCTw)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q dir, NimStringDesc* ind) {
	nimfr_("printDir", "spriteatlasloader.nim");
	{
		NimStringDesc* key;
		key = (NimStringDesc*)0;
		{
			NI h;
			NI colontmp_;
			NI T3_;
			NI res;
			h = (NI)0;
			colontmp_ = (NI)0;
			nimln_(255, "tables.nim");
			T3_ = (dir.data ? (dir.data->Sup.len-1) : -1);
			colontmp_ = T3_;
			nimln_(2045, "system.nim");
			res = ((NI) 0);
			{
				nimln_(2046, "system.nim");
				while (1) {
					NI TM_THCNEHkyG9b0BQ4nXMJumiQ_93;
					if (!(res <= colontmp_)) goto LA5;
					nimln_(2047, "system.nim");
					h = res;
					nimln_(256, "tables.nim");
					{
						NIM_BOOL T8_;
						tyArray_24KAM9afIUgUaqBaEBB6r9bg T11_;
						tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ T12_;
						NimStringDesc* T13_;
						if ((NU)(h) >= (NU)(dir.data->Sup.len)) raiseIndexError();
						T8_ = (NIM_BOOL)0;
						T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(dir.data->data[h].Field0);
						if (!T8_) goto LA9_;
						if ((NU)(h) >= (NU)(dir.data->Sup.len)) raiseIndexError();
						key = dir.data->data[h].Field1;
						nimln_(161, "spriteatlasloader.nim");
						memset((void*)T11_, 0, sizeof(T11_));
						T11_[0] = copyString(ind);
						T11_[1] = copyString(key);
						T11_[2] = copyString(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_92));
						echoBinSafe(T11_, 3);
						nimln_(162, "spriteatlasloader.nim");
						memset((void*)(&T12_), 0, sizeof(T12_));
						X5BX5D__zcwPTNhPAum8RGgySuB6yw(dir, key, (&T12_));
						T13_ = (NimStringDesc*)0;
						T13_ = rawNewString(ind->Sup.len + ind->Sup.len + 0);
appendString(T13_, ind);
appendString(T13_, ind);
						printEntry_Ck1bmhzHeGCkUY6B0DzDuQ(T12_, T13_);
					}
					LA9_: ;
					nimln_(2048, "system.nim");
					TM_THCNEHkyG9b0BQ4nXMJumiQ_93 = addInt(res, ((NI) 1));
					res = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_93);
				} LA5: ;
			}
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, printEntry_Ck1bmhzHeGCkUY6B0DzDuQ)(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ entry, NimStringDesc* ind) {
	nimfr_("printEntry", "spriteatlasloader.nim");
	nimln_(165, "spriteatlasloader.nim");
	{
		tyArray_Re75IspeoxXy2oCZHwcRrA T5_;
		if (!entry.leaf) goto LA3_;
		nimln_(166, "spriteatlasloader.nim");
		memset((void*)T5_, 0, sizeof(T5_));
		T5_[0] = copyString(ind);
		if (!(((2 &(1U<<((NU)(entry.leaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_7));
		T5_[1] = dollar__AL4x9c75I1uxEnKAciW3OAA(entry.leafU.S1.regs);
		echoBinSafe(T5_, 2);
	}
	goto LA1_;
	LA3_: ;
	{
		nimln_(168, "spriteatlasloader.nim");
		if (!(((1 &(1U<<((NU)(entry.leaf)&7U)))!=0))) raiseFieldError(((NimStringDesc*) &TM_THCNEHkyG9b0BQ4nXMJumiQ_5));
		printDir_UBqDBxP3vzRgEEi1d3CCTw(entry.leafU.S2.dir, ind);
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_94;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_THCNEHkyG9b0BQ4nXMJumiQ_94 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_94) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_OVftIzDoNNg1ML9adNJj9a2Qtables)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_95;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_THCNEHkyG9b0BQ4nXMJumiQ_95 = subInt(((NI) -1), h);
	result = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_95);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetKnownHC_S9bfN6OPlbXf79cIz23P9cYAgtables)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_96;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_THCNEHkyG9b0BQ4nXMJumiQ_96 = subInt(((NI) -1), h);
	result = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_96);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x) {
	NI result;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(109, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetDeep_9aeDPbhxF26fhAXAucq5Bgwtables)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	nimfr_("rawGetDeep", "tableimpl.nim");
	result = (NI)0;
	nimln_(57, "tableimpl.nim");
	(*hc) = hash_M6zZEYz39abIOUmj0QsNREghashes(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(58, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(59, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T9_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(60, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T9_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T9_);
		} LA7: ;
	}
	nimln_(61, "tableimpl.nim");
	result = h;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_9aeDPbhxF26fhAXAucq5Bgw_2tables)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_THCNEHkyG9b0BQ4nXMJumiQ_97;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_M6zZEYz39abIOUmj0QsNREghashes(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_THCNEHkyG9b0BQ4nXMJumiQ_97 = subInt(((NI) -1), h);
	result = (NI)(TM_THCNEHkyG9b0BQ4nXMJumiQ_97);
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_spriteatlasloaderInit000)(void) {
	nimfr_("spriteatlasloader", "spriteatlasloader.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_spriteatlasloaderDatInit000)(void) {
static TNimNode* TM_THCNEHkyG9b0BQ4nXMJumiQ_3[2];
static TNimNode TM_THCNEHkyG9b0BQ4nXMJumiQ_0[6];
NTI_FObehHmSKwAl6Yz9bwTsjiw_.size = sizeof(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw);
NTI_FObehHmSKwAl6Yz9bwTsjiw_.kind = 18;
NTI_FObehHmSKwAl6Yz9bwTsjiw_.base = 0;
NTI_FObehHmSKwAl6Yz9bwTsjiw_.flags = 2;
TM_THCNEHkyG9b0BQ4nXMJumiQ_3[0] = &TM_THCNEHkyG9b0BQ4nXMJumiQ_0[1];
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[1].kind = 1;
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[1].offset = offsetof(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw, data);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[1].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[1].name = "data";
TM_THCNEHkyG9b0BQ4nXMJumiQ_3[1] = &TM_THCNEHkyG9b0BQ4nXMJumiQ_0[2];
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[2].kind = 1;
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[2].offset = offsetof(tyObject_CtsStream_FObehHmSKwAl6Yz9bwTsjiw, pos);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[2].name = "pos";
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[0].len = 2; TM_THCNEHkyG9b0BQ4nXMJumiQ_0[0].kind = 2; TM_THCNEHkyG9b0BQ4nXMJumiQ_0[0].sons = &TM_THCNEHkyG9b0BQ4nXMJumiQ_3[0];
NTI_FObehHmSKwAl6Yz9bwTsjiw_.node = &TM_THCNEHkyG9b0BQ4nXMJumiQ_0[0];
NTI_NdvWyrh1mMPCgDSZoEuCZQ_.size = sizeof(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ);
NTI_NdvWyrh1mMPCgDSZoEuCZQ_.kind = 18;
NTI_NdvWyrh1mMPCgDSZoEuCZQ_.base = 0;
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[3].kind = 3;
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[3].offset = offsetof(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ, leaf);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[3].typ = (&NTI_VaVACK0bpYmqIQ0mKcHfQQ_);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[3].name = "leaf";
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[3].sons = &NimDT__NdvWyrh1mMPCgDSZoEuCZQ_leaf[0];
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[3].len = 2;
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[4].kind = 1;
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[4].offset = offsetof(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ, leafU.S1.regs);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[4].typ = (&NTI_s9a6JMyQZ55Jz5fGce9aWo0A_);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[4].name = "regs";
NimDT__NdvWyrh1mMPCgDSZoEuCZQ_leaf[1] = &TM_THCNEHkyG9b0BQ4nXMJumiQ_0[4];
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[5].kind = 1;
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[5].offset = offsetof(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ, leafU.S2.dir);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[5].typ = (&NTI_VYUBB7iQgr6JV9bHeS0Ht7Q_);
TM_THCNEHkyG9b0BQ4nXMJumiQ_0[5].name = "dir";
NimDT__NdvWyrh1mMPCgDSZoEuCZQ_leaf[0] = &TM_THCNEHkyG9b0BQ4nXMJumiQ_0[5];
NTI_NdvWyrh1mMPCgDSZoEuCZQ_.node = &TM_THCNEHkyG9b0BQ4nXMJumiQ_0[3];
NTI_WzvE7PdLW9bdyTHkZUG6C0Q_.size = sizeof(tySequence_WzvE7PdLW9bdyTHkZUG6C0Q*);
NTI_WzvE7PdLW9bdyTHkZUG6C0Q_.kind = 24;
NTI_WzvE7PdLW9bdyTHkZUG6C0Q_.base = (&NTI_PUESnDTGwFKYB1Hds1Rg6g_);
NTI_WzvE7PdLW9bdyTHkZUG6C0Q_.flags = 2;
NTI_WzvE7PdLW9bdyTHkZUG6C0Q_.marker = Marker_tySequence_WzvE7PdLW9bdyTHkZUG6C0Q;
}

