/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimengine\src\nimcache\spriteatlas.o C:\Users\Desktop-P1NKA\Desktop\nimengine\src\nimcache\spriteatlas.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw;
typedef struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ {
NI width;
NI height;
NU32 handle;
};
struct tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw {
NF u0;
NF v0;
NF u1;
NF v1;
NI width;
NI height;
NI logicalWidth;
NI logicalHeight;
NI xoffs;
NI yoffs;
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex;
NI page;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g {
NI width;
NI height;
NimStringDesc* path;
};
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
TNimType NTI_Ilul4CN69aDnVQVDpHK9a2Aw_;
extern TNimType NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_rRMR38YRTFk9b55z9cSXatnQ_;
TNimType NTI_PUESnDTGwFKYB1Hds1Rg6g_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}
NIM_EXTERNC N_NOINLINE(void, unknown_spriteatlasInit000)(void) {
	nimfr_("spriteatlas", "spriteatlas.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_spriteatlasDatInit000)(void) {
static TNimNode* TM_8uWemHEAqG7LvWdWfraLtA_2[12];
static TNimNode* TM_8uWemHEAqG7LvWdWfraLtA_3[3];
static TNimNode TM_8uWemHEAqG7LvWdWfraLtA_0[17];
NTI_Ilul4CN69aDnVQVDpHK9a2Aw_.size = sizeof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw);
NTI_Ilul4CN69aDnVQVDpHK9a2Aw_.kind = 18;
NTI_Ilul4CN69aDnVQVDpHK9a2Aw_.base = 0;
NTI_Ilul4CN69aDnVQVDpHK9a2Aw_.flags = 3;
TM_8uWemHEAqG7LvWdWfraLtA_2[0] = &TM_8uWemHEAqG7LvWdWfraLtA_0[1];
TM_8uWemHEAqG7LvWdWfraLtA_0[1].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[1].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, u0);
TM_8uWemHEAqG7LvWdWfraLtA_0[1].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_8uWemHEAqG7LvWdWfraLtA_0[1].name = "u0";
TM_8uWemHEAqG7LvWdWfraLtA_2[1] = &TM_8uWemHEAqG7LvWdWfraLtA_0[2];
TM_8uWemHEAqG7LvWdWfraLtA_0[2].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[2].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, v0);
TM_8uWemHEAqG7LvWdWfraLtA_0[2].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_8uWemHEAqG7LvWdWfraLtA_0[2].name = "v0";
TM_8uWemHEAqG7LvWdWfraLtA_2[2] = &TM_8uWemHEAqG7LvWdWfraLtA_0[3];
TM_8uWemHEAqG7LvWdWfraLtA_0[3].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[3].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, u1);
TM_8uWemHEAqG7LvWdWfraLtA_0[3].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_8uWemHEAqG7LvWdWfraLtA_0[3].name = "u1";
TM_8uWemHEAqG7LvWdWfraLtA_2[3] = &TM_8uWemHEAqG7LvWdWfraLtA_0[4];
TM_8uWemHEAqG7LvWdWfraLtA_0[4].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[4].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, v1);
TM_8uWemHEAqG7LvWdWfraLtA_0[4].typ = (&NTI_w9bl9a1ul9ctRJWiMl9cNnIMvg_);
TM_8uWemHEAqG7LvWdWfraLtA_0[4].name = "v1";
TM_8uWemHEAqG7LvWdWfraLtA_2[4] = &TM_8uWemHEAqG7LvWdWfraLtA_0[5];
TM_8uWemHEAqG7LvWdWfraLtA_0[5].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[5].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, width);
TM_8uWemHEAqG7LvWdWfraLtA_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[5].name = "width";
TM_8uWemHEAqG7LvWdWfraLtA_2[5] = &TM_8uWemHEAqG7LvWdWfraLtA_0[6];
TM_8uWemHEAqG7LvWdWfraLtA_0[6].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[6].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, height);
TM_8uWemHEAqG7LvWdWfraLtA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[6].name = "height";
TM_8uWemHEAqG7LvWdWfraLtA_2[6] = &TM_8uWemHEAqG7LvWdWfraLtA_0[7];
TM_8uWemHEAqG7LvWdWfraLtA_0[7].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[7].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, logicalWidth);
TM_8uWemHEAqG7LvWdWfraLtA_0[7].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[7].name = "logicalWidth";
TM_8uWemHEAqG7LvWdWfraLtA_2[7] = &TM_8uWemHEAqG7LvWdWfraLtA_0[8];
TM_8uWemHEAqG7LvWdWfraLtA_0[8].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[8].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, logicalHeight);
TM_8uWemHEAqG7LvWdWfraLtA_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[8].name = "logicalHeight";
TM_8uWemHEAqG7LvWdWfraLtA_2[8] = &TM_8uWemHEAqG7LvWdWfraLtA_0[9];
TM_8uWemHEAqG7LvWdWfraLtA_0[9].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[9].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, xoffs);
TM_8uWemHEAqG7LvWdWfraLtA_0[9].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[9].name = "xoffs";
TM_8uWemHEAqG7LvWdWfraLtA_2[9] = &TM_8uWemHEAqG7LvWdWfraLtA_0[10];
TM_8uWemHEAqG7LvWdWfraLtA_0[10].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[10].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, yoffs);
TM_8uWemHEAqG7LvWdWfraLtA_0[10].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[10].name = "yoffs";
TM_8uWemHEAqG7LvWdWfraLtA_2[10] = &TM_8uWemHEAqG7LvWdWfraLtA_0[11];
TM_8uWemHEAqG7LvWdWfraLtA_0[11].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[11].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, tex);
TM_8uWemHEAqG7LvWdWfraLtA_0[11].typ = (&NTI_rRMR38YRTFk9b55z9cSXatnQ_);
TM_8uWemHEAqG7LvWdWfraLtA_0[11].name = "tex";
TM_8uWemHEAqG7LvWdWfraLtA_2[11] = &TM_8uWemHEAqG7LvWdWfraLtA_0[12];
TM_8uWemHEAqG7LvWdWfraLtA_0[12].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[12].offset = offsetof(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, page);
TM_8uWemHEAqG7LvWdWfraLtA_0[12].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[12].name = "page";
TM_8uWemHEAqG7LvWdWfraLtA_0[0].len = 12; TM_8uWemHEAqG7LvWdWfraLtA_0[0].kind = 2; TM_8uWemHEAqG7LvWdWfraLtA_0[0].sons = &TM_8uWemHEAqG7LvWdWfraLtA_2[0];
NTI_Ilul4CN69aDnVQVDpHK9a2Aw_.node = &TM_8uWemHEAqG7LvWdWfraLtA_0[0];
NTI_PUESnDTGwFKYB1Hds1Rg6g_.size = sizeof(tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g);
NTI_PUESnDTGwFKYB1Hds1Rg6g_.kind = 18;
NTI_PUESnDTGwFKYB1Hds1Rg6g_.base = 0;
NTI_PUESnDTGwFKYB1Hds1Rg6g_.flags = 2;
TM_8uWemHEAqG7LvWdWfraLtA_3[0] = &TM_8uWemHEAqG7LvWdWfraLtA_0[14];
TM_8uWemHEAqG7LvWdWfraLtA_0[14].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[14].offset = offsetof(tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g, width);
TM_8uWemHEAqG7LvWdWfraLtA_0[14].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[14].name = "width";
TM_8uWemHEAqG7LvWdWfraLtA_3[1] = &TM_8uWemHEAqG7LvWdWfraLtA_0[15];
TM_8uWemHEAqG7LvWdWfraLtA_0[15].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[15].offset = offsetof(tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g, height);
TM_8uWemHEAqG7LvWdWfraLtA_0[15].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_8uWemHEAqG7LvWdWfraLtA_0[15].name = "height";
TM_8uWemHEAqG7LvWdWfraLtA_3[2] = &TM_8uWemHEAqG7LvWdWfraLtA_0[16];
TM_8uWemHEAqG7LvWdWfraLtA_0[16].kind = 1;
TM_8uWemHEAqG7LvWdWfraLtA_0[16].offset = offsetof(tyObject_AtlasPage_PUESnDTGwFKYB1Hds1Rg6g, path);
TM_8uWemHEAqG7LvWdWfraLtA_0[16].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_8uWemHEAqG7LvWdWfraLtA_0[16].name = "path";
TM_8uWemHEAqG7LvWdWfraLtA_0[13].len = 3; TM_8uWemHEAqG7LvWdWfraLtA_0[13].kind = 2; TM_8uWemHEAqG7LvWdWfraLtA_0[13].sons = &TM_8uWemHEAqG7LvWdWfraLtA_3[0];
NTI_PUESnDTGwFKYB1Hds1Rg6g_.node = &TM_8uWemHEAqG7LvWdWfraLtA_0[13];
}

