/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimengine\src\nimcache\stdlib_tables.o C:\Users\Desktop-P1NKA\Desktop\nimengine\src\nimcache\stdlib_tables.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w;
typedef struct tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw;
typedef struct tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A;
typedef struct tyTuple_w2pkV7dQ2qWCfR34rQj5Qw tyTuple_w2pkV7dQ2qWCfR34rQj5Qw;
typedef struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg;
typedef struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA;
typedef struct Exception Exception;
typedef struct RootObj RootObj;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ;
typedef struct tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q;
typedef struct tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A;
typedef struct tySequence_uTDAVJgt4heRKwc9cJkhwhw tySequence_uTDAVJgt4heRKwc9cJkhwhw;
typedef struct tySequence_fQOhtRDCMDpsajodiC1WLg tySequence_fQOhtRDCMDpsajodiC1WLg;
typedef struct tyTuple_C80qVni9bN9alMWam2oML36Q tyTuple_C80qVni9bN9alMWam2oML36Q;
typedef struct tyTuple_PlkGsuz7STQxey5DAiEKnQ tyTuple_PlkGsuz7STQxey5DAiEKnQ;
typedef struct tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw;
typedef struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w {
tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw* data;
NI counter;
};
struct tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A {
NIM_CHAR r;
NIM_CHAR g;
NIM_CHAR b;
NIM_CHAR a;
};
struct tyTuple_w2pkV7dQ2qWCfR34rQj5Qw {
NI Field0;
tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A Field1;
NI Field2;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
struct RootObj {
TNimType* m_type;
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA {
  Exception Sup;
};
struct tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg {
  tyObject_ValueError_Gi06FkNeykJn7mrqRZYrkA Sup;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
struct tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A {
tySequence_uTDAVJgt4heRKwc9cJkhwhw* data;
NI counter;
};
struct tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q {
tySequence_fQOhtRDCMDpsajodiC1WLg* data;
NI counter;
};
struct tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ {
NIM_BOOL leaf;
union{
struct {tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A regs;
} S1;
struct {tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q dir;
} S2;
} leafU;
};
struct tyTuple_C80qVni9bN9alMWam2oML36Q {
NI Field0;
NimStringDesc* Field1;
tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ Field2;
};
struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ {
NI width;
NI height;
NU32 handle;
};
struct tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw {
NF u0;
NF v0;
NF u1;
NF v1;
NI width;
NI height;
NI logicalWidth;
NI logicalHeight;
NI xoffs;
NI yoffs;
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex;
NI page;
};
struct tyTuple_PlkGsuz7STQxey5DAiEKnQ {
NI Field0;
NI Field1;
tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw Field2;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw {
  TGenericSeq Sup;
  tyTuple_w2pkV7dQ2qWCfR34rQj5Qw data[SEQ_DECL_SIZE];
};
struct tySequence_fQOhtRDCMDpsajodiC1WLg {
  TGenericSeq Sup;
  tyTuple_C80qVni9bN9alMWam2oML36Q data[SEQ_DECL_SIZE];
};
struct tySequence_uTDAVJgt4heRKwc9cJkhwhw {
  TGenericSeq Sup;
  tyTuple_PlkGsuz7STQxey5DAiEKnQ data[SEQ_DECL_SIZE];
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
static N_INLINE(NIM_BOOL, isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode);
static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_NIMCALL(NI, mulInt)(NI a, NI b);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash);
static N_INLINE(NI, addInt)(NI a, NI b);
static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count);
N_LIB_PRIVATE N_NIMCALL(NI, nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA)(NI x);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, rawGet_SGdxF4aWZm8Oh38HXd5iWQtables)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w t, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_yuY9cJg9cAdlrbaCdIuBRtIQ)(tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A c);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq__r0wWIMSZuguAbVSyc9bw9cPA)(tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A x, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A y);
N_NIMCALL(void*, newObj)(TNimType* typ, NI size);
static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src);
static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size);
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__W9aiyCXI9bBY9bXUnzemT7NgA)(tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A x);
N_NIMCALL(NimStringDesc*, rawNewString)(NI space);
static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_NOINLINE(void, chckNil)(void* p);
static N_NIMCALL(void, Marker_tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw)(void* p, NI op);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg)(NI x);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NIMCALL(void*, newSeq)(TNimType* typ, NI len);
N_NIMCALL(void, unsureAsgnRef)(void** dest, void* src);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_JLYnU5LISmK2fYXkXdiuAA)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_htTCX38S0oNxHwpBuh9cyhg)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w* t, tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw** data, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key, NI val, NI hc, NI h);
static N_INLINE(NI, rawGetKnownHC_lkHd9c4rhePeuQ4FqQ2iCtAtables)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w t, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key, NI hc);
static N_INLINE(NI, rawGet_OVftIzDoNNg1ML9adNJj9a2Qtables)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, NI* hc);
N_LIB_PRIVATE N_NIMCALL(NI, hash_uBstFm5SYVQeOL3j9c9bc58A)(NimStringDesc* x);
static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b);
static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_9cBIHqYsh1oBSF5JO1TUMWQ)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* t);
static N_NIMCALL(void, Marker_tySequence_uTDAVJgt4heRKwc9cJkhwhw)(void* p, NI op);
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, Marker_tySequence_fQOhtRDCMDpsajodiC1WLg)(void* p, NI op);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_bRZGA9b9bqLuN3RTworf2D7Q)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* t, tySequence_fQOhtRDCMDpsajodiC1WLg** data, NimStringDesc* key, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ val, NI hc, NI h);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
N_NIMCALL(void, genericAssign)(void* dest, void* src, TNimType* mt);
static N_INLINE(NI, rawGetKnownHC_S9bfN6OPlbXf79cIz23P9cYAgtables)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, NI hc);
N_LIB_PRIVATE N_NIMCALL(void, enlarge_4Xl8scbDVmcdOPmoARONhA)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* t);
N_LIB_PRIVATE N_NIMCALL(void, rawInsert_pp6pu3dJY59cSOuBTSSB9cMQ)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* t, tySequence_uTDAVJgt4heRKwc9cJkhwhw** data, NI key, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* val, NI hc, NI h);
static N_INLINE(NI, rawGetDeep_9aeDPbhxF26fhAXAucq5Bgwtables)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key, NI* hc);
static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x);
N_LIB_PRIVATE N_NIMCALL(NI, len_O8KbWIdPuGdKZNJ8im9aOPw)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
N_NIMCALL(NimStringDesc*, resizeString)(NimStringDesc* dest, NI addlen);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_nyaZAljVI03SH2d9cnD0WMw)(NimStringDesc** s, NI x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_P15pMNpPzeOrboQYn9b8YEQ)(NimStringDesc** s, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* x);
N_LIB_PRIVATE N_NIMCALL(NI, len_7XbOL9aqlP4K5ktPo2C4K1g)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_KHwyPEV6PV8Q9aS88ENydhw)(NimStringDesc** s, NimStringDesc* x);
N_LIB_PRIVATE N_NIMCALL(void, addQuoted_UQQwT01he1jqp0OpJpqgzg)(NimStringDesc** s, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ x);
static N_INLINE(NI, rawGet_9aeDPbhxF26fhAXAucq5Bgw_2tables)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key, NI* hc);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_axqhRnwd09cVJkRcojfw6mA_;
extern TNimType NTI_ifYAhUumNzWR9c9cN9amyJLtg_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
TNimType NTI_Ye4zca3XfMwtCqFH1n2x5w_;
TNimType NTI_w2pkV7dQ2qWCfR34rQj5Qw_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_P4w0wnmH7J1IGztO6QfG5A_;
TNimType NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_;
TNimType NTI_C80qVni9bN9alMWam2oML36Q_;
extern TNimType NTI_77mFvmsOLKik79ci2hXkHEg_;
TNimType NTI_s9a6JMyQZ55Jz5fGce9aWo0A_;
TNimType NTI_PlkGsuz7STQxey5DAiEKnQ_;
extern TNimType NTI_Ilul4CN69aDnVQVDpHK9a2Aw_;
TNimType NTI_uTDAVJgt4heRKwc9cJkhwhw_;
TNimType NTI_VYUBB7iQgr6JV9bHeS0Ht7Q_;
extern TNimType NTI_NdvWyrh1mMPCgDSZoEuCZQ_;
TNimType NTI_fQOhtRDCMDpsajodiC1WLg_;
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_2, "\012counter < length ", 18);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_11, "key not found: ", 15);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_14, "isPowerOfTwo(initialSize) ", 26);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_33, "{:}", 3);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_34, "{", 1);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_35, ", ", 2);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_36, ": ", 2);
STRING_LITERAL(TM_4SoG2KRQy3oMm9aUzSLtGrA_38, "}", 1);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NIM_BOOL, isEmpty_IxXD1UAPoEehVDW9cv9cRaewtables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isEmpty", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(15, "tableimpl.nim");
	result = (hcode == ((NI) 0));
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables)(NI hcode) {
	NIM_BOOL result;
	nimfr_("isFilled", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(18, "tableimpl.nim");
	nimln_(398, "system.nim");
	nimln_(18, "tableimpl.nim");
	result = !((hcode == ((NI) 0)));
	popFrame();
	return result;
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables)(NI length, NI counter) {
	NIM_BOOL result;
	NIM_BOOL T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_3;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_4;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_5;
	nimfr_("mustRehash", "tableimpl.nim");
	result = (NIM_BOOL)0;
	nimln_(24, "tableimpl.nim");
	{
		if (!!((counter < length))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_2));
	}
	LA3_: ;
	nimln_(25, "tableimpl.nim");
	T5_ = (NIM_BOOL)0;
	TM_4SoG2KRQy3oMm9aUzSLtGrA_3 = mulInt(length, ((NI) 2));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_4 = mulInt(counter, ((NI) 3));
	T5_ = ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_3) < (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_4));
	if (T5_) goto LA6_;
	TM_4SoG2KRQy3oMm9aUzSLtGrA_5 = subInt(length, counter);
	T5_ = ((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_5) < ((NI) 4));
	LA6_: ;
	result = T5_;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, nextTry_OLPhxSyW9bte5CwHzzQVhfAtables)(NI h, NI maxHash) {
	NI result;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_6;
	nimfr_("nextTry", "tableimpl.nim");
	result = (NI)0;
	nimln_(28, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_6 = addInt(h, ((NI) 1));
	result = (NI)((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_6) & maxHash);
	popFrame();
	return result;
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rightSize_l3wfAVpWNBWtzL8kQfvMMAtables)(NI count) {
	NI result;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_7;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_8;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_9;
	nimfr_("rightSize", "tables.nim");
	result = (NI)0;
	nimln_(136, "tables.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_7 = mulInt(((NI) (count)), ((NI) 3));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_8 = divInt((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_7), ((NI) 2));
	TM_4SoG2KRQy3oMm9aUzSLtGrA_9 = addInt((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_8), ((NI) 4));
	result = nextPowerOfTwo_gcitR3TEXHJ3GR9bmwIvtRA((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_9));
	popFrame();
	return result;
}

static N_INLINE(NI, rawGet_SGdxF4aWZm8Oh38HXd5iWQtables)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w t, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_10;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_yuY9cJg9cAdlrbaCdIuBRtIQ(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqeq__r0wWIMSZuguAbVSyc9bw9cPA(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_10 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_10);
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(void, copyMem_E1xtACub5WcDa3vbrIXbwgsystem)(void* dest, void* source, NI size) {
	void* T1_;
	T1_ = (void*)0;
	T1_ = memcpy(dest, source, ((size_t) (size)));
}

static N_INLINE(void, appendString)(NimStringDesc* dest, NimStringDesc* src) {
	copyMem_E1xtACub5WcDa3vbrIXbwgsystem(((void*) ((&(*dest).data[((*dest).Sup.len)- 0]))), ((void*) ((*src).data)), ((NI) ((NI)((*src).Sup.len + ((NI) 1)))));
	(*dest).Sup.len += (*src).Sup.len;
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, asgnRefNoCycle)(void** dest, void* src) {
	nimfr_("asgnRefNoCycle", "gc.nim");
	nimln_(271, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
		nimln_(398, "system.nim");
		nimln_(271, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		nimln_(272, "gc.nim");
		c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		nimln_(273, "gc.nim");
		(*c).refcount += ((NI) 8);
	}
	LA3_: ;
	nimln_(274, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c_2;
		nimln_(398, "system.nim");
		nimln_(274, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA7_;
		nimln_(275, "gc.nim");
		c_2 = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		nimln_(276, "gc.nim");
		{
			(*c_2).refcount -= ((NI) 8);
			if (!((NU64)((*c_2).refcount) < (NU64)(((NI) 8)))) goto LA11_;
			nimln_(277, "gc.nim");
			rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c_2);
		}
		LA11_: ;
	}
	LA7_: ;
	nimln_(278, "gc.nim");
	(*dest) = src;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, X5BX5D__eWskklWT2sM34gRXz9cFZjg)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w t, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key) {
	NI result;
	NI hc;
	NI index;
	nimfr_("[]", "tables.nim");
	result = (NI)0;
	hc = (NI)0;
	nimln_(147, "tables.nim");
	index = rawGet_SGdxF4aWZm8Oh38HXd5iWQtables(t, key, (&hc));
	nimln_(165, "tables.nim");
	{
		nimln_(148, "tables.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)(t.data->Sup.len)) raiseIndexError();
		result = t.data->data[index].Field2;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		nimln_(151, "tables.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(165, "tables.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = dollar__W9aiyCXI9bBY9bXUnzemT7NgA(key);
		T6_ = rawNewString(T7_->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_11));
appendString(T6_, T7_);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(151, "tables.nim");
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw)(void* p, NI op) {
	tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw* a;
	NI T1_;
	a = (tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw*)p;
	T1_ = (NI)0;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_dB6q5J4H5jjbcH69a6Ra9a1Q)(NI initialSize, tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w* Result) {
	nimfr_("initTable", "tables.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_Ye4zca3XfMwtCqFH1n2x5w_));
	nimln_(324, "tables.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_14));
	}
	LA4_: ;
	nimln_(325, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln_(326, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw*) newSeq((&NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_htTCX38S0oNxHwpBuh9cyhg)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w* t, tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw** data, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key, NI val, NI hc, NI h) {
	nimfr_("rawInsert", "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(64, "tableimpl.nim");
	(*data)->data[h].Field1 = key;
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(65, "tableimpl.nim");
	(*data)->data[h].Field2 = val;
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(66, "tableimpl.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_JLYnU5LISmK2fYXkXdiuAA)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w* t) {
	tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw* n;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_15;
	tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw* T2_;
	nimfr_("enlarge", "tables.nim");
	n = (tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw*)0;
	nimln_(286, "tables.nim");
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	TM_4SoG2KRQy3oMm9aUzSLtGrA_15 = mulInt(T1_, ((NI) 2));
	n = (tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw*) newSeq((&NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_), ((NI)chckRange((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_15), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(287, "tables.nim");
	T2_ = (tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(288, "tables.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI eh;
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_16;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(289, "tables.nim");
				if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
				eh = n->data[i].Field0;
				nimln_(290, "tables.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(eh);
					if (!T9_) goto LA10_;
					nimln_(291, "tables.nim");
					nimln_(116, "tables.nim");
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						nimln_(292, "tables.nim");
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if ((NU)(j) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							nimln_(293, "tables.nim");
							nimln_(116, "tables.nim");
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					nimln_(294, "tables.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_htTCX38S0oNxHwpBuh9cyhg(t, (&(*t).data), n->data[i].Field1, n->data[i].Field2, eh, j);
				}
				LA10_: ;
				nimln_(2035, "system.nim");
				TM_4SoG2KRQy3oMm9aUzSLtGrA_16 = addInt(res, ((NI) 1));
				res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_16);
			} LA6: ;
		}
	}
	popFrame();
}

static N_INLINE(NI, rawGetKnownHC_lkHd9c4rhePeuQ4FqQ2iCtAtables)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w t, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_17;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqeq__r0wWIMSZuguAbVSyc9bw9cPA(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_17 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_17);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5Deq__sR8kqHax3QR4DqDsWNRLMA)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w* t, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key, NI val) {
	NI hc;
	NI index;
	nimfr_("[]=", "tables.nim");
	hc = (NI)0;
	nimln_(98, "tableimpl.nim");
	index = rawGet_SGdxF4aWZm8Oh38HXd5iWQtables((*t), key, (&hc));
	nimln_(307, "tables.nim");
	{
		nimln_(99, "tableimpl.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
		(*t).data->data[index].Field2 = val;
	}
	goto LA1_;
	LA3_: ;
	{
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_18;
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_19;
		nimln_(89, "tableimpl.nim");
		{
			NI T8_;
			NIM_BOOL T9_;
			nimln_(117, "tables.nim");
			T8_ = ((*t).data ? (*t).data->Sup.len : 0);
			T9_ = (NIM_BOOL)0;
			T9_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T8_, (*t).counter);
			if (!T9_) goto LA10_;
			nimln_(90, "tableimpl.nim");
			enlarge_JLYnU5LISmK2fYXkXdiuAA(t);
			nimln_(91, "tableimpl.nim");
			index = rawGetKnownHC_lkHd9c4rhePeuQ4FqQ2iCtAtables((*t), key, hc);
		}
		LA10_: ;
		nimln_(92, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_18 = subInt(((NI) -1), index);
		index = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_18);
		nimln_(93, "tableimpl.nim");
		rawInsert_htTCX38S0oNxHwpBuh9cyhg(t, (&(*t).data), key, val, hc, index);
		nimln_(94, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_19 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_19);
	}
	LA1_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, hasKey_Zt5D4SH59a7LI9cr3BVTdA4Q)(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w t, tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A key) {
	NIM_BOOL result;
	NI hc;
	NI T1_;
	nimfr_("hasKey", "tables.nim");
	result = (NIM_BOOL)0;
	hc = (NI)0;
	nimln_(236, "tables.nim");
	T1_ = (NI)0;
	T1_ = rawGet_SGdxF4aWZm8Oh38HXd5iWQtables(t, key, (&hc));
	result = (((NI) 0) <= T1_);
	popFrame();
	return result;
}

static N_INLINE(NIM_BOOL, equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem)(void* a, void* b, NI size) {
	NIM_BOOL result;
	int T1_;
	result = (NIM_BOOL)0;
	T1_ = (int)0;
	T1_ = memcmp(a, b, ((size_t) (size)));
	result = (T1_ == ((NI32) 0));
	return result;
}

static N_INLINE(NIM_BOOL, eqStrings)(NimStringDesc* a, NimStringDesc* b) {
	NIM_BOOL result;
	NIM_BOOL T11_;
{	result = (NIM_BOOL)0;
	{
		if (!(a == b)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == NIM_NIL);
		if (T7_) goto LA8_;
		T7_ = (b == NIM_NIL);
		LA8_: ;
		if (!T7_) goto LA9_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA9_: ;
	T11_ = (NIM_BOOL)0;
	T11_ = ((*a).Sup.len == (*b).Sup.len);
	if (!(T11_)) goto LA12_;
	T11_ = equalMem_fmeFeLBvgmAHG9bC8ETS9bYQsystem(((void*) ((*a).data)), ((void*) ((*b).data)), ((NI) ((*a).Sup.len)));
	LA12_: ;
	result = T11_;
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, rawGet_OVftIzDoNNg1ML9adNJj9a2Qtables)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_20;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_uBstFm5SYVQeOL3j9c9bc58A(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = eqStrings(t.data->data[h].Field1, key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_20 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_20);
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, Marker_tySequence_uTDAVJgt4heRKwc9cJkhwhw)(void* p, NI op) {
	tySequence_uTDAVJgt4heRKwc9cJkhwhw* a;
	NI T1_;
	a = (tySequence_uTDAVJgt4heRKwc9cJkhwhw*)p;
	T1_ = (NI)0;
}
static N_NIMCALL(void, Marker_tySequence_fQOhtRDCMDpsajodiC1WLg)(void* p, NI op) {
	tySequence_fQOhtRDCMDpsajodiC1WLg* a;
	NI T1_;
	a = (tySequence_fQOhtRDCMDpsajodiC1WLg*)p;
	T1_ = (NI)0;
	for (T1_ = 0; T1_ < a->Sup.len; T1_++) {
	nimGCvisit((void*)a->data[T1_].Field1, op);
	switch (a->data[T1_].Field2.leaf) {
	case NIM_TRUE:
	nimGCvisit((void*)a->data[T1_].Field2.leafU.S1.regs.data, op);
	break;
	case NIM_FALSE:
	nimGCvisit((void*)a->data[T1_].Field2.leafU.S2.dir.data, op);
	break;
	} 
	}
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_bRZGA9b9bqLuN3RTworf2D7Q)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* t, tySequence_fQOhtRDCMDpsajodiC1WLg** data, NimStringDesc* key, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ val, NI hc, NI h) {
	NimStringDesc* T1_;
	nimfr_("rawInsert", "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(64, "tableimpl.nim");
	T1_ = (NimStringDesc*)0;
	T1_ = (*data)->data[h].Field1; (*data)->data[h].Field1 = copyStringRC1(key);
	if (T1_) nimGCunrefNoCycle(T1_);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(65, "tableimpl.nim");
	genericAssign((void*)(&(*data)->data[h].Field2), (void*)(&val), (&NTI_NdvWyrh1mMPCgDSZoEuCZQ_));
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(66, "tableimpl.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_9cBIHqYsh1oBSF5JO1TUMWQ)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* t) {
	tySequence_fQOhtRDCMDpsajodiC1WLg* n;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_21;
	tySequence_fQOhtRDCMDpsajodiC1WLg* T2_;
	nimfr_("enlarge", "tables.nim");
	n = (tySequence_fQOhtRDCMDpsajodiC1WLg*)0;
	nimln_(286, "tables.nim");
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	TM_4SoG2KRQy3oMm9aUzSLtGrA_21 = mulInt(T1_, ((NI) 2));
	n = (tySequence_fQOhtRDCMDpsajodiC1WLg*) newSeq((&NTI_fQOhtRDCMDpsajodiC1WLg_), ((NI)chckRange((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_21), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(287, "tables.nim");
	T2_ = (tySequence_fQOhtRDCMDpsajodiC1WLg*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(288, "tables.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI eh;
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_26;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(289, "tables.nim");
				if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
				eh = n->data[i].Field0;
				nimln_(290, "tables.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(eh);
					if (!T9_) goto LA10_;
					nimln_(291, "tables.nim");
					nimln_(116, "tables.nim");
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						nimln_(292, "tables.nim");
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if ((NU)(j) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							nimln_(293, "tables.nim");
							nimln_(116, "tables.nim");
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					nimln_(294, "tables.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_bRZGA9b9bqLuN3RTworf2D7Q(t, (&(*t).data), n->data[i].Field1, n->data[i].Field2, eh, j);
				}
				LA10_: ;
				nimln_(2035, "system.nim");
				TM_4SoG2KRQy3oMm9aUzSLtGrA_26 = addInt(res, ((NI) 1));
				res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_26);
			} LA6: ;
		}
	}
	popFrame();
}

static N_INLINE(NI, rawGetKnownHC_S9bfN6OPlbXf79cIz23P9cYAgtables)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, NI hc) {
	NI result;
	NI h;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_27;
	nimfr_("rawGetKnownHC", "tableimpl.nim");
{	result = (NI)0;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T1_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)(hc & T1_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T4_;
			NI T11_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T4_ = (NIM_BOOL)0;
			T4_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T4_) goto LA3;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T7_;
				T7_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = (t.data->data[h].Field0 == hc);
				if (!(T7_)) goto LA8_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T7_ = eqStrings(t.data->data[h].Field1, key);
				LA8_: ;
				if (!T7_) goto LA9_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA9_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T11_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T11_);
		} LA3: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_27 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_27);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ*, mgetOrPut_72R8U6ss4ZI9cxlHSH5N1hw)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* t, NimStringDesc* key, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ val) {
	tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ* result;
	NI hc;
	NI index;
	nimfr_("mgetOrPut", "tables.nim");
	result = (tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ*)0;
	hc = (NI)0;
	nimln_(104, "tableimpl.nim");
	index = rawGet_OVftIzDoNNg1ML9adNJj9a2Qtables((*t), key, (&hc));
	nimln_(105, "tableimpl.nim");
	{
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_28;
		NI TM_4SoG2KRQy3oMm9aUzSLtGrA_29;
		if (!(index < ((NI) 0))) goto LA3_;
		nimln_(89, "tableimpl.nim");
		{
			NI T7_;
			NIM_BOOL T8_;
			nimln_(117, "tables.nim");
			T7_ = ((*t).data ? (*t).data->Sup.len : 0);
			T8_ = (NIM_BOOL)0;
			T8_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T7_, (*t).counter);
			if (!T8_) goto LA9_;
			nimln_(90, "tableimpl.nim");
			enlarge_9cBIHqYsh1oBSF5JO1TUMWQ(t);
			nimln_(91, "tableimpl.nim");
			index = rawGetKnownHC_S9bfN6OPlbXf79cIz23P9cYAgtables((*t), key, hc);
		}
		LA9_: ;
		nimln_(92, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_28 = subInt(((NI) -1), index);
		index = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_28);
		nimln_(93, "tableimpl.nim");
		rawInsert_bRZGA9b9bqLuN3RTworf2D7Q(t, (&(*t).data), key, val, hc, index);
		nimln_(94, "tableimpl.nim");
		TM_4SoG2KRQy3oMm9aUzSLtGrA_29 = addInt((*t).counter, ((NI) 1));
		(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_29);
	}
	LA3_: ;
	nimln_(109, "tableimpl.nim");
	if ((NU)(index) >= (NU)((*t).data->Sup.len)) raiseIndexError();
	result = (&(*t).data->data[index].Field2);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_VpFKAGy3QS4KetRNn6XNlQ)(NI initialSize, tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q* Result) {
	nimfr_("initTable", "tables.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_VYUBB7iQgr6JV9bHeS0Ht7Q_));
	nimln_(324, "tables.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_14));
	}
	LA4_: ;
	nimln_(325, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln_(326, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_fQOhtRDCMDpsajodiC1WLg*) newSeq((&NTI_fQOhtRDCMDpsajodiC1WLg_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, rawInsert_pp6pu3dJY59cSOuBTSSB9cMQ)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* t, tySequence_uTDAVJgt4heRKwc9cJkhwhw** data, NI key, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* val, NI hc, NI h) {
	nimfr_("rawInsert", "tableimpl.nim");
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(64, "tableimpl.nim");
	(*data)->data[h].Field1 = key;
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(65, "tableimpl.nim");
	(*data)->data[h].Field2 = (*val);
	if ((NU)(h) >= (NU)((*data)->Sup.len)) raiseIndexError();
	nimln_(66, "tableimpl.nim");
	(*data)->data[h].Field0 = hc;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, enlarge_4Xl8scbDVmcdOPmoARONhA)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* t) {
	tySequence_uTDAVJgt4heRKwc9cJkhwhw* n;
	NI T1_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_30;
	tySequence_uTDAVJgt4heRKwc9cJkhwhw* T2_;
	nimfr_("enlarge", "tables.nim");
	n = (tySequence_uTDAVJgt4heRKwc9cJkhwhw*)0;
	nimln_(286, "tables.nim");
	T1_ = ((*t).data ? (*t).data->Sup.len : 0);
	TM_4SoG2KRQy3oMm9aUzSLtGrA_30 = mulInt(T1_, ((NI) 2));
	n = (tySequence_uTDAVJgt4heRKwc9cJkhwhw*) newSeq((&NTI_uTDAVJgt4heRKwc9cJkhwhw_), ((NI)chckRange((NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_30), ((NI) 0), ((NI) IL64(9223372036854775807)))));
	nimln_(287, "tables.nim");
	T2_ = (tySequence_uTDAVJgt4heRKwc9cJkhwhw*)0;
	T2_ = (*t).data;
	unsureAsgnRef((void**) (&(*t).data), n);
	n = T2_;
	{
		NI i;
		NI colontmp_;
		NI T4_;
		NI res;
		i = (NI)0;
		colontmp_ = (NI)0;
		nimln_(288, "tables.nim");
		T4_ = (n ? (n->Sup.len-1) : -1);
		colontmp_ = T4_;
		nimln_(2032, "system.nim");
		res = ((NI) 0);
		{
			nimln_(2033, "system.nim");
			while (1) {
				NI eh;
				NI TM_4SoG2KRQy3oMm9aUzSLtGrA_31;
				if (!(res <= colontmp_)) goto LA6;
				nimln_(2034, "system.nim");
				i = res;
				nimln_(289, "tables.nim");
				if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
				eh = n->data[i].Field0;
				nimln_(290, "tables.nim");
				{
					NIM_BOOL T9_;
					NI j;
					NI T12_;
					T9_ = (NIM_BOOL)0;
					T9_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(eh);
					if (!T9_) goto LA10_;
					nimln_(291, "tables.nim");
					nimln_(116, "tables.nim");
					T12_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
					j = (NI)(eh & T12_);
					{
						nimln_(292, "tables.nim");
						while (1) {
							NIM_BOOL T15_;
							NI T16_;
							if ((NU)(j) >= (NU)((*t).data->Sup.len)) raiseIndexError();
							T15_ = (NIM_BOOL)0;
							T15_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables((*t).data->data[j].Field0);
							if (!T15_) goto LA14;
							nimln_(293, "tables.nim");
							nimln_(116, "tables.nim");
							T16_ = ((*t).data ? ((*t).data->Sup.len-1) : -1);
							j = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(j, T16_);
						} LA14: ;
					}
					nimln_(294, "tables.nim");
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					if ((NU)(i) >= (NU)(n->Sup.len)) raiseIndexError();
					rawInsert_pp6pu3dJY59cSOuBTSSB9cMQ(t, (&(*t).data), n->data[i].Field1, (&n->data[i].Field2), eh, j);
				}
				LA10_: ;
				nimln_(2035, "system.nim");
				TM_4SoG2KRQy3oMm9aUzSLtGrA_31 = addInt(res, ((NI) 1));
				res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_31);
			} LA6: ;
		}
	}
	popFrame();
}

static N_INLINE(NI, hash_M6zZEYz39abIOUmj0QsNREghashes)(NI x) {
	NI result;
	nimfr_("hash", "hashes.nim");
	result = (NI)0;
	nimln_(109, "hashes.nim");
	result = x;
	popFrame();
	return result;
}

static N_INLINE(NI, rawGetDeep_9aeDPbhxF26fhAXAucq5Bgwtables)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	nimfr_("rawGetDeep", "tableimpl.nim");
	result = (NI)0;
	nimln_(57, "tableimpl.nim");
	(*hc) = hash_M6zZEYz39abIOUmj0QsNREghashes(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(58, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(59, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T9_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(60, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T9_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T9_);
		} LA7: ;
	}
	nimln_(61, "tableimpl.nim");
	result = h;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, add_xdjKC0QLjR9bZBTz9ct9a1XyQ)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* t, NI key, tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw* val) {
	NI hc;
	NI j;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_32;
	nimfr_("add", "tables.nim");
	nimln_(82, "tableimpl.nim");
	{
		NI T3_;
		NIM_BOOL T4_;
		nimln_(117, "tables.nim");
		T3_ = ((*t).data ? (*t).data->Sup.len : 0);
		T4_ = (NIM_BOOL)0;
		T4_ = mustRehash_CT8KHtrz1uoHrT4RgfOSmQtables(T3_, (*t).counter);
		if (!T4_) goto LA5_;
		nimln_(82, "tableimpl.nim");
		enlarge_4Xl8scbDVmcdOPmoARONhA(t);
	}
	LA5_: ;
	hc = (NI)0;
	nimln_(84, "tableimpl.nim");
	j = rawGetDeep_9aeDPbhxF26fhAXAucq5Bgwtables((*t), key, (&hc));
	nimln_(85, "tableimpl.nim");
	rawInsert_pp6pu3dJY59cSOuBTSSB9cMQ(t, (&(*t).data), key, val, hc, j);
	nimln_(86, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_32 = addInt((*t).counter, ((NI) 1));
	(*t).counter = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_32);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, initTable_9bEe79bLaUXK1rbPlj69c5wOQ)(NI initialSize, tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A* Result) {
	nimfr_("initTable", "tables.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_s9a6JMyQZ55Jz5fGce9aWo0A_));
	nimln_(324, "tables.nim");
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = isPowerOfTwo_M0Db9b9cHxuUgw2ZF0P8utPg(initialSize);
		if (!!(T3_)) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_14));
	}
	LA4_: ;
	nimln_(325, "tables.nim");
	(*Result).counter = ((NI) 0);
	nimln_(326, "tables.nim");
	unsureAsgnRef((void**) (&(*Result).data), (tySequence_uTDAVJgt4heRKwc9cJkhwhw*) newSeq((&NTI_uTDAVJgt4heRKwc9cJkhwhw_), ((NI)chckRange(initialSize, ((NI) 0), ((NI) IL64(9223372036854775807))))));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NI, len_O8KbWIdPuGdKZNJ8im9aOPw)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t) {
	NI result;
	nimfr_("len", "tables.nim");
	result = (NI)0;
	nimln_(140, "tables.nim");
	result = t.counter;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__AL4x9c75I1uxEnKAciW3OAA)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t) {
	NimStringDesc* result;
	nimfr_("$", "tables.nim");
	result = (NimStringDesc*)0;
	nimln_(348, "tables.nim");
	{
		NI T3_;
		nimln_(335, "tables.nim");
		T3_ = (NI)0;
		T3_ = len_O8KbWIdPuGdKZNJ8im9aOPw(t);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(336, "tables.nim");
		result = copyString(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_33));
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(338, "tables.nim");
		result = copyString(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_34));
		{
			NI key;
			tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw val;
			key = (NI)0;
			memset((void*)(&val), 0, sizeof(val));
			{
				NI h;
				NI colontmp_;
				NI T9_;
				NI res;
				h = (NI)0;
				colontmp_ = (NI)0;
				nimln_(244, "tables.nim");
				T9_ = (t.data ? (t.data->Sup.len-1) : -1);
				colontmp_ = T9_;
				nimln_(2045, "system.nim");
				res = ((NI) 0);
				{
					nimln_(2046, "system.nim");
					while (1) {
						NI TM_4SoG2KRQy3oMm9aUzSLtGrA_37;
						if (!(res <= colontmp_)) goto LA11;
						nimln_(2047, "system.nim");
						h = res;
						nimln_(245, "tables.nim");
						{
							NIM_BOOL T14_;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							T14_ = (NIM_BOOL)0;
							T14_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
							if (!T14_) goto LA15_;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							key = t.data->data[h].Field1;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							val = t.data->data[h].Field2;
							nimln_(340, "tables.nim");
							{
								if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA19_;
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_35));
							}
							LA19_: ;
							nimln_(341, "tables.nim");
							addQuoted_nyaZAljVI03SH2d9cnD0WMw((&result), key);
							nimln_(342, "tables.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_36));
							nimln_(343, "tables.nim");
							addQuoted_P15pMNpPzeOrboQYn9b8YEQ((&result), (&val));
						}
						LA15_: ;
						nimln_(2048, "system.nim");
						TM_4SoG2KRQy3oMm9aUzSLtGrA_37 = addInt(res, ((NI) 1));
						res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_37);
					} LA11: ;
				}
			}
		}
		nimln_(344, "tables.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_38));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NI, len_7XbOL9aqlP4K5ktPo2C4K1g)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t) {
	NI result;
	nimfr_("len", "tables.nim");
	result = (NI)0;
	nimln_(140, "tables.nim");
	result = t.counter;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar__mX8pQU7600LRrHVD6HOR9ag)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t) {
	NimStringDesc* result;
	nimfr_("$", "tables.nim");
	result = (NimStringDesc*)0;
	nimln_(348, "tables.nim");
	{
		NI T3_;
		nimln_(335, "tables.nim");
		T3_ = (NI)0;
		T3_ = len_7XbOL9aqlP4K5ktPo2C4K1g(t);
		if (!(T3_ == ((NI) 0))) goto LA4_;
		nimln_(336, "tables.nim");
		result = copyString(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_33));
	}
	goto LA1_;
	LA4_: ;
	{
		nimln_(338, "tables.nim");
		result = copyString(((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_34));
		{
			NimStringDesc* key;
			tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ val;
			key = (NimStringDesc*)0;
			memset((void*)(&val), 0, sizeof(val));
			{
				NI h;
				NI colontmp_;
				NI T9_;
				NI res;
				h = (NI)0;
				colontmp_ = (NI)0;
				nimln_(244, "tables.nim");
				T9_ = (t.data ? (t.data->Sup.len-1) : -1);
				colontmp_ = T9_;
				nimln_(2045, "system.nim");
				res = ((NI) 0);
				{
					nimln_(2046, "system.nim");
					while (1) {
						NI TM_4SoG2KRQy3oMm9aUzSLtGrA_39;
						if (!(res <= colontmp_)) goto LA11;
						nimln_(2047, "system.nim");
						h = res;
						nimln_(245, "tables.nim");
						{
							NIM_BOOL T14_;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							T14_ = (NIM_BOOL)0;
							T14_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
							if (!T14_) goto LA15_;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							key = t.data->data[h].Field1;
							if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
							memcpy((void*)(&val), (NIM_CONST void*)(&t.data->data[h].Field2), sizeof(val));
							nimln_(340, "tables.nim");
							{
								if (!(((NI) 1) < (result ? result->Sup.len : 0))) goto LA19_;
								result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_35));
							}
							LA19_: ;
							nimln_(341, "tables.nim");
							addQuoted_KHwyPEV6PV8Q9aS88ENydhw((&result), key);
							nimln_(342, "tables.nim");
							result = resizeString(result, 2);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_36));
							nimln_(343, "tables.nim");
							addQuoted_UQQwT01he1jqp0OpJpqgzg((&result), val);
						}
						LA15_: ;
						nimln_(2048, "system.nim");
						TM_4SoG2KRQy3oMm9aUzSLtGrA_39 = addInt(res, ((NI) 1));
						res = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_39);
					} LA11: ;
				}
			}
		}
		nimln_(344, "tables.nim");
		result = resizeString(result, 1);
appendString(result, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_38));
	}
	LA1_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, X5BX5D__zcwPTNhPAum8RGgySuB6yw)(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q t, NimStringDesc* key, tyObject_Entry_NdvWyrh1mMPCgDSZoEuCZQ* Result) {
	NI hc;
	NI index;
	nimfr_("[]", "tables.nim");
	chckNil((void*)Result);
	genericReset((void*)Result, (&NTI_NdvWyrh1mMPCgDSZoEuCZQ_));
	hc = (NI)0;
	nimln_(147, "tables.nim");
	index = rawGet_OVftIzDoNNg1ML9adNJj9a2Qtables(t, key, (&hc));
	nimln_(165, "tables.nim");
	{
		nimln_(148, "tables.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)(t.data->Sup.len)) raiseIndexError();
		genericAssign((void*)Result, (void*)(&t.data->data[index].Field2), (&NTI_NdvWyrh1mMPCgDSZoEuCZQ_));
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		nimln_(151, "tables.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(165, "tables.nim");
		T6_ = rawNewString(key->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_11));
appendString(T6_, key);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(151, "tables.nim");
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	popFrame();
}

static N_INLINE(NI, rawGet_9aeDPbhxF26fhAXAucq5Bgw_2tables)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key, NI* hc) {
	NI result;
	NI h;
	NI T5_;
	NI TM_4SoG2KRQy3oMm9aUzSLtGrA_40;
	nimfr_("rawGet", "tableimpl.nim");
{	result = (NI)0;
	nimln_(53, "tableimpl.nim");
	(*hc) = hash_M6zZEYz39abIOUmj0QsNREghashes(key);
	{
		if (!((*hc) == ((NI) 0))) goto LA3_;
		nimln_(45, "tableimpl.nim");
		(*hc) = ((NI) 314159265);
	}
	LA3_: ;
	nimln_(31, "tableimpl.nim");
	nimln_(116, "tables.nim");
	T5_ = (t.data ? (t.data->Sup.len-1) : -1);
	h = (NI)((*hc) & T5_);
	{
		nimln_(32, "tableimpl.nim");
		while (1) {
			NIM_BOOL T8_;
			NI T15_;
			if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
			T8_ = (NIM_BOOL)0;
			T8_ = isFilled_IxXD1UAPoEehVDW9cv9cRaew_2tables(t.data->data[h].Field0);
			if (!T8_) goto LA7;
			nimln_(37, "tableimpl.nim");
			{
				NIM_BOOL T11_;
				T11_ = (NIM_BOOL)0;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field0 == (*hc));
				if (!(T11_)) goto LA12_;
				if ((NU)(h) >= (NU)(t.data->Sup.len)) raiseIndexError();
				T11_ = (t.data->data[h].Field1 == key);
				LA12_: ;
				if (!T11_) goto LA13_;
				nimln_(38, "tableimpl.nim");
				result = h;
				goto BeforeRet_;
			}
			LA13_: ;
			nimln_(39, "tableimpl.nim");
			nimln_(116, "tables.nim");
			T15_ = (t.data ? (t.data->Sup.len-1) : -1);
			h = nextTry_OLPhxSyW9bte5CwHzzQVhfAtables(h, T15_);
		} LA7: ;
	}
	nimln_(40, "tableimpl.nim");
	TM_4SoG2KRQy3oMm9aUzSLtGrA_40 = subInt(((NI) -1), h);
	result = (NI)(TM_4SoG2KRQy3oMm9aUzSLtGrA_40);
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw, X5BX5D__4A4fcN6iwGdI4Dri653RXA)(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A t, NI key) {
	tyObject_AtlasRegion_Ilul4CN69aDnVQVDpHK9a2Aw result;
	NI hc;
	NI index;
	nimfr_("[]", "tables.nim");
	memset((void*)(&result), 0, sizeof(result));
	hc = (NI)0;
	nimln_(147, "tables.nim");
	index = rawGet_9aeDPbhxF26fhAXAucq5Bgw_2tables(t, key, (&hc));
	nimln_(165, "tables.nim");
	{
		nimln_(148, "tables.nim");
		if (!(((NI) 0) <= index)) goto LA3_;
		if ((NU)(index) >= (NU)(t.data->Sup.len)) raiseIndexError();
		result = t.data->data[index].Field2;
	}
	goto LA1_;
	LA3_: ;
	{
		tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg* e;
		NimStringDesc* T6_;
		NimStringDesc* T7_;
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*)0;
		nimln_(2811, "system.nim");
		e = (tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg*) newObj((&NTI_axqhRnwd09cVJkRcojfw6mA_), sizeof(tyObject_KeyError_ifYAhUumNzWR9c9cN9amyJLtg));
		(*e).Sup.Sup.Sup.m_type = (&NTI_ifYAhUumNzWR9c9cN9amyJLtg_);
		nimln_(151, "tables.nim");
		T6_ = (NimStringDesc*)0;
		nimln_(165, "tables.nim");
		T7_ = (NimStringDesc*)0;
		T7_ = nimIntToStr(key);
		T6_ = rawNewString(T7_->Sup.len + 15);
appendString(T6_, ((NimStringDesc*) &TM_4SoG2KRQy3oMm9aUzSLtGrA_11));
appendString(T6_, T7_);
		asgnRefNoCycle((void**) (&(*e).Sup.Sup.message), T6_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e).Sup.Sup.parent), NIM_NIL);
		nimln_(151, "tables.nim");
		raiseException((Exception*)e, "KeyError");
	}
	LA1_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void) {
	nimfr_("tables", "tables.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void) {
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_12[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_13[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_22[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_23[2];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_24[3];
static TNimNode* TM_4SoG2KRQy3oMm9aUzSLtGrA_25[2];
static TNimNode TM_4SoG2KRQy3oMm9aUzSLtGrA_0[21];
NTI_Ye4zca3XfMwtCqFH1n2x5w_.size = sizeof(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w);
NTI_Ye4zca3XfMwtCqFH1n2x5w_.kind = 18;
NTI_Ye4zca3XfMwtCqFH1n2x5w_.base = 0;
NTI_Ye4zca3XfMwtCqFH1n2x5w_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_12[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1];
NTI_w2pkV7dQ2qWCfR34rQj5Qw_.size = sizeof(tyTuple_w2pkV7dQ2qWCfR34rQj5Qw);
NTI_w2pkV7dQ2qWCfR34rQj5Qw_.kind = 18;
NTI_w2pkV7dQ2qWCfR34rQj5Qw_.base = 0;
NTI_w2pkV7dQ2qWCfR34rQj5Qw_.flags = 3;
TM_4SoG2KRQy3oMm9aUzSLtGrA_13[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].offset = offsetof(tyTuple_w2pkV7dQ2qWCfR34rQj5Qw, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[3].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_13[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].offset = offsetof(tyTuple_w2pkV7dQ2qWCfR34rQj5Qw, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].typ = (&NTI_P4w0wnmH7J1IGztO6QfG5A_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[4].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_13[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].offset = offsetof(tyTuple_w2pkV7dQ2qWCfR34rQj5Qw, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[5].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_13[0];
NTI_w2pkV7dQ2qWCfR34rQj5Qw_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[2];
NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_.size = sizeof(tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw*);
NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_.kind = 24;
NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_.base = (&NTI_w2pkV7dQ2qWCfR34rQj5Qw_);
NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_.flags = 2;
NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_.marker = Marker_tySequence_fl4Fl0sjv6wLBM59aA9a59c9aw;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].offset = offsetof(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].typ = (&NTI_fl4Fl0sjv6wLBM59aA9a59c9aw_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[1].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_12[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].offset = offsetof(tyObject_Table_Ye4zca3XfMwtCqFH1n2x5w, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[6].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_12[0];
NTI_Ye4zca3XfMwtCqFH1n2x5w_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[0];
NTI_C80qVni9bN9alMWam2oML36Q_.size = sizeof(tyTuple_C80qVni9bN9alMWam2oML36Q);
NTI_C80qVni9bN9alMWam2oML36Q_.kind = 18;
NTI_C80qVni9bN9alMWam2oML36Q_.base = 0;
TM_4SoG2KRQy3oMm9aUzSLtGrA_22[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].offset = offsetof(tyTuple_C80qVni9bN9alMWam2oML36Q, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[8].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_22[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].offset = offsetof(tyTuple_C80qVni9bN9alMWam2oML36Q, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].typ = (&NTI_77mFvmsOLKik79ci2hXkHEg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[9].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_22[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10];
NTI_s9a6JMyQZ55Jz5fGce9aWo0A_.size = sizeof(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A);
NTI_s9a6JMyQZ55Jz5fGce9aWo0A_.kind = 18;
NTI_s9a6JMyQZ55Jz5fGce9aWo0A_.base = 0;
NTI_s9a6JMyQZ55Jz5fGce9aWo0A_.flags = 2;
TM_4SoG2KRQy3oMm9aUzSLtGrA_23[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12];
NTI_PlkGsuz7STQxey5DAiEKnQ_.size = sizeof(tyTuple_PlkGsuz7STQxey5DAiEKnQ);
NTI_PlkGsuz7STQxey5DAiEKnQ_.kind = 18;
NTI_PlkGsuz7STQxey5DAiEKnQ_.base = 0;
NTI_PlkGsuz7STQxey5DAiEKnQ_.flags = 3;
TM_4SoG2KRQy3oMm9aUzSLtGrA_24[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].offset = offsetof(tyTuple_PlkGsuz7STQxey5DAiEKnQ, Field0);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[14].name = "Field0";
TM_4SoG2KRQy3oMm9aUzSLtGrA_24[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].offset = offsetof(tyTuple_PlkGsuz7STQxey5DAiEKnQ, Field1);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[15].name = "Field1";
TM_4SoG2KRQy3oMm9aUzSLtGrA_24[2] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].offset = offsetof(tyTuple_PlkGsuz7STQxey5DAiEKnQ, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].typ = (&NTI_Ilul4CN69aDnVQVDpHK9a2Aw_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[16].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_24[0];
NTI_PlkGsuz7STQxey5DAiEKnQ_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[13];
NTI_uTDAVJgt4heRKwc9cJkhwhw_.size = sizeof(tySequence_uTDAVJgt4heRKwc9cJkhwhw*);
NTI_uTDAVJgt4heRKwc9cJkhwhw_.kind = 24;
NTI_uTDAVJgt4heRKwc9cJkhwhw_.base = (&NTI_PlkGsuz7STQxey5DAiEKnQ_);
NTI_uTDAVJgt4heRKwc9cJkhwhw_.flags = 2;
NTI_uTDAVJgt4heRKwc9cJkhwhw_.marker = Marker_tySequence_uTDAVJgt4heRKwc9cJkhwhw;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].offset = offsetof(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].typ = (&NTI_uTDAVJgt4heRKwc9cJkhwhw_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[12].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_23[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].offset = offsetof(tyObject_Table_s9a6JMyQZ55Jz5fGce9aWo0A, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[17].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_23[0];
NTI_s9a6JMyQZ55Jz5fGce9aWo0A_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[11];
NTI_VYUBB7iQgr6JV9bHeS0Ht7Q_.size = sizeof(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q);
NTI_VYUBB7iQgr6JV9bHeS0Ht7Q_.kind = 18;
NTI_VYUBB7iQgr6JV9bHeS0Ht7Q_.base = 0;
TM_4SoG2KRQy3oMm9aUzSLtGrA_25[0] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].offset = offsetof(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q, data);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].typ = (&NTI_fQOhtRDCMDpsajodiC1WLg_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[19].name = "data";
TM_4SoG2KRQy3oMm9aUzSLtGrA_25[1] = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].offset = offsetof(tyObject_Table_VYUBB7iQgr6JV9bHeS0Ht7Q, counter);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[20].name = "counter";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].len = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_25[0];
NTI_VYUBB7iQgr6JV9bHeS0Ht7Q_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[18];
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].kind = 1;
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].offset = offsetof(tyTuple_C80qVni9bN9alMWam2oML36Q, Field2);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].typ = (&NTI_NdvWyrh1mMPCgDSZoEuCZQ_);
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[10].name = "Field2";
TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].len = 3; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].kind = 2; TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7].sons = &TM_4SoG2KRQy3oMm9aUzSLtGrA_22[0];
NTI_C80qVni9bN9alMWam2oML36Q_.node = &TM_4SoG2KRQy3oMm9aUzSLtGrA_0[7];
NTI_fQOhtRDCMDpsajodiC1WLg_.size = sizeof(tySequence_fQOhtRDCMDpsajodiC1WLg*);
NTI_fQOhtRDCMDpsajodiC1WLg_.kind = 24;
NTI_fQOhtRDCMDpsajodiC1WLg_.base = (&NTI_C80qVni9bN9alMWam2oML36Q_);
NTI_fQOhtRDCMDpsajodiC1WLg_.marker = Marker_tySequence_fQOhtRDCMDpsajodiC1WLg;
}

