/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\texture.o C:\Users\Desktop-P1NKA\Desktop\nimgame\src\nimcache\texture.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ {
NI width;
NI height;
NU32 handle;
};
typedef NU8 tyEnum_PixelFormat_8J9cBMWJgNNS8b4aTcfFdQg;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ, initTexture_Xt2LvZ6NCFeQAauwyI4Xeg)(NI width, NI height, tyEnum_PixelFormat_8J9cBMWJgNNS8b4aTcfFdQg format, NimStringDesc** data);
N_LIB_PRIVATE N_STDCALL(void, glCreateTextures_wdn3W5Wqz04r5vtCLTtGvQ)(NU32 target, NI32 n, NU32* textures);
N_LIB_PRIVATE N_STDCALL(void, glBindTexture_shJfrHWoymy1BbmsKpC7Xg)(NU32 target, NU32 texture);
N_LIB_PRIVATE N_STDCALL(void, glTexImage2D_G7UzQ8ZECowVV7IoQf5rhg)(NU32 target, NI32 level, NI32 internalformat, NI32 width, NI32 height, NI32 border, NU32 format, NU32 type_0, void* pixels);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_STDCALL(void, glTexParameteri_MG1n9caM41cv9bizyIOehN3g)(NU32 target, NU32 pname, NI32 param);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_rRMR38YRTFk9b55z9cSXatnQ_;
extern TNimType NTI_rR5Bzr1D5krxoo1NcNyeMA_;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_;

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ, initTexture_Xt2LvZ6NCFeQAauwyI4Xeg)(NI width, NI height, tyEnum_PixelFormat_8J9cBMWJgNNS8b4aTcfFdQg format, NimStringDesc** data) {
	tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ result;
	NU32 glFormat;
	NU32 handle;
	nimfr_("initTexture", "texture.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(13, "texture.nim");
	switch (format) {
	case ((tyEnum_PixelFormat_8J9cBMWJgNNS8b4aTcfFdQg) 0):
	{
		glFormat = ((NU32) 6407);
	}
	break;
	case ((tyEnum_PixelFormat_8J9cBMWJgNNS8b4aTcfFdQg) 1):
	{
		glFormat = ((NU32) 6408);
	}
	break;
	}
	handle = (NU32)0;
	nimln_(18, "texture.nim");
	glCreateTextures_wdn3W5Wqz04r5vtCLTtGvQ(((NU32) 3553), ((NI32) 1), (&handle));
	nimln_(19, "texture.nim");
	glBindTexture_shJfrHWoymy1BbmsKpC7Xg(((NU32) 3553), handle);
	nimln_(20, "texture.nim");
	if ((NU)(((NI) 0)) > (NU)((*data)->Sup.len)) raiseIndexError();
	glTexImage2D_G7UzQ8ZECowVV7IoQf5rhg(((NU32) 3553), ((NI32) 0), ((NI32) 6408), ((NI32)chckRange(width, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI32)chckRange(height, ((NI32) (-2147483647 -1)), ((NI32) 2147483647))), ((NI32) 0), glFormat, ((NU32) 5121), ((void*) ((&(*data)->data[((NI) 0)]))));
	nimln_(22, "texture.nim");
	glTexParameteri_MG1n9caM41cv9bizyIOehN3g(((NU32) 3553), ((NU32) 10241), ((NI32) 9728));
	nimln_(23, "texture.nim");
	glTexParameteri_MG1n9caM41cv9bizyIOehN3g(((NU32) 3553), ((NU32) 10240), ((NI32) 9728));
	nimln_(24, "texture.nim");
	glTexParameteri_MG1n9caM41cv9bizyIOehN3g(((NU32) 3553), ((NU32) 10242), ((NI32) 33071));
	nimln_(25, "texture.nim");
	glTexParameteri_MG1n9caM41cv9bizyIOehN3g(((NU32) 3553), ((NU32) 10243), ((NI32) 33071));
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.width = width;
	result.height = height;
	result.handle = handle;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_textureInit000)(void) {
	nimfr_("texture", "texture.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_textureDatInit000)(void) {
static TNimNode* TM_gGbH1PTM41tAbqt1rwyZ9bw_2[3];
static TNimNode TM_gGbH1PTM41tAbqt1rwyZ9bw_0[4];
NTI_rRMR38YRTFk9b55z9cSXatnQ_.size = sizeof(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ);
NTI_rRMR38YRTFk9b55z9cSXatnQ_.kind = 18;
NTI_rRMR38YRTFk9b55z9cSXatnQ_.base = 0;
NTI_rRMR38YRTFk9b55z9cSXatnQ_.flags = 3;
TM_gGbH1PTM41tAbqt1rwyZ9bw_2[0] = &TM_gGbH1PTM41tAbqt1rwyZ9bw_0[1];
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[1].kind = 1;
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[1].offset = offsetof(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ, width);
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[1].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[1].name = "width";
TM_gGbH1PTM41tAbqt1rwyZ9bw_2[1] = &TM_gGbH1PTM41tAbqt1rwyZ9bw_0[2];
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[2].kind = 1;
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[2].offset = offsetof(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ, height);
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[2].typ = (&NTI_rR5Bzr1D5krxoo1NcNyeMA_);
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[2].name = "height";
TM_gGbH1PTM41tAbqt1rwyZ9bw_2[2] = &TM_gGbH1PTM41tAbqt1rwyZ9bw_0[3];
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[3].kind = 1;
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[3].offset = offsetof(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ, handle);
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[3].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[3].name = "handle";
TM_gGbH1PTM41tAbqt1rwyZ9bw_0[0].len = 3; TM_gGbH1PTM41tAbqt1rwyZ9bw_0[0].kind = 2; TM_gGbH1PTM41tAbqt1rwyZ9bw_0[0].sons = &TM_gGbH1PTM41tAbqt1rwyZ9bw_2[0];
NTI_rRMR38YRTFk9b55z9cSXatnQ_.node = &TM_gGbH1PTM41tAbqt1rwyZ9bw_0[0];
}

