/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\affine2.o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\affine2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw;
typedef struct tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w;
typedef NF tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ[3];
typedef tyArray_9ce69c9a1NzlPVqY9aKHS79b5IQ tyArray_lyzHzk9aModN4FAni3DbC4Q[2];
struct tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw {
tyArray_lyzHzk9aModN4FAni3DbC4Q data;
};
struct tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w {
NF x;
NF y;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, createAffine2_HkU9b8hEpERxwbgBWllafBw)(void);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, createTrn_Icnys4pAARytXILfwGowsw)(NF tx, NF ty);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, createScl_84eF6t3Ad7lTYc7g1UlDnA)(NF sx, NF sy);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, createRot_9auw1pzlEje6Bk9aoEPDAzdw)(NF rads);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, product_kOmzNjM3mknBMY9ctOZ2x7Q)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* l, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* r);
N_LIB_PRIVATE N_NIMCALL(NF, det_p9bSgaQ0eMHu6Ykd9cpwd9cug)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, inv_Vcz3Vzqoj8w8Fuc719bvhdQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* m);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, mul_RgJ9a9ayQVggHe2rYxWmgGng)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* other);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, trn_KtcIlianA9cBWtuFxek3DBw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF tx, NF ty);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, scl_QAwj9c14NoZ5U318weiZWZQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF sx, NF sy);
N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, rot_2zuzpUSW5Nm9cVTa5PV7Mjw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF rads);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, apply_p2hhysjrPPCLAqoXUm4Bdw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* m, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
NIM_CONST tyArray_lyzHzk9aModN4FAni3DbC4Q TM_DsiWuGy48krXxtfllLQbKg_2 = {{1.0000000000000000e+000,
0.0,
0.0}
,
{0.0,
1.0000000000000000e+000,
0.0}
}
;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, createAffine2_HkU9b8hEpERxwbgBWllafBw)(void) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("createAffine2", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(9, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	memcpy((void*)result.data, (NIM_CONST void*)TM_DsiWuGy48krXxtfllLQbKg_2, sizeof(tyArray_lyzHzk9aModN4FAni3DbC4Q));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, createTrn_Icnys4pAARytXILfwGowsw)(NF tx, NF ty) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("createTrn", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(15, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.data[0][0] = 1.0000000000000000e+000;
	result.data[0][1] = 0.0;
	result.data[0][2] = tx;
	result.data[1][0] = 0.0;
	result.data[1][1] = 1.0000000000000000e+000;
	result.data[1][2] = ty;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, createScl_84eF6t3Ad7lTYc7g1UlDnA)(NF sx, NF sy) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("createScl", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(21, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.data[0][0] = sx;
	result.data[0][1] = 0.0;
	result.data[0][2] = 0.0;
	result.data[1][0] = 0.0;
	result.data[1][1] = sy;
	result.data[1][2] = 0.0;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, createRot_9auw1pzlEje6Bk9aoEPDAzdw)(NF rads) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	NF c;
	NF s;
	nimfr_("createRot", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(27, "affine2.nim");
	c = cos(rads);
	nimln_(28, "affine2.nim");
	s = sin(rads);
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.data[0][0] = c;
	nimln_(31, "affine2.nim");
	result.data[0][1] = -(s);
	result.data[0][2] = 0.0;
	result.data[1][0] = s;
	result.data[1][1] = c;
	result.data[1][2] = 0.0;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, product_kOmzNjM3mknBMY9ctOZ2x7Q)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* l, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* r) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("product", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(36, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	nimln_(38, "affine2.nim");
	result.data[0][0] = ((NF)(((NF)((*l).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*r).data[(((NI) 0))- 0][(((NI) 0))- 0]))) + (NF)(((NF)((*l).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*r).data[(((NI) 1))- 0][(((NI) 0))- 0]))));
	nimln_(39, "affine2.nim");
	result.data[0][1] = ((NF)(((NF)((*l).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*r).data[(((NI) 0))- 0][(((NI) 1))- 0]))) + (NF)(((NF)((*l).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*r).data[(((NI) 1))- 0][(((NI) 1))- 0]))));
	nimln_(40, "affine2.nim");
	result.data[0][2] = ((NF)(((NF)(((NF)((*l).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*r).data[(((NI) 0))- 0][(((NI) 2))- 0]))) + (NF)(((NF)((*l).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*r).data[(((NI) 1))- 0][(((NI) 2))- 0]))))) + (NF)((*l).data[(((NI) 0))- 0][(((NI) 2))- 0]));
	nimln_(43, "affine2.nim");
	result.data[1][0] = ((NF)(((NF)((*l).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)((*r).data[(((NI) 0))- 0][(((NI) 0))- 0]))) + (NF)(((NF)((*l).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)((*r).data[(((NI) 1))- 0][(((NI) 0))- 0]))));
	nimln_(44, "affine2.nim");
	result.data[1][1] = ((NF)(((NF)((*l).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)((*r).data[(((NI) 0))- 0][(((NI) 1))- 0]))) + (NF)(((NF)((*l).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)((*r).data[(((NI) 1))- 0][(((NI) 1))- 0]))));
	nimln_(45, "affine2.nim");
	result.data[1][2] = ((NF)(((NF)(((NF)((*l).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)((*r).data[(((NI) 0))- 0][(((NI) 2))- 0]))) + (NF)(((NF)((*l).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)((*r).data[(((NI) 1))- 0][(((NI) 2))- 0]))))) + (NF)((*l).data[(((NI) 1))- 0][(((NI) 2))- 0]));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, det_p9bSgaQ0eMHu6Ykd9cpwd9cug)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat) {
	NF result;
	nimfr_("det", "affine2.nim");
{	result = (NF)0;
	nimln_(50, "affine2.nim");
	result = ((NF)(((NF)((*mat).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*mat).data[(((NI) 1))- 0][(((NI) 1))- 0]))) - (NF)(((NF)((*mat).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*mat).data[(((NI) 1))- 0][(((NI) 0))- 0]))));
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, inv_Vcz3Vzqoj8w8Fuc719bvhdQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* m) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	NF det;
	NF invDet;
	nimfr_("inv", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(53, "affine2.nim");
	det = det_p9bSgaQ0eMHu6Ykd9cpwd9cug(m);
	nimln_(54, "affine2.nim");
	invDet = ((NF)(1.0000000000000000e+000) / (NF)(det));
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	nimln_(58, "affine2.nim");
	result.data[0][0] = ((NF)(invDet) * (NF)((*m).data[(((NI) 1))- 0][(((NI) 1))- 0]));
	nimln_(59, "affine2.nim");
	result.data[0][1] = ((NF)(invDet) * (NF)(-((*m).data[(((NI) 0))- 0][(((NI) 1))- 0])));
	nimln_(60, "affine2.nim");
	result.data[0][2] = ((NF)(invDet) * (NF)(((NF)(((NF)((*m).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)((*m).data[(((NI) 1))- 0][(((NI) 2))- 0]))) - (NF)(((NF)((*m).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)((*m).data[(((NI) 0))- 0][(((NI) 2))- 0]))))));
	nimln_(63, "affine2.nim");
	result.data[1][0] = ((NF)(invDet) * (NF)(-((*m).data[(((NI) 1))- 0][(((NI) 0))- 0])));
	nimln_(64, "affine2.nim");
	result.data[1][1] = ((NF)(invDet) * (NF)((*m).data[(((NI) 0))- 0][(((NI) 0))- 0]));
	nimln_(65, "affine2.nim");
	result.data[1][2] = ((NF)(invDet) * (NF)(((NF)(((NF)((*m).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)((*m).data[(((NI) 0))- 0][(((NI) 2))- 0]))) - (NF)(((NF)((*m).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)((*m).data[(((NI) 1))- 0][(((NI) 2))- 0]))))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, mul_RgJ9a9ayQVggHe2rYxWmgGng)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* other) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	nimfr_("mul", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(69, "affine2.nim");
	result = product_kOmzNjM3mknBMY9ctOZ2x7Q(mat, other);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, trn_KtcIlianA9cBWtuFxek3DBw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF tx, NF ty) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T1_;
	nimfr_("trn", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(72, "affine2.nim");
	T1_ = createTrn_Icnys4pAARytXILfwGowsw(tx, ty);
	result = mul_RgJ9a9ayQVggHe2rYxWmgGng(mat, (&T1_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, scl_QAwj9c14NoZ5U318weiZWZQ)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF sx, NF sy) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T1_;
	nimfr_("scl", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(75, "affine2.nim");
	T1_ = createScl_84eF6t3Ad7lTYc7g1UlDnA(sx, sy);
	result = mul_RgJ9a9ayQVggHe2rYxWmgGng(mat, (&T1_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw, rot_2zuzpUSW5Nm9cVTa5PV7Mjw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* mat, NF rads) {
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw result;
	tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw T1_;
	nimfr_("rot", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(78, "affine2.nim");
	T1_ = createRot_9auw1pzlEje6Bk9aoEPDAzdw(rads);
	result = mul_RgJ9a9ayQVggHe2rYxWmgGng(mat, (&T1_));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, apply_p2hhysjrPPCLAqoXUm4Bdw)(tyObject_Affine2_WGoxMDI3T5RNt1Vzmu0Hiw* m, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	nimfr_("apply", "affine2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(81, "affine2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	nimln_(82, "affine2.nim");
	result.x = ((NF)(((NF)(((NF)((*m).data[(((NI) 0))- 0][(((NI) 0))- 0]) * (NF)(v.x))) + (NF)(((NF)((*m).data[(((NI) 0))- 0][(((NI) 1))- 0]) * (NF)(v.y))))) + (NF)((*m).data[(((NI) 0))- 0][(((NI) 2))- 0]));
	nimln_(83, "affine2.nim");
	result.y = ((NF)(((NF)(((NF)((*m).data[(((NI) 1))- 0][(((NI) 0))- 0]) * (NF)(v.x))) + (NF)(((NF)((*m).data[(((NI) 1))- 0][(((NI) 1))- 0]) * (NF)(v.y))))) + (NF)((*m).data[(((NI) 1))- 0][(((NI) 2))- 0]));
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_affine2Init000)(void) {
	nimfr_("affine2", "affine2.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_affine2DatInit000)(void) {
}

