/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\glutils.o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\glutils.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
typedef N_STDCALL_PTR(NU32, tyProc_aFoDQp02eCKmdsvI86zC8w) (void);
typedef NU8 tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg;
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NimStringDesc* tyArray_nHXaesL0DJZHyVS07ARPRA[1];
N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorString_9bNJDp4O36lzEkoOfGxUlJQ)(NU32 err);
N_NIMCALL(NimStringDesc*, copyString)(NimStringDesc* src);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, logErrors_pEaGAU1Kg4UuY0TJsTAPzA)(void);
N_LIB_PRIVATE N_NIMCALL(void, logLoop_Y1QvvdpC0FmKBCafruMWGQ)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(NU32, createShader_2AHO9c5dppd7n465CyKP18A)(NU32 shaderType, NimStringDesc* source);
N_LIB_PRIVATE N_STDCALL(NU32, glCreateShader_9aq2f5W9ciZ4xHTEIXreS9aDQ)(NU32 type_0);
N_LIB_PRIVATE N_NIMCALL(NCSTRING*, allocCStringArray_TEzwlF389aOWujK0ZU6Ck9bA)(NimStringDesc** a, NI aLen_0);
N_LIB_PRIVATE N_STDCALL(void, glShaderSource_ucehHh8g6pBlrLrZtUH9akw)(NU32 shader, NI32 count, NCSTRING* string, NI32* length);
N_LIB_PRIVATE N_STDCALL(void, glCompileShader_fdBHJ8ytQFLIIjstacvOaA)(NU32 shader);
N_LIB_PRIVATE N_STDCALL(void, glGetShaderiv_19a4e9byfNWwyylU9b0x0xEfA)(NU32 shader, NU32 pname, NI32* params);
N_LIB_PRIVATE N_NIMCALL(void, deallocCStringArray_C6iuca1Cowwvc7xYXRiSig)(NCSTRING* a);
N_LIB_PRIVATE N_NIMCALL(void, failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA)(NimStringDesc* msg);
N_LIB_PRIVATE N_NIMCALL(NU32, createProgram_ap6cDX2l6cLS9bixaOW9cplg)(NU32 vertexShader, NU32 fragmentShader);
N_LIB_PRIVATE N_STDCALL(NU32, glCreateProgram_CuMrTzE9cxE5PqEhbYT8FwA)(void);
N_LIB_PRIVATE N_STDCALL(void, glAttachShader_6mrqhfMeT2OBe1X8Rfgbug)(NU32 program, NU32 shader);
N_LIB_PRIVATE N_STDCALL(void, glLinkProgram_bYudX2ps2dTBClLz2NbyzA)(NU32 program);
N_LIB_PRIVATE N_STDCALL(void, glGetProgramiv_Xk3dGZO8OzQ2Ub0o6uNcFg)(NU32 program, NU32 pname, NI32* params);
N_LIB_PRIVATE N_STDCALL(void, glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g)(NI32 n, NU32* buffers);
N_LIB_PRIVATE N_STDCALL(void, glBindBuffer_3rtrqe5eYHMVBLzlqTY63w)(NU32 target, NU32 buffer);
N_LIB_PRIVATE N_STDCALL(void, glBufferData_00Qu57bAXtAMX49bzkHe6aQ)(NU32 target, NI size, void* data, NU32 usage);
N_NIMCALL(NI, mulInt)(NI a, NI b);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern tyProc_aFoDQp02eCKmdsvI86zC8w Dl_179604_;
extern tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level_hzbRBHMSEnpbC61ptpdKmA;
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_2, "GL_NO_ERROR", 11);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_3, "GL_INVALID_ENUM", 15);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_4, "GL_INVALID_VALUE", 16);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_5, "GL_INVALID_OPERATION", 20);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_6, "GL_INVALID_FRAMEBUFFER_OPERATION", 32);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_7, "GL_OUT_OF_MEMORY", 16);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_8, "GL_STACK_UNDERFLOW", 18);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_9, "GL_STACK_OVERFLOW", 17);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_10, "<UNKNOWN GL ERROR>", 18);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_11, "OpenGL error: ", 14);
STRING_LITERAL(TM_6CxAzBupgncqYOUi9bNY3Jw_12, "status == GLint(GL_TRUE) ", 25);

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, errorString_9bNJDp4O36lzEkoOfGxUlJQ)(NU32 err) {
	NimStringDesc* result;
	nimfr_("errorString", "glutils.nim");
	result = (NimStringDesc*)0;
	nimln_(5, "glutils.nim");
	switch (err) {
	case ((NU32) 0):
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_2));
	}
	break;
	case ((NU32) 1280):
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_3));
	}
	break;
	case ((NU32) 1281):
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_4));
	}
	break;
	case ((NU32) 1282):
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_5));
	}
	break;
	case ((NU32) 1286):
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_6));
	}
	break;
	case ((NU32) 1285):
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_7));
	}
	break;
	case ((NU32) 1284):
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_8));
	}
	break;
	case ((NU32) 1283):
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_9));
	}
	break;
	default:
	{
		result = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_10));
	}
	break;
	}
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, logErrors_pEaGAU1Kg4UuY0TJsTAPzA)(void) {
	nimfr_("logErrors", "glutils.nim");
	{
		NU32 err;
		NU32 err_2;
		err = (NU32)0;
		nimln_(17, "glutils.nim");
		err_2 = Dl_179604_();
		{
			nimln_(18, "glutils.nim");
			while (1) {
				nimln_(398, "system.nim");
				nimln_(18, "glutils.nim");
				if (!!((err_2 == ((NU32) 0)))) goto LA3;
				nimln_(19, "glutils.nim");
				err = err_2;
				nimln_(24, "glutils.nim");
				{
					tyArray_Re75IspeoxXy2oCZHwcRrA T8_;
					nimln_(295, "logging.nim");
					if (!(level_hzbRBHMSEnpbC61ptpdKmA <= ((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 4))) goto LA6_;
					nimln_(326, "logging.nim");
					memset((void*)T8_, 0, sizeof(T8_));
					T8_[0] = copyString(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_11));
					nimln_(24, "glutils.nim");
					T8_[1] = errorString_9bNJDp4O36lzEkoOfGxUlJQ(err);
					logLoop_Y1QvvdpC0FmKBCafruMWGQ(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 4), T8_, 2);
				}
				LA6_: ;
				nimln_(20, "glutils.nim");
				err_2 = Dl_179604_();
			} LA3: ;
		}
	}
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(NU32, createShader_2AHO9c5dppd7n465CyKP18A)(NU32 shaderType, NimStringDesc* source) {
	NU32 result;
	NU32 shader;
	NCSTRING* source_2;
	tyArray_nHXaesL0DJZHyVS07ARPRA T1_;
	NI32 status;
	nimfr_("createShader", "glutils.nim");
{	result = (NU32)0;
	nimln_(34, "glutils.nim");
	shader = glCreateShader_9aq2f5W9ciZ4xHTEIXreS9aDQ(shaderType);
	nimln_(35, "glutils.nim");
	memset((void*)T1_, 0, sizeof(T1_));
	T1_[0] = copyString(source);
	source_2 = allocCStringArray_TEzwlF389aOWujK0ZU6Ck9bA(T1_, 1);
	status = (NI32)0;
	nimln_(38, "glutils.nim");
	glShaderSource_ucehHh8g6pBlrLrZtUH9akw(shader, ((NI32) 1), source_2, NIM_NIL);
	nimln_(39, "glutils.nim");
	glCompileShader_fdBHJ8ytQFLIIjstacvOaA(shader);
	nimln_(40, "glutils.nim");
	glGetShaderiv_19a4e9byfNWwyylU9b0x0xEfA(shader, ((NU32) 35713), (&status));
	nimln_(42, "glutils.nim");
	deallocCStringArray_C6iuca1Cowwvc7xYXRiSig(source_2);
	nimln_(43, "glutils.nim");
	{
		if (!!((status == ((NI32) 1)))) goto LA4_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_12));
	}
	LA4_: ;
	nimln_(44, "glutils.nim");
	result = shader;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU32, createProgram_ap6cDX2l6cLS9bixaOW9cplg)(NU32 vertexShader, NU32 fragmentShader) {
	NU32 result;
	NU32 program;
	NI32 status;
	nimfr_("createProgram", "glutils.nim");
{	result = (NU32)0;
	nimln_(47, "glutils.nim");
	program = glCreateProgram_CuMrTzE9cxE5PqEhbYT8FwA();
	status = (NI32)0;
	nimln_(50, "glutils.nim");
	glAttachShader_6mrqhfMeT2OBe1X8Rfgbug(program, vertexShader);
	nimln_(51, "glutils.nim");
	glAttachShader_6mrqhfMeT2OBe1X8Rfgbug(program, fragmentShader);
	nimln_(52, "glutils.nim");
	glLinkProgram_bYudX2ps2dTBClLz2NbyzA(program);
	nimln_(54, "glutils.nim");
	glGetProgramiv_Xk3dGZO8OzQ2Ub0o6uNcFg(program, ((NU32) 35714), (&status));
	nimln_(56, "glutils.nim");
	{
		if (!!((status == ((NI32) 1)))) goto LA3_;
		failedAssertImpl_aDmpBTs9cPuXp0Mp9cfiNeyA(((NimStringDesc*) &TM_6CxAzBupgncqYOUi9bNY3Jw_12));
	}
	LA3_: ;
	nimln_(57, "glutils.nim");
	result = program;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU32, makeVbo_19cMypki1TDjfDJ6InDUeaw)(NF32* data, NI dataLen_0, NU32 usage) {
	NU32 result;
	NU32 buff;
	NI TM_6CxAzBupgncqYOUi9bNY3Jw_13;
	nimfr_("makeVbo", "glutils.nim");
{	result = (NU32)0;
	buff = (NU32)0;
	nimln_(28, "glutils.nim");
	glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g(((NI32) 1), (&buff));
	nimln_(5214, "opengl.nim");
	glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), buff);
	nimln_(30, "glutils.nim");
	TM_6CxAzBupgncqYOUi9bNY3Jw_13 = mulInt(dataLen_0, ((NI) 4));
	glBufferData_00Qu57bAXtAMX49bzkHe6aQ(((NU32) 34962), (NI)(TM_6CxAzBupgncqYOUi9bNY3Jw_13), NIM_NIL, usage);
	nimln_(31, "glutils.nim");
	result = buff;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NU32, makeVbo_BgyX5TYbUOhVcBnHDSpA1g)(NU8* data, NI dataLen_0, NU32 usage) {
	NU32 result;
	NU32 buff;
	NI TM_6CxAzBupgncqYOUi9bNY3Jw_14;
	nimfr_("makeVbo", "glutils.nim");
{	result = (NU32)0;
	buff = (NU32)0;
	nimln_(28, "glutils.nim");
	glGenBuffers_B9ax9aWnWORHtXpch5OZqE6g(((NI32) 1), (&buff));
	nimln_(5214, "opengl.nim");
	glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), buff);
	nimln_(30, "glutils.nim");
	TM_6CxAzBupgncqYOUi9bNY3Jw_14 = mulInt(dataLen_0, ((NI) 1));
	glBufferData_00Qu57bAXtAMX49bzkHe6aQ(((NU32) 34962), (NI)(TM_6CxAzBupgncqYOUi9bNY3Jw_14), NIM_NIL, usage);
	nimln_(31, "glutils.nim");
	result = buff;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_glutilsInit000)(void) {
	nimfr_("glutils", "glutils.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_glutilsDatInit000)(void) {
}

