/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\spritebatch.o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\spritebatch.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg;
typedef struct tyObject_Program_5U307oTET301CaFCP809big tyObject_Program_5U307oTET301CaFCP809big;
typedef struct tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw;
typedef struct tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ;
typedef struct tyTuple_2U9aQqMEBcSEoidI9cRa4P0A tyTuple_2U9aQqMEBcSEoidI9cRa4P0A;
typedef struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef NF32 tyArray_oyZrYU9bPA1n9b1MM23cnzzQ[12288];
typedef NU8 tyArray_tWovyCrDXxvtzvQ5q9awdWA[24576];
struct tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw {
NI32 coords;
NI32 colors;
NI32 tex_coords;
NI32 texture;
};
struct tyObject_Program_5U307oTET301CaFCP809big {
NU32 handle;
tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw locations;
};
struct tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg {
NI coordIdx;
NI colorIdx;
NI texCoordIdx;
tyArray_oyZrYU9bPA1n9b1MM23cnzzQ coordData;
tyArray_tWovyCrDXxvtzvQ5q9awdWA colorData;
tyArray_oyZrYU9bPA1n9b1MM23cnzzQ texCoordData;
NU32 coordBuff;
NU32 colorBuff;
NU32 texCoordBuff;
tyObject_Program_5U307oTET301CaFCP809big program;
NU32 lastTexHandle;
};
struct tyTuple_2U9aQqMEBcSEoidI9cRa4P0A {
NF32 Field0;
NF32 Field1;
};
struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ {
NI width;
NI height;
NU32 handle;
};
struct tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ {
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ texture;
NF u0;
NF v0;
NF u1;
NF v1;
};
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg, newSpriteBatch_Rx4s9cI3qy4Qwal5QjiqUBw)(tyObject_Program_5U307oTET301CaFCP809big program);
N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_NIMCALL(NU32, makeVbo_19cMypki1TDjfDJ6InDUeaw)(NF32* data, NI dataLen_0, NU32 usage);
N_LIB_PRIVATE N_NIMCALL(NU32, makeVbo_BgyX5TYbUOhVcBnHDSpA1g)(NU8* data, NI dataLen_0, NU32 usage);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(void, pushCoord_rWY5hfKDJ5nUzCfafTrWww)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NF32 x, NF32 y);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_NOINLINE(void, raiseIndexError)(void);
N_LIB_PRIVATE N_NIMCALL(void, pushColor_UGVLPOtXjGhsMJEIckr1uQ)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NU8 r, NU8 g, NU8 b, NU8 a);
N_LIB_PRIVATE N_NIMCALL(void, pushTexCoord_j6cjWlq1IbBd6e8gADiUgw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NF32 u, NF32 v);
N_LIB_PRIVATE N_NIMCALL(void, flush_GHonqE9aQDzibr6yQNKdk3A)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch);
N_LIB_PRIVATE N_STDCALL(void, glBindBuffer_3rtrqe5eYHMVBLzlqTY63w)(NU32 target, NU32 buffer);
N_LIB_PRIVATE N_STDCALL(void, glBufferSubData_ZuBlSQcG0v7PWXIwsqHIEQ)(NU32 target, NI offset, NI size, void* data);
N_NIMCALL(NI, mulInt)(NI a, NI b);
N_LIB_PRIVATE N_STDCALL(void, glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA)(NU32 index);
N_LIB_PRIVATE N_STDCALL(void, glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww)(NU32 index, NI32 size, NU32 type_0, NIM_BOOL normalized, NI32 stride, void* pointer);
N_LIB_PRIVATE N_STDCALL(void, glUseProgram_bYudX2ps2dTBClLz2NbyzA_2)(NU32 program);
N_LIB_PRIVATE N_STDCALL(void, glUniform1i_JXFx8pP9cft9ayhvOovLEZsg)(NI32 location, NI32 v0);
N_LIB_PRIVATE N_STDCALL(void, glDrawArrays_Bw7cKcZtx9bAbZdj5Iw9af9ag)(NU32 mode, NI32 first, NI32 count);
static N_INLINE(NI, divInt)(NI a, NI b);
N_NOINLINE(void, raiseDivByZero)(void);
static N_INLINE(NI, chckRange)(NI i, NI a, NI b);
N_NOINLINE(void, raiseRangeError)(NI64 val);
N_LIB_PRIVATE N_NIMCALL(void, draw_2FrjBHe3tWgCd1N7e15eHw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ* reg, NF x, NF y, NF w, NF h);
N_LIB_PRIVATE N_STDCALL(void, glBindTexture_shJfrHWoymy1BbmsKpC7Xg)(NU32 target, NU32 texture);
N_LIB_PRIVATE N_NIMCALL(void, draw_NIwQSRD025UZcYXZogXm6g)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NF x, NF y, NF width, NF height);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ, makeTextureRegion_10Ua2psAivWdjmRBQsvDtA)(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NI x, NI y, NI width, NI height);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
TNimType NTI_5U307oTET301CaFCP809big_;
extern TNimType NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_;
TNimType NTI_w5LtLI9bobxLoIavQIQCGAw_;
extern TNimType NTI_sVg18TP9cLifHyygRe9cro9aA_;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg, newSpriteBatch_Rx4s9cI3qy4Qwal5QjiqUBw)(tyObject_Program_5U307oTET301CaFCP809big program) {
	tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg result;
	tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg batch;
	nimfr_("newSpriteBatch", "spritebatch.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(37, "spritebatch.nim");
	chckNil((void*)(&batch));
	memset((void*)(&batch), 0, sizeof(batch));
	nimln_(38, "spritebatch.nim");
	batch.coordBuff = makeVbo_19cMypki1TDjfDJ6InDUeaw(batch.coordData, 12288, ((NU32) 35048));
	nimln_(39, "spritebatch.nim");
	batch.colorBuff = makeVbo_BgyX5TYbUOhVcBnHDSpA1g(batch.colorData, 24576, ((NU32) 35048));
	nimln_(40, "spritebatch.nim");
	batch.texCoordBuff = makeVbo_19cMypki1TDjfDJ6InDUeaw(batch.texCoordData, 12288, ((NU32) 35048));
	nimln_(41, "spritebatch.nim");
	batch.program = program;
	nimln_(42, "spritebatch.nim");
	result = batch;
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, pushCoord_rWY5hfKDJ5nUzCfafTrWww)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NF32 x, NF32 y) {
	NI TM_DRmnSAPZdQrD3q2oC62tTA_2;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_3;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_4;
	nimfr_("pushCoord", "spritebatch.nim");
	nimln_(45, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_2 = addInt((*batch).coordIdx, ((NI) 0));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_2)) > (NU)(12287)) raiseIndexError();
	(*batch).coordData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_2))- 0] = x;
	nimln_(46, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_3 = addInt((*batch).coordIdx, ((NI) 1));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_3)) > (NU)(12287)) raiseIndexError();
	(*batch).coordData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_3))- 0] = y;
	nimln_(47, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_4 = addInt((*batch).coordIdx, ((NI) 2));
	(*batch).coordIdx = (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_4);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, pushColor_UGVLPOtXjGhsMJEIckr1uQ)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NU8 r, NU8 g, NU8 b, NU8 a) {
	NI TM_DRmnSAPZdQrD3q2oC62tTA_5;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_6;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_7;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_8;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_9;
	nimfr_("pushColor", "spritebatch.nim");
	nimln_(50, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_5 = addInt((*batch).colorIdx, ((NI) 0));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_5)) > (NU)(24575)) raiseIndexError();
	(*batch).colorData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_5))- 0] = r;
	nimln_(51, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_6 = addInt((*batch).colorIdx, ((NI) 1));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_6)) > (NU)(24575)) raiseIndexError();
	(*batch).colorData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_6))- 0] = g;
	nimln_(52, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_7 = addInt((*batch).colorIdx, ((NI) 2));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_7)) > (NU)(24575)) raiseIndexError();
	(*batch).colorData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_7))- 0] = b;
	nimln_(53, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_8 = addInt((*batch).colorIdx, ((NI) 3));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_8)) > (NU)(24575)) raiseIndexError();
	(*batch).colorData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_8))- 0] = a;
	nimln_(54, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_9 = addInt((*batch).colorIdx, ((NI) 4));
	(*batch).colorIdx = (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_9);
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, pushTexCoord_j6cjWlq1IbBd6e8gADiUgw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, NF32 u, NF32 v) {
	NI TM_DRmnSAPZdQrD3q2oC62tTA_10;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_11;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_12;
	nimfr_("pushTexCoord", "spritebatch.nim");
	nimln_(57, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_10 = addInt((*batch).texCoordIdx, ((NI) 0));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_10)) > (NU)(12287)) raiseIndexError();
	(*batch).texCoordData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_10))- 0] = u;
	nimln_(58, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_11 = addInt((*batch).texCoordIdx, ((NI) 1));
	if ((NU)((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_11)) > (NU)(12287)) raiseIndexError();
	(*batch).texCoordData[((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_11))- 0] = v;
	nimln_(59, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_12 = addInt((*batch).texCoordIdx, ((NI) 2));
	(*batch).texCoordIdx = (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_12);
	popFrame();
}

static N_INLINE(NI, divInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		if (!(b == ((NI) 0))) goto LA3_;
		raiseDivByZero();
	}
	LA3_: ;
	{
		NIM_BOOL T7_;
		T7_ = (NIM_BOOL)0;
		T7_ = (a == ((NI) (IL64(-9223372036854775807) - IL64(1))));
		if (!(T7_)) goto LA8_;
		T7_ = (b == ((NI) -1));
		LA8_: ;
		if (!T7_) goto LA9_;
		raiseOverflow();
	}
	LA9_: ;
	result = (NI)(a / b);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NI, chckRange)(NI i, NI a, NI b) {
	NI result;
{	result = (NI)0;
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (a <= i);
		if (!(T3_)) goto LA4_;
		T3_ = (i <= b);
		LA4_: ;
		if (!T3_) goto LA5_;
		result = i;
		goto BeforeRet_;
	}
	goto LA1_;
	LA5_: ;
	{
		raiseRangeError(((NI64) (i)));
	}
	LA1_: ;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, flush_GHonqE9aQDzibr6yQNKdk3A)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch) {
	tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw* locs;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_13;
	NI TM_DRmnSAPZdQrD3q2oC62tTA_15;
	nimfr_("flush", "spritebatch.nim");
{	nimln_(62, "spritebatch.nim");
	{
		if (!((*batch).coordIdx == ((NI) 0))) goto LA3_;
		nimln_(63, "spritebatch.nim");
		goto BeforeRet_;
	}
	LA3_: ;
	nimln_(65, "spritebatch.nim");
	locs = (&(*batch).program.locations);
	nimln_(67, "spritebatch.nim");
	glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), (*batch).coordBuff);
	nimln_(68, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_13 = mulInt((*batch).coordIdx, ((NI) 4));
	glBufferSubData_ZuBlSQcG0v7PWXIwsqHIEQ(((NU32) 34962), ((NI) 0), (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_13), ((void*) ((*batch).coordData)));
	nimln_(69, "spritebatch.nim");
	glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(((NU32) ((*locs).coords)));
	nimln_(70, "spritebatch.nim");
	glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(((NU32) ((*locs).coords)), ((NI32) 2), ((NU32) 5126), NIM_FALSE, ((NI32) 0), NIM_NIL);
	nimln_(72, "spritebatch.nim");
	{
		nimln_(398, "system.nim");
		nimln_(72, "spritebatch.nim");
		if (!!(((*locs).colors == ((NI32) -1)))) goto LA7_;
		nimln_(73, "spritebatch.nim");
		glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), (*batch).colorBuff);
		nimln_(74, "spritebatch.nim");
		glBufferSubData_ZuBlSQcG0v7PWXIwsqHIEQ(((NU32) 34962), ((NI) 0), (*batch).colorIdx, ((void*) ((*batch).colorData)));
		nimln_(75, "spritebatch.nim");
		glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(((NU32) ((*locs).colors)));
		nimln_(76, "spritebatch.nim");
		glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(((NU32) ((*locs).colors)), ((NI32) 4), ((NU32) 5121), NIM_TRUE, ((NI32) 0), NIM_NIL);
	}
	LA7_: ;
	nimln_(78, "spritebatch.nim");
	{
		NI TM_DRmnSAPZdQrD3q2oC62tTA_14;
		nimln_(398, "system.nim");
		nimln_(78, "spritebatch.nim");
		if (!!(((*locs).tex_coords == ((NI32) -1)))) goto LA11_;
		nimln_(79, "spritebatch.nim");
		glBindBuffer_3rtrqe5eYHMVBLzlqTY63w(((NU32) 34962), (*batch).texCoordBuff);
		nimln_(80, "spritebatch.nim");
		TM_DRmnSAPZdQrD3q2oC62tTA_14 = mulInt((*batch).texCoordIdx, ((NI) 4));
		glBufferSubData_ZuBlSQcG0v7PWXIwsqHIEQ(((NU32) 34962), ((NI) 0), (NI)(TM_DRmnSAPZdQrD3q2oC62tTA_14), ((void*) ((*batch).texCoordData)));
		nimln_(81, "spritebatch.nim");
		glEnableVertexAttribArray_PNXJR7G6JIj9ajx7Tvz9a1RA(((NU32) ((*locs).tex_coords)));
		nimln_(82, "spritebatch.nim");
		glVertexAttribPointer_ARjPQ9cnPkJQtADdR9bd9a8Ww(((NU32) ((*locs).tex_coords)), ((NI32) 2), ((NU32) 5126), NIM_FALSE, ((NI32) 0), NIM_NIL);
	}
	LA11_: ;
	nimln_(84, "spritebatch.nim");
	glUseProgram_bYudX2ps2dTBClLz2NbyzA_2((*batch).program.handle);
	nimln_(85, "spritebatch.nim");
	glUniform1i_JXFx8pP9cft9ayhvOovLEZsg((*locs).texture, ((NI32) 0));
	nimln_(86, "spritebatch.nim");
	TM_DRmnSAPZdQrD3q2oC62tTA_15 = divInt((*batch).coordIdx, ((NI) 2));
	glDrawArrays_Bw7cKcZtx9bAbZdj5Iw9af9ag(((NU32) 4), ((NI32) 0), ((NI32)chckRange((NI)(TM_DRmnSAPZdQrD3q2oC62tTA_15), ((NI32) (-2147483647 -1)), ((NI32) 2147483647))));
	nimln_(88, "spritebatch.nim");
	(*batch).coordIdx = ((NI) 0);
	nimln_(89, "spritebatch.nim");
	(*batch).colorIdx = ((NI) 0);
	nimln_(90, "spritebatch.nim");
	(*batch).texCoordIdx = ((NI) 0);
	}BeforeRet_: ;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_2FrjBHe3tWgCd1N7e15eHw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ* reg, NF x, NF y, NF w, NF h) {
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T1_;
	NF32 x0;
	NF32 y0;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T2_;
	NF32 x1;
	NF32 y1;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T3_;
	NF32 x2;
	NF32 y2;
	tyTuple_2U9aQqMEBcSEoidI9cRa4P0A T4_;
	NF32 x3;
	NF32 y3;
	nimfr_("draw", "spritebatch.nim");
	nimln_(93, "spritebatch.nim");
	T1_.Field0 = ((NF32) (x));
	T1_.Field1 = ((NF32) (y));
	x0 = T1_.Field0;
	y0 = T1_.Field1;
	nimln_(94, "spritebatch.nim");
	T2_.Field0 = ((NF32) (((NF)(x) + (NF)(w))));
	T2_.Field1 = ((NF32) (y));
	x1 = T2_.Field0;
	y1 = T2_.Field1;
	nimln_(95, "spritebatch.nim");
	T3_.Field0 = ((NF32) (((NF)(x) + (NF)(w))));
	T3_.Field1 = ((NF32) (((NF)(y) + (NF)(h))));
	x2 = T3_.Field0;
	y2 = T3_.Field1;
	nimln_(96, "spritebatch.nim");
	T4_.Field0 = ((NF32) (x));
	T4_.Field1 = ((NF32) (((NF)(y) + (NF)(h))));
	x3 = T4_.Field0;
	y3 = T4_.Field1;
	nimln_(98, "spritebatch.nim");
	{
		nimln_(398, "system.nim");
		nimln_(98, "spritebatch.nim");
		if (!!(((*reg).texture.handle == (*batch).lastTexHandle))) goto LA7_;
		nimln_(99, "spritebatch.nim");
		flush_GHonqE9aQDzibr6yQNKdk3A(batch);
		nimln_(100, "spritebatch.nim");
		(*batch).lastTexHandle = (*reg).texture.handle;
		nimln_(101, "spritebatch.nim");
		glBindTexture_shJfrHWoymy1BbmsKpC7Xg(((NU32) 3553), (*reg).texture.handle);
	}
	LA7_: ;
	nimln_(103, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x0, y0);
	nimln_(104, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(105, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v0)));
	nimln_(107, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x1, y1);
	nimln_(108, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(109, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v0)));
	nimln_(111, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x2, y2);
	nimln_(112, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(113, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v1)));
	nimln_(115, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x2, y2);
	nimln_(116, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(117, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u1)), ((NF32) ((*reg).v1)));
	nimln_(119, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x3, y3);
	nimln_(120, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(121, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v1)));
	nimln_(123, "spritebatch.nim");
	pushCoord_rWY5hfKDJ5nUzCfafTrWww(batch, x0, y0);
	nimln_(124, "spritebatch.nim");
	pushColor_UGVLPOtXjGhsMJEIckr1uQ(batch, ((NU8) 255), ((NU8) 255), ((NU8) 255), ((NU8) 255));
	nimln_(125, "spritebatch.nim");
	pushTexCoord_j6cjWlq1IbBd6e8gADiUgw(batch, ((NF32) ((*reg).u0)), ((NF32) ((*reg).v0)));
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(void, draw_NIwQSRD025UZcYXZogXm6g)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NF x, NF y, NF width, NF height) {
	tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ T1_;
	nimfr_("draw", "spritebatch.nim");
	nimln_(128, "spritebatch.nim");
	T1_ = makeTextureRegion_10Ua2psAivWdjmRBQsvDtA(tex, ((NI) 0), ((NI) 0), tex.width, tex.height);
	draw_2FrjBHe3tWgCd1N7e15eHw(batch, (&T1_), x, y, width, height);
	popFrame();
}
NIM_EXTERNC N_NOINLINE(void, unknown_spritebatchInit000)(void) {
	nimfr_("spritebatch", "spritebatch.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_spritebatchDatInit000)(void) {
static TNimNode* TM_DRmnSAPZdQrD3q2oC62tTA_16[2];
static TNimNode* TM_DRmnSAPZdQrD3q2oC62tTA_17[4];
static TNimNode TM_DRmnSAPZdQrD3q2oC62tTA_0[8];
NTI_5U307oTET301CaFCP809big_.size = sizeof(tyObject_Program_5U307oTET301CaFCP809big);
NTI_5U307oTET301CaFCP809big_.kind = 18;
NTI_5U307oTET301CaFCP809big_.base = 0;
NTI_5U307oTET301CaFCP809big_.flags = 3;
TM_DRmnSAPZdQrD3q2oC62tTA_16[0] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[1];
TM_DRmnSAPZdQrD3q2oC62tTA_0[1].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[1].offset = offsetof(tyObject_Program_5U307oTET301CaFCP809big, handle);
TM_DRmnSAPZdQrD3q2oC62tTA_0[1].typ = (&NTI_JrFyJbYm9b5I4hJ9cWDqvfYA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[1].name = "handle";
TM_DRmnSAPZdQrD3q2oC62tTA_16[1] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[2];
NTI_w5LtLI9bobxLoIavQIQCGAw_.size = sizeof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw);
NTI_w5LtLI9bobxLoIavQIQCGAw_.kind = 18;
NTI_w5LtLI9bobxLoIavQIQCGAw_.base = 0;
NTI_w5LtLI9bobxLoIavQIQCGAw_.flags = 3;
TM_DRmnSAPZdQrD3q2oC62tTA_17[0] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[4];
TM_DRmnSAPZdQrD3q2oC62tTA_0[4].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[4].offset = offsetof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, coords);
TM_DRmnSAPZdQrD3q2oC62tTA_0[4].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[4].name = "coords";
TM_DRmnSAPZdQrD3q2oC62tTA_17[1] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[5];
TM_DRmnSAPZdQrD3q2oC62tTA_0[5].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[5].offset = offsetof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, colors);
TM_DRmnSAPZdQrD3q2oC62tTA_0[5].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[5].name = "colors";
TM_DRmnSAPZdQrD3q2oC62tTA_17[2] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[6];
TM_DRmnSAPZdQrD3q2oC62tTA_0[6].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[6].offset = offsetof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, tex_coords);
TM_DRmnSAPZdQrD3q2oC62tTA_0[6].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[6].name = "tex_coords";
TM_DRmnSAPZdQrD3q2oC62tTA_17[3] = &TM_DRmnSAPZdQrD3q2oC62tTA_0[7];
TM_DRmnSAPZdQrD3q2oC62tTA_0[7].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[7].offset = offsetof(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, texture);
TM_DRmnSAPZdQrD3q2oC62tTA_0[7].typ = (&NTI_sVg18TP9cLifHyygRe9cro9aA_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[7].name = "texture";
TM_DRmnSAPZdQrD3q2oC62tTA_0[3].len = 4; TM_DRmnSAPZdQrD3q2oC62tTA_0[3].kind = 2; TM_DRmnSAPZdQrD3q2oC62tTA_0[3].sons = &TM_DRmnSAPZdQrD3q2oC62tTA_17[0];
NTI_w5LtLI9bobxLoIavQIQCGAw_.node = &TM_DRmnSAPZdQrD3q2oC62tTA_0[3];
TM_DRmnSAPZdQrD3q2oC62tTA_0[2].kind = 1;
TM_DRmnSAPZdQrD3q2oC62tTA_0[2].offset = offsetof(tyObject_Program_5U307oTET301CaFCP809big, locations);
TM_DRmnSAPZdQrD3q2oC62tTA_0[2].typ = (&NTI_w5LtLI9bobxLoIavQIQCGAw_);
TM_DRmnSAPZdQrD3q2oC62tTA_0[2].name = "locations";
TM_DRmnSAPZdQrD3q2oC62tTA_0[0].len = 2; TM_DRmnSAPZdQrD3q2oC62tTA_0[0].kind = 2; TM_DRmnSAPZdQrD3q2oC62tTA_0[0].sons = &TM_DRmnSAPZdQrD3q2oC62tTA_16[0];
NTI_5U307oTET301CaFCP809big_.node = &TM_DRmnSAPZdQrD3q2oC62tTA_0[0];
}

