/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\test.o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\test.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <stdio.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct Exception Exception;
typedef struct TNimType TNimType;
typedef struct TNimNode TNimNode;
typedef struct RootObj RootObj;
typedef struct NimStringDesc NimStringDesc;
typedef struct TGenericSeq TGenericSeq;
typedef struct tySequence_uB9b75OUPRENsBAu4AnoePA tySequence_uB9b75OUPRENsBAu4AnoePA;
typedef struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g;
typedef struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w;
typedef struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ;
typedef struct tyObject_GcStack_7fytPA5bBsob6See21YMRA tyObject_GcStack_7fytPA5bBsob6See21YMRA;
typedef struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg;
typedef struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ;
typedef struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg;
typedef struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw;
typedef struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA;
typedef struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw;
typedef struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw;
typedef struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg;
typedef struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyTuple_ujsjpB2O9cjj3uDHsXbnSzg;
typedef struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg;
typedef struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ;
typedef struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg;
typedef struct tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug;
typedef struct tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA;
typedef struct tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw;
typedef struct tyObject_Program_5U307oTET301CaFCP809big tyObject_Program_5U307oTET301CaFCP809big;
typedef struct tyObject_PNGResultcolonObjectType__UGj0Wf0n6sttZ5gHuJqzug tyObject_PNGResultcolonObjectType__UGj0Wf0n6sttZ5gHuJqzug;
typedef struct tyObject_PNGDecodercolonObjectType__YCEZFAllgHMittYhSqWqEQ tyObject_PNGDecodercolonObjectType__YCEZFAllgHMittYhSqWqEQ;
typedef struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ;
typedef struct tySequence_54FDWV4H446H3czolNxQbA tySequence_54FDWV4H446H3czolNxQbA;
typedef struct tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg;
typedef struct tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ;
typedef struct tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw;
typedef struct tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw;
typedef struct tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw;
typedef struct tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ;
typedef struct tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg;
typedef struct tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q;
typedef struct tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA;
typedef struct tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw;
typedef struct tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ;
typedef struct tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ;
typedef struct tyObject_PNGStandarRGBcolonObjectType__19ah8rXfRZMmdCeZoOyE8Hw tyObject_PNGStandarRGBcolonObjectType__19ah8rXfRZMmdCeZoOyE8Hw;
typedef struct tyObject_PNGHistcolonObjectType__LT7Y9a9bsqO6qiFWdeftE0WA tyObject_PNGHistcolonObjectType__LT7Y9a9bsqO6qiFWdeftE0WA;
typedef struct tyObject_PNGSPalettecolonObjectType__IQbkgmOSGm6kEHaEfeltDw tyObject_PNGSPalettecolonObjectType__IQbkgmOSGm6kEHaEfeltDw;
typedef struct tyObject_PNGSbitcolonObjectType__hMHzmPmnYaDDKI81MPfelQ tyObject_PNGSbitcolonObjectType__hMHzmPmnYaDDKI81MPfelQ;
typedef struct tyObject_APNGFrameDatacolonObjectType__R7Jw9cl9cQmf0yjLYX7u8kxw tyObject_APNGFrameDatacolonObjectType__R7Jw9cl9cQmf0yjLYX7u8kxw;
typedef struct tyObject_PNGGammacolonObjectType__UDHAj9c34pyOZKEGUUayLSg tyObject_PNGGammacolonObjectType__UDHAj9c34pyOZKEGUUayLSg;
typedef struct tyObject_APNGAnimationControlcolonObjectType__wnKS2ux9aN2yCglvRsRiPrQ tyObject_APNGAnimationControlcolonObjectType__wnKS2ux9aN2yCglvRsRiPrQ;
typedef struct tyObject_PNGChromacolonObjectType__oJWRCuC12OxkSgyxp4G6Aw tyObject_PNGChromacolonObjectType__oJWRCuC12OxkSgyxp4G6Aw;
typedef struct tyObject_PNGPalettecolonObjectType__EliRKtUsLlyl0DkfPoJTCw tyObject_PNGPalettecolonObjectType__EliRKtUsLlyl0DkfPoJTCw;
typedef struct tyObject_PNGBackgroundcolonObjectType__29bWwuvCwJ8KaXreO9bPK09cw tyObject_PNGBackgroundcolonObjectType__29bWwuvCwJ8KaXreO9bPK09cw;
typedef struct tyObject_PNGTranscolonObjectType__A3ZPalS9aOltaWs09cbPoBuA tyObject_PNGTranscolonObjectType__A3ZPalS9aOltaWs09cbPoBuA;
typedef struct tyObject_PNGPhyscolonObjectType__DIdBuf9cN8oFoYRxXG4B9ccA tyObject_PNGPhyscolonObjectType__DIdBuf9cN8oFoYRxXG4B9ccA;
typedef struct tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g;
typedef struct tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w;
typedef struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA;
typedef struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w;
typedef struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ;
typedef struct tyObject_PNGSettingscolonObjectType__d9bVWoSPrpZUTCBA9cSwNxfQ tyObject_PNGSettingscolonObjectType__d9bVWoSPrpZUTCBA9cSwNxfQ;
typedef struct tyObject_APNGFramecolonObjectType__SAu9a4u5IBriCV9cbj5Kxeig tyObject_APNGFramecolonObjectType__SAu9a4u5IBriCV9cbj5Kxeig;
typedef struct tySequence_ulsDHyRkreLOq1Qfonz4kA tySequence_ulsDHyRkreLOq1Qfonz4kA;
typedef struct tySequence_M4mmrieYxM8yFm9bD2E7jkg tySequence_M4mmrieYxM8yFm9bD2E7jkg;
typedef struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ tySequence_sM4lkSb7zS6F7OVMvW9cffQ;
typedef struct tyObject_APNGFrameChunkcolonObjectType__EgPEsE2RG9bpxi1zW8cli6A tyObject_APNGFrameChunkcolonObjectType__EgPEsE2RG9bpxi1zW8cli6A;
typedef struct tySequence_qwqHTkRvwhrRyENtudHQ7g tySequence_qwqHTkRvwhrRyENtudHQ7g;
typedef struct tySequence_ZbeuK49bnXlBFergN2fMXJw tySequence_ZbeuK49bnXlBFergN2fMXJw;
typedef struct tySequence_i2hxTTh6F9cnFKwT363YGsw tySequence_i2hxTTh6F9cnFKwT363YGsw;
typedef struct tyObject_PNGSPEntry_ssGGwOIR6eguzTlrHozL1Q tyObject_PNGSPEntry_ssGGwOIR6eguzTlrHozL1Q;
typedef struct tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A;
typedef N_CDECL_PTR(int, tyProc_cez8YhJI0vaCUcjGg6z4zA) (void);
typedef NU8 tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A;
typedef NU8 tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ;
typedef N_NIMCALL_PTR(void, tyProc_ojoeKfW4VYIm36I9cpDTQIg) (void* p, NI op);
typedef N_NIMCALL_PTR(void*, tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ) (void* p);
struct TNimType {
NI size;
tyEnum_TNimKind_jIBKr1ejBgsfM33Kxw4j7A kind;
tySet_tyEnum_TNimTypeFlag_v8QUszD1sWlSIWZz7mC4bQ flags;
TNimType* base;
TNimNode* node;
void* finalizer;
tyProc_ojoeKfW4VYIm36I9cpDTQIg marker;
tyProc_WSm2xU5ARYv9aAR4l0z9c9auQ deepcopy;
};
typedef NU8 tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ;
struct TNimNode {
tyEnum_TNimNodeKind_unfNsxrcATrufDZmpBq4HQ kind;
NI offset;
TNimType* typ;
NCSTRING name;
NI len;
TNimNode** sons;
};
typedef N_NIMCALL_PTR(void, tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ) (void);
struct RootObj {
TNimType* m_type;
};
struct TGenericSeq {
NI len;
NI reserved;
};
struct NimStringDesc {
  TGenericSeq Sup;
NIM_CHAR data[SEQ_DECL_SIZE];
};
struct Exception {
  RootObj Sup;
Exception* parent;
NCSTRING name;
NimStringDesc* message;
tySequence_uB9b75OUPRENsBAu4AnoePA* trace;
Exception* up;
};
struct tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g {
NI refcount;
TNimType* typ;
};
struct tyObject_GcStack_7fytPA5bBsob6See21YMRA {
void* bottom;
};
struct tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w {
NI len;
NI cap;
tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g** d;
};
typedef tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* tyArray_SiRwrEKZdLgxqz9a9aoVBglg[512];
typedef NU32 tyArray_BHbOSqU1t9b3Gt7K2c6fQig[24];
typedef tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* tyArray_N1u1nqOgmuJN9cSZrnMHgOQ[32];
typedef tyArray_N1u1nqOgmuJN9cSZrnMHgOQ tyArray_B6durA4ZCi1xjJvRtyYxMg[24];
typedef tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* tyArray_lh2A89ahMmYg9bCmpVaplLbA[256];
struct tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA {
tyArray_lh2A89ahMmYg9bCmpVaplLbA data;
};
typedef tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* tyArray_0aOLqZchNi8nWtMTi8ND8w[2];
struct tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw {
tyArray_0aOLqZchNi8nWtMTi8ND8w link;
NI key;
NI upperBound;
NI level;
};
struct tyTuple_ujsjpB2O9cjj3uDHsXbnSzg {
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* Field0;
NI Field1;
};
typedef tyTuple_ujsjpB2O9cjj3uDHsXbnSzg tyArray_LzOv2eCDGiceMKQstCLmhw[30];
struct tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg {
NI len;
tyArray_LzOv2eCDGiceMKQstCLmhw chunks;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg* next;
};
struct tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg {
NI minLargeObj;
NI maxLargeObj;
tyArray_SiRwrEKZdLgxqz9a9aoVBglg freeSmallChunks;
NU32 flBitmap;
tyArray_BHbOSqU1t9b3Gt7K2c6fQig slBitmap;
tyArray_B6durA4ZCi1xjJvRtyYxMg matrix;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* llmem;
NI currMem;
NI maxMem;
NI freeMem;
NI occ;
NI lastSize;
tyObject_IntSet_EZObFrE3NC9bIb3YMkY9crZA chunkStarts;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* root;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* deleted;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* last;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw* freeAvlNodes;
NIM_BOOL locked;
NIM_BOOL blockChunkSizeIncrease;
NI nextChunkSize;
tyObject_AvlNode_IaqjtwKhxLEpvDS9bct9blEw bottomData;
tyObject_HeapLinks_PDV1HBZ8CQSQJC9aOBFNRSg heapLinks;
};
struct tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg {
NI stackScans;
NI cycleCollections;
NI maxThreshold;
NI maxStackSize;
NI maxStackCells;
NI cycleTableSize;
NI64 maxPause;
};
struct tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ {
NI counter;
NI max;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* head;
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg** data;
};
struct tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ {
tyObject_GcStack_7fytPA5bBsob6See21YMRA stack;
NI cycleThreshold;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w zct;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w decStack;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w tempStack;
NI recGcLock;
tyObject_MemRegion_x81NhDv59b8ercDZ9bi85jyg region;
tyObject_GcStat_0RwLoVBHZPfUAcLczmfQAg stat;
tyObject_CellSet_jG87P0AI9aZtss9ccTYBIISQ marked;
tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w additionalRoots;
NI gcThreadId;
};
typedef NU8 tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg;
typedef N_CDECL_PTR(void*, tyProc_xjK2Jbm9aCJ7DEn7DKl9ceYg) (int width, int height, NCSTRING title, void* monitor, void* share);
typedef N_CDECL_PTR(void, tyProc_32w2ZypAyMWuajvi2Jt79cg) (void* window);
struct tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw {
NI32 coords;
NI32 colors;
NI32 tex_coords;
NI32 texture;
};
struct tyObject_Program_5U307oTET301CaFCP809big {
NU32 handle;
tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw locations;
};
struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ {
NI width;
NI height;
NU32 handle;
};
typedef NU8 tyEnum_PixelFormat_8J9cBMWJgNNS8b4aTcfFdQg;
struct tyObject_PNGResultcolonObjectType__UGj0Wf0n6sttZ5gHuJqzug {
NI width;
NI height;
NimStringDesc* data;
tySequence_54FDWV4H446H3czolNxQbA* frames;
};
typedef NimStringDesc* tyArray_Re75IspeoxXy2oCZHwcRrA[2];
typedef NF32 tyArray_oyZrYU9bPA1n9b1MM23cnzzQ[12288];
typedef NU8 tyArray_tWovyCrDXxvtzvQ5q9awdWA[24576];
struct tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg {
NI coordIdx;
NI colorIdx;
NI texCoordIdx;
tyArray_oyZrYU9bPA1n9b1MM23cnzzQ coordData;
tyArray_tWovyCrDXxvtzvQ5q9awdWA colorData;
tyArray_oyZrYU9bPA1n9b1MM23cnzzQ texCoordData;
NU32 coordBuff;
NU32 colorBuff;
NU32 texCoordBuff;
tyObject_Program_5U307oTET301CaFCP809big program;
NU32 lastTexHandle;
};
typedef N_CDECL_PTR(int, tyProc_fbYpjfe38x3ujjAmVRbI1Q) (void* window);
typedef N_CDECL_PTR(void, tyProc_ln4kdL5W9bbX4a1xl8nnVXQ) (void);
typedef N_CDECL_PTR(int, tyProc_AbsnR49cK1X9a2Wblez5VQWQ) (void* window, int key);
typedef N_CDECL_PTR(void, tyProc_9cBAJsQgOiAekcR9ctCN5urQ) (void* window, int value);
struct tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ {
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ texture;
NF u0;
NF v0;
NF u1;
NF v1;
};
struct tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA {
NCSTRING procname;
NI line;
NCSTRING filename;
};
struct tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w {
NI prevSize;
NI size;
};
struct tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* next;
tyObject_SmallChunk_tXn60W2f8h3jgAYdEmy5NQ* prev;
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* freeList;
NI free;
NI acc;
NF data;
};
struct tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg {
  tyObject_BaseChunk_Sdq7WpT6qAH858F5ZEdG3w Sup;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* next;
tyObject_BigChunk_Rv9c70Uhp2TytkX7eH78qEg* prev;
NF data;
};
struct tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw {
NI size;
NI acc;
tyObject_LLChunk_XsENErzHIZV9bhvyJx56wGw* next;
};
typedef NI tyArray_9a8QARi5WsUggNU9bom7kzTQ[8];
struct tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw {
tyObject_Trunk_W0r8S0Y3UGke6T9bIUWnnuw* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg {
tyObject_PageDesc_fublkgIY4LG3mT51LU2WHg* next;
NI key;
tyArray_9a8QARi5WsUggNU9bom7kzTQ bits;
};
struct tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug {
  RootObj Sup;
tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold;
NimStringDesc* fmtStr;
};
struct tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA {
  tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug Sup;
};
struct tyObject_PNGSettingscolonObjectType__d9bVWoSPrpZUTCBA9cSwNxfQ {
  RootObj Sup;
};
struct tyObject_PNGDecodercolonObjectType__YCEZFAllgHMittYhSqWqEQ {
  tyObject_PNGSettingscolonObjectType__d9bVWoSPrpZUTCBA9cSwNxfQ Sup;
NIM_BOOL colorConvert;
NIM_BOOL readTextChunks;
NIM_BOOL rememberUnknownChunks;
NIM_BOOL ignoreCRC;
NIM_BOOL ignoreAdler32;
};
struct tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw {
  RootObj Sup;
NI length;
NI32 chunkType;
NU32 crc;
NimStringDesc* data;
NI pos;
};
struct tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw {
tyObject_PNGSettingscolonObjectType__d9bVWoSPrpZUTCBA9cSwNxfQ* settings;
tySequence_ulsDHyRkreLOq1Qfonz4kA* chunks;
NimStringDesc* pixels;
NI width;
NI height;
tySequence_M4mmrieYxM8yFm9bD2E7jkg* apngChunks;
NIM_BOOL firstFrameIsDefaultImage;
NIM_BOOL isAPNG;
tySequence_sM4lkSb7zS6F7OVMvW9cffQ* apngPixels;
};
struct tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI year;
NI month;
NI day;
NI hour;
NI minute;
NI second;
};
struct tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NimStringDesc* idat;
};
typedef NU8 tyEnum_PNGColorType_6NseIBcU1F9aLu6cFQlJjyg;
typedef NU8 tyEnum_PNGInterlace_9bp9ce9c69cdZc49cWx9biCJ9amYQ;
struct tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI width;
NI height;
NI bitDepth;
tyEnum_PNGColorType_6NseIBcU1F9aLu6cFQlJjyg colorType;
NI compressionMethod;
NI filterMethod;
tyEnum_PNGInterlace_9bp9ce9c69cdZc49cWx9biCJ9amYQ interlaceMethod;
};
struct tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NimStringDesc* keyword;
NimStringDesc* text;
};
struct tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NimStringDesc* profileName;
NimStringDesc* profile;
};
struct tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NimStringDesc* keyword;
NimStringDesc* text;
NimStringDesc* languageTag;
NimStringDesc* translatedKeyword;
};
struct tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NimStringDesc* keyword;
NimStringDesc* text;
};
struct tyObject_APNGFrameChunkcolonObjectType__EgPEsE2RG9bpxi1zW8cli6A {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI sequenceNumber;
};
typedef NU8 tyEnum_APNG_DISPOSE_OP_bHZjOPjI9b7xRyrDNF6It5w;
typedef NU8 tyEnum_APNG_BLEND_OP_Vr4zw9aRqV1Fu5Qqb7vdVjw;
struct tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ {
  tyObject_APNGFrameChunkcolonObjectType__EgPEsE2RG9bpxi1zW8cli6A Sup;
NI width;
NI height;
NI xOffset;
NI yOffset;
NI delayNum;
NI delayDen;
tyEnum_APNG_DISPOSE_OP_bHZjOPjI9b7xRyrDNF6It5w disposeOp;
tyEnum_APNG_BLEND_OP_Vr4zw9aRqV1Fu5Qqb7vdVjw blendOp;
};
struct tyObject_PNGStandarRGBcolonObjectType__19ah8rXfRZMmdCeZoOyE8Hw {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI renderingIntent;
};
struct tyObject_PNGHistcolonObjectType__LT7Y9a9bsqO6qiFWdeftE0WA {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
tySequence_qwqHTkRvwhrRyENtudHQ7g* histogram;
};
struct tyObject_PNGSPalettecolonObjectType__IQbkgmOSGm6kEHaEfeltDw {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NimStringDesc* paletteName;
NI sampleDepth;
tySequence_ZbeuK49bnXlBFergN2fMXJw* palette;
};
struct tyObject_PNGSbitcolonObjectType__hMHzmPmnYaDDKI81MPfelQ {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
};
struct tyObject_APNGFrameDatacolonObjectType__R7Jw9cl9cQmf0yjLYX7u8kxw {
  tyObject_APNGFrameChunkcolonObjectType__EgPEsE2RG9bpxi1zW8cli6A Sup;
NI frameDataPos;
};
struct tyObject_PNGGammacolonObjectType__UDHAj9c34pyOZKEGUUayLSg {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI gamma;
};
struct tyObject_APNGAnimationControlcolonObjectType__wnKS2ux9aN2yCglvRsRiPrQ {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI numFrames;
NI numPlays;
};
struct tyObject_PNGChromacolonObjectType__oJWRCuC12OxkSgyxp4G6Aw {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI whitePointX;
NI whitePointY;
NI redX;
NI redY;
NI greenX;
NI greenY;
NI blueX;
NI blueY;
};
struct tyObject_PNGPalettecolonObjectType__EliRKtUsLlyl0DkfPoJTCw {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
tySequence_i2hxTTh6F9cnFKwT363YGsw* palette;
};
struct tyObject_PNGBackgroundcolonObjectType__29bWwuvCwJ8KaXreO9bPK09cw {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI bkgdR;
NI bkgdG;
NI bkgdB;
};
struct tyObject_PNGTranscolonObjectType__A3ZPalS9aOltaWs09cbPoBuA {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI keyR;
NI keyG;
NI keyB;
};
struct tyObject_PNGPhyscolonObjectType__DIdBuf9cN8oFoYRxXG4B9ccA {
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw Sup;
NI physX;
NI physY;
NI unit;
};
struct tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w {
  tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug Sup;
FILE* file;
};
typedef NU8 tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ;
struct tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g {
  tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w Sup;
NI maxLines;
NI curLine;
NimStringDesc* baseName;
tyEnum_FileMode_fVUBHvW79bXUw1j55Oo9avSQ baseMode;
NI logFiles;
NI bufSize;
};
struct tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ {
tyObject_FreeCell_u6M5LHprqzkn9axr04yg9bGQ* next;
NI zeroField;
};
struct tyObject_APNGFramecolonObjectType__SAu9a4u5IBriCV9cbj5Kxeig {
tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ* ctl;
NimStringDesc* data;
};
struct tyObject_PNGSPEntry_ssGGwOIR6eguzTlrHozL1Q {
NI red;
NI green;
NI blue;
NI alpha;
NI frequency;
};
struct tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A {
NIM_CHAR r;
NIM_CHAR g;
NIM_CHAR b;
NIM_CHAR a;
};
struct tySequence_uB9b75OUPRENsBAu4AnoePA {
  TGenericSeq Sup;
  tyObject_StackTraceEntry_oLyohQ7O2XOvGnflOss8EA data[SEQ_DECL_SIZE];
};
struct tySequence_54FDWV4H446H3czolNxQbA {
  TGenericSeq Sup;
  tyObject_APNGFramecolonObjectType__SAu9a4u5IBriCV9cbj5Kxeig* data[SEQ_DECL_SIZE];
};
struct tySequence_ulsDHyRkreLOq1Qfonz4kA {
  TGenericSeq Sup;
  tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw* data[SEQ_DECL_SIZE];
};
struct tySequence_M4mmrieYxM8yFm9bD2E7jkg {
  TGenericSeq Sup;
  tyObject_APNGFrameChunkcolonObjectType__EgPEsE2RG9bpxi1zW8cli6A* data[SEQ_DECL_SIZE];
};
struct tySequence_sM4lkSb7zS6F7OVMvW9cffQ {
  TGenericSeq Sup;
  NimStringDesc* data[SEQ_DECL_SIZE];
};
struct tySequence_qwqHTkRvwhrRyENtudHQ7g {
  TGenericSeq Sup;
  NI data[SEQ_DECL_SIZE];
};
struct tySequence_ZbeuK49bnXlBFergN2fMXJw {
  TGenericSeq Sup;
  tyObject_PNGSPEntry_ssGGwOIR6eguzTlrHozL1Q data[SEQ_DECL_SIZE];
};
struct tySequence_i2hxTTh6F9cnFKwT363YGsw {
  TGenericSeq Sup;
  tyObject_RGBA8_P4w0wnmH7J1IGztO6QfG5A data[SEQ_DECL_SIZE];
};
N_NIMCALL(void, nimGCvisit)(void* d, NI op);
static N_NIMCALL(void, TM_ipcYmBC9bj9a1BW35ABoB1Kw_2)(void);
N_NIMCALL(void, nimRegisterGlobalMarker)(tyProc_T4eqaYlFJYZUv9aG9b1TV0bQ markerProc);
static N_INLINE(void, nimGCunrefRC1)(void* p);
static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_LIB_PRIVATE N_NOINLINE(void, addZCT_fCDI7oO1NNVXXURtxSzsRw)(tyObject_CellSeq_Axo1XVm9aaQueTOldv8le5w* s, tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr);
N_NIMCALL(void*, newObjRC1)(TNimType* typ, NI size);
N_NIMCALL(NimStringDesc*, copyStringRC1)(NimStringDesc* src);
static N_INLINE(void, nimGCunrefNoCycle)(void* p);
static N_INLINE(void, asgnRef)(void** dest, void* src);
static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c);
N_NIMCALL(void, raiseException)(Exception* e, NCSTRING ename);
N_LIB_PRIVATE N_NIMCALL(void, addHandler_tg0stk9atBM54nh79a3PBrOA)(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* handler);
N_LIB_PRIVATE N_NIMCALL(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*, newConsoleLogger_EgdHBnSBbwirQsDvEbPCdg)(tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg levelThreshold, NimStringDesc* fmtStr);
N_NIMCALL(void, nimLoadProcs0)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, getStandardLocations_giUqXozJi7uywizGM9a9beug)(NU32 program);
N_NOINLINE(void, chckNil)(void* p);
N_LIB_PRIVATE N_STDCALL(NI32, glGetAttribLocation_oSrxPmF9cyUrVZRg4cZ4LjQ)(NU32 program, NCSTRING name);
N_LIB_PRIVATE N_STDCALL(NI32, glGetUniformLocation_oSrxPmF9cyUrVZRg4cZ4LjQ_2)(NU32 program, NCSTRING name);
N_LIB_PRIVATE N_NIMCALL(NU32, createProgram_ap6cDX2l6cLS9bixaOW9cplg)(NU32 vertexShader, NU32 fragmentShader);
N_LIB_PRIVATE N_NIMCALL(NU32, createShader_2AHO9c5dppd7n465CyKP18A)(NU32 shaderType, NimStringDesc* source);
N_NIMCALL(void, genericReset)(void* dest, TNimType* mt);
static N_NIMCALL(void, TM_ipcYmBC9bj9a1BW35ABoB1Kw_7)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_PNGResultcolonObjectType__UGj0Wf0n6sttZ5gHuJqzug*, loadPNG32_9bMlYZh4PdO4Rg4mqC8VJFg)(NimStringDesc* fileName, tyObject_PNGDecodercolonObjectType__YCEZFAllgHMittYhSqWqEQ* settings);
N_LIB_PRIVATE N_NIMCALL(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ, createTexture_Xt2LvZ6NCFeQAauwyI4Xeg)(NI width, NI height, tyEnum_PixelFormat_8J9cBMWJgNNS8b4aTcfFdQg format, NimStringDesc** data);
N_NIMCALL(NimStringDesc*, nimIntToStr)(NI x);
N_NIMCALL(void, echoBinSafe)(NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg, newSpriteBatch_Rx4s9cI3qy4Qwal5QjiqUBw)(tyObject_Program_5U307oTET301CaFCP809big program);
N_LIB_PRIVATE N_STDCALL(void, glClearColor_f9bT9as4U8bxdkTUxJK60qlA)(NF32 red, NF32 green, NF32 blue, NF32 alpha);
N_LIB_PRIVATE N_STDCALL(void, glClear_ecjp09clx9c7t3uIhyfuACGQ)(NU32 mask);
N_LIB_PRIVATE N_NIMCALL(void, draw_2FrjBHe3tWgCd1N7e15eHw)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch, tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ* reg, NF x, NF y, NF w, NF h);
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ, makeTextureRegion_10Ua2psAivWdjmRBQsvDtA)(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NI x, NI y, NI width, NI height);
static N_INLINE(NI, subInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
N_LIB_PRIVATE N_NIMCALL(void, flush_GHonqE9aQDzibr6yQNKdk3A)(tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg* batch);
N_NIMCALL(void, chckNilDisp)(void* p);
static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NOINLINE(NIM_BOOL, isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg)(TNimType* obj, TNimType* subclass, TNimType** cache);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_45LvIL0vtyWdfWB3UnhGqw)(tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_NIMCALL(void, chckObj)(TNimType* obj, TNimType* subclass);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_oc0WZ2tp9bbJfl0wUUjUNQA)(tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_nOl1j6BrGY1Z66jHbqYf8A)(tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg* header, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_iINp1zhnlPxLbSRphuEN0w)(tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_SaMVSf9bJH269cOlLNbV0Kag)(tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_kJehw0Ir7Artp89bM9avhUYg)(tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_zDMhjbZAKC29cdauwRCTwxQ)(tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_vHWs7qbKpjD3JhdXw6DsRQ_2)(tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_mdjB58OHI6j9c07YXah9b0SA)(tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_VOEemMktNEtLAnGqe2NkRQ)(tyObject_PNGStandarRGBcolonObjectType__19ah8rXfRZMmdCeZoOyE8Hw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_f1Csfw6GK8I6uZ9aReM9ax8g)(tyObject_PNGHistcolonObjectType__LT7Y9a9bsqO6qiFWdeftE0WA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_C3QLu189bW7TGq4XUYtiJ4Q)(tyObject_PNGSPalettecolonObjectType__IQbkgmOSGm6kEHaEfeltDw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_Yqr9bYNYbizHCl50cNUo0Ug)(tyObject_PNGSbitcolonObjectType__hMHzmPmnYaDDKI81MPfelQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_i2Erk5UJ3zJ0fXAGvMZPJw)(tyObject_APNGFrameDatacolonObjectType__R7Jw9cl9cQmf0yjLYX7u8kxw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_vHWs7qbKpjD3JhdXw6DsRQ)(tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_SaMVSf9bJH269cOlLNbV0Kag_2)(tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_iINp1zhnlPxLbSRphuEN0w_2)(tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_fS9cfD0FVS0VVKlnmc5VwOQ)(tyObject_PNGGammacolonObjectType__UDHAj9c34pyOZKEGUUayLSg* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_kJehw0Ir7Artp89bM9avhUYg_2)(tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_2a6wG1cvLN85BDnzT7Riww)(tyObject_APNGAnimationControlcolonObjectType__wnKS2ux9aN2yCglvRsRiPrQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_RsWUXX6AEMqhtRVVJUWyjg)(tyObject_PNGChromacolonObjectType__oJWRCuC12OxkSgyxp4G6Aw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_KlDtsoibKBOQWOEX9bF9bDGw)(tyObject_PNGPalettecolonObjectType__EliRKtUsLlyl0DkfPoJTCw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_WilUcM7l4auoZDrNezzfYQ)(tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_zDMhjbZAKC29cdauwRCTwxQ_2)(tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_oc0WZ2tp9bbJfl0wUUjUNQA_2)(tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_45LvIL0vtyWdfWB3UnhGqw_2)(tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_w9bXHZQNdsXY9a2Vl9aA9c81Ew)(tyObject_PNGBackgroundcolonObjectType__29bWwuvCwJ8KaXreO9bPK09cw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_wQnbfAKRQnaxvEGUdtchig)(tyObject_PNGTranscolonObjectType__A3ZPalS9aOltaWs09cbPoBuA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_tso9cUarLApsWLxQQMv5bnw)(tyObject_PNGPhyscolonObjectType__DIdBuf9cN8oFoYRxXG4B9ccA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_mdjB58OHI6j9c07YXah9b0SA_2)(tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_SaMVSf9bJH269cOlLNbV0Kag_3)(tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_kJehw0Ir7Artp89bM9avhUYg_3)(tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_oc0WZ2tp9bbJfl0wUUjUNQA_3)(tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_iINp1zhnlPxLbSRphuEN0w_3)(tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_i2Erk5UJ3zJ0fXAGvMZPJw_2)(tyObject_APNGFrameDatacolonObjectType__R7Jw9cl9cQmf0yjLYX7u8kxw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_zDMhjbZAKC29cdauwRCTwxQ_3)(tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_2a6wG1cvLN85BDnzT7Riww_2)(tyObject_APNGAnimationControlcolonObjectType__wnKS2ux9aN2yCglvRsRiPrQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_C3QLu189bW7TGq4XUYtiJ4Q_2)(tyObject_PNGSPalettecolonObjectType__IQbkgmOSGm6kEHaEfeltDw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_VOEemMktNEtLAnGqe2NkRQ_2)(tyObject_PNGStandarRGBcolonObjectType__19ah8rXfRZMmdCeZoOyE8Hw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_vHWs7qbKpjD3JhdXw6DsRQ_3)(tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_fS9cfD0FVS0VVKlnmc5VwOQ_2)(tyObject_PNGGammacolonObjectType__UDHAj9c34pyOZKEGUUayLSg* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_KlDtsoibKBOQWOEX9bF9bDGw_2)(tyObject_PNGPalettecolonObjectType__EliRKtUsLlyl0DkfPoJTCw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_WilUcM7l4auoZDrNezzfYQ_2)(tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_RsWUXX6AEMqhtRVVJUWyjg_2)(tyObject_PNGChromacolonObjectType__oJWRCuC12OxkSgyxp4G6Aw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_f1Csfw6GK8I6uZ9aReM9ax8g_2)(tyObject_PNGHistcolonObjectType__LT7Y9a9bsqO6qiFWdeftE0WA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_tso9cUarLApsWLxQQMv5bnw_2)(tyObject_PNGPhyscolonObjectType__DIdBuf9cN8oFoYRxXG4B9ccA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_45LvIL0vtyWdfWB3UnhGqw_3)(tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_w9bXHZQNdsXY9a2Vl9aA9c81Ew_2)(tyObject_PNGBackgroundcolonObjectType__29bWwuvCwJ8KaXreO9bPK09cw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_wQnbfAKRQnaxvEGUdtchig_2)(tyObject_PNGTranscolonObjectType__A3ZPalS9aOltaWs09cbPoBuA* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_mdjB58OHI6j9c07YXah9b0SA_3)(tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png);
N_LIB_PRIVATE N_NIMCALL(void, log_Z1wwTzhV8hfwxjrAweVVZQ)(tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log_ZlB8IWVc9cdlahbPdrAh0Og)(tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log_F2wVp9bYd9alkwSwovfO9aanw)(tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
N_LIB_PRIVATE N_NIMCALL(void, log_ickm9bT0pWcynhn7oX83aTg)(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0);
static N_INLINE(void, initStackBottomWith)(void* locals);
N_NOINLINE(void, setStackBottom)(void* theStackBottom);
NIM_EXTERNC N_NOINLINE(void, systemInit000)(void);
NIM_EXTERNC N_NOINLINE(void, systemDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, glfw_glfw3Init000)(void);
NIM_EXTERNC N_NOINLINE(void, glfw_glfw3DatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_macrosDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_sequtilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_parseutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_mathDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_algorithmDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_strutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_dynlibDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_winleanDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_timesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_ospathsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_osDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, opengl_openglInit000)(void);
NIM_EXTERNC N_NOINLINE(void, opengl_openglDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_streamsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_endiansDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_hashesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_tablesDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimPNG_bufferInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimPNG_bufferDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimPNG_nimzInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimPNG_nimzDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimPNG_nimPNGInit000)(void);
NIM_EXTERNC N_NOINLINE(void, nimPNG_nimPNGDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_loggingInit000)(void);
NIM_EXTERNC N_NOINLINE(void, stdlib_loggingDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_glutilsInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_glutilsDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_textureInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_textureDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_textureregionInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_textureregionDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_spritebatchInit000)(void);
NIM_EXTERNC N_NOINLINE(void, unknown_spritebatchDatInit000)(void);
NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void);
NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void);
extern tyProc_cez8YhJI0vaCUcjGg6z4zA Dl_108855_;
Exception* e_TTtl9bYTKPNoTGtunSBNPVg;
extern TNimType NTI_oUKtBcKRdK6usj8RWrlp6A_;
extern tyObject_GcHeap_1TRH1TZMaVZTnLNcIHuNFQ gch_IcYaEuuWivYAS86vFMTS3Q;
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
extern TNimType NTI_bAvOj2UcojKN87yAQLs0aw_;
void* window_dD49cxsV0oovpiv8IGDCmxA;
extern tyProc_xjK2Jbm9aCJ7DEn7DKl9ceYg Dl_108928_;
extern tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_109195_;
NU32 handle_be1PDmhwBN9aUP9b0Z9cxnyjg;
tyObject_Program_5U307oTET301CaFCP809big program_wJjMvAO7mULmp9cHljQls8Q;
extern TNimType NTI_5U307oTET301CaFCP809big_;
tyObject_PNGResultcolonObjectType__UGj0Wf0n6sttZ5gHuJqzug* png_RMrzyLJuTrkfKnEVsGKAmg;
extern TNimType NTI_rn9cEqofeFEccqdUAboxoKQ_;
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex_WARSAqa76GTaQHkTuw4WbA;
tyObject_SpriteBatch_JcKc07Td1XxTtLTY9cIpGPg batch_2OjOVmonJdOmSkINAfqJXQ;
extern tyProc_fbYpjfe38x3ujjAmVRbI1Q Dl_108938_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_109073_;
extern tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_109200_;
extern tyProc_AbsnR49cK1X9a2Wblez5VQWQ Dl_109091_;
extern tyProc_9cBAJsQgOiAekcR9ctCN5urQ Dl_108941_;
extern tyProc_32w2ZypAyMWuajvi2Jt79cg Dl_108935_;
extern tyProc_ln4kdL5W9bbX4a1xl8nnVXQ Dl_108857_;
extern TNimType NTI_s0sPyN9atFvjezpAW8tdnmw_;
static TNimType* Nim_OfCheck_CACHE12[2];
extern TNimType NTI_x6P7vE9cYceltKZAZDSQVuQ_;
static TNimType* Nim_OfCheck_CACHE13[2];
extern TNimType NTI_TJdSTRO4iixkiNDLa9cshfg_;
static TNimType* Nim_OfCheck_CACHE14[2];
extern TNimType NTI_i9cF13cHtN9cwvMVXkTJEO1Q_;
static TNimType* Nim_OfCheck_CACHE15[2];
extern TNimType NTI_nMRAAuCEC9aROxdmFdUpJtA_;
static TNimType* Nim_OfCheck_CACHE16[2];
extern TNimType NTI_rMpje6gA2Q2GH0W9bTwxWbw_;
static TNimType* Nim_OfCheck_CACHE17[2];
extern TNimType NTI_H9cL3h8nRRweZK9axJZKCdfQ_;
static TNimType* Nim_OfCheck_CACHE18[2];
extern TNimType NTI_XHELJVsVdBknz4Bfivv4kQ_;
static TNimType* Nim_OfCheck_CACHE19[2];
extern TNimType NTI_DNM8loOImElj9bvoxFar9auw_;
static TNimType* Nim_OfCheck_CACHE20[2];
extern TNimType NTI_19ah8rXfRZMmdCeZoOyE8Hw_;
static TNimType* Nim_OfCheck_CACHE21[2];
extern TNimType NTI_LT7Y9a9bsqO6qiFWdeftE0WA_;
static TNimType* Nim_OfCheck_CACHE22[2];
extern TNimType NTI_IQbkgmOSGm6kEHaEfeltDw_;
static TNimType* Nim_OfCheck_CACHE23[2];
extern TNimType NTI_hMHzmPmnYaDDKI81MPfelQ_;
static TNimType* Nim_OfCheck_CACHE24[2];
extern TNimType NTI_R7Jw9cl9cQmf0yjLYX7u8kxw_;
static TNimType* Nim_OfCheck_CACHE25[2];
static TNimType* Nim_OfCheck_CACHE26[2];
static TNimType* Nim_OfCheck_CACHE27[2];
static TNimType* Nim_OfCheck_CACHE28[2];
extern TNimType NTI_UDHAj9c34pyOZKEGUUayLSg_;
static TNimType* Nim_OfCheck_CACHE29[2];
static TNimType* Nim_OfCheck_CACHE30[2];
extern TNimType NTI_wnKS2ux9aN2yCglvRsRiPrQ_;
static TNimType* Nim_OfCheck_CACHE31[2];
extern TNimType NTI_oJWRCuC12OxkSgyxp4G6Aw_;
static TNimType* Nim_OfCheck_CACHE32[2];
extern TNimType NTI_EliRKtUsLlyl0DkfPoJTCw_;
static TNimType* Nim_OfCheck_CACHE33[2];
static TNimType* Nim_OfCheck_CACHE34[2];
static TNimType* Nim_OfCheck_CACHE35[2];
static TNimType* Nim_OfCheck_CACHE36[2];
static TNimType* Nim_OfCheck_CACHE37[2];
extern TNimType NTI_29bWwuvCwJ8KaXreO9bPK09cw_;
static TNimType* Nim_OfCheck_CACHE38[2];
extern TNimType NTI_A3ZPalS9aOltaWs09cbPoBuA_;
static TNimType* Nim_OfCheck_CACHE39[2];
extern TNimType NTI_DIdBuf9cN8oFoYRxXG4B9ccA_;
static TNimType* Nim_OfCheck_CACHE40[2];
static TNimType* Nim_OfCheck_CACHE41[2];
static TNimType* Nim_OfCheck_CACHE42[2];
static TNimType* Nim_OfCheck_CACHE43[2];
static TNimType* Nim_OfCheck_CACHE44[2];
static TNimType* Nim_OfCheck_CACHE45[2];
static TNimType* Nim_OfCheck_CACHE46[2];
static TNimType* Nim_OfCheck_CACHE47[2];
static TNimType* Nim_OfCheck_CACHE48[2];
static TNimType* Nim_OfCheck_CACHE49[2];
static TNimType* Nim_OfCheck_CACHE50[2];
static TNimType* Nim_OfCheck_CACHE51[2];
static TNimType* Nim_OfCheck_CACHE52[2];
static TNimType* Nim_OfCheck_CACHE53[2];
static TNimType* Nim_OfCheck_CACHE54[2];
static TNimType* Nim_OfCheck_CACHE55[2];
static TNimType* Nim_OfCheck_CACHE56[2];
static TNimType* Nim_OfCheck_CACHE57[2];
static TNimType* Nim_OfCheck_CACHE58[2];
static TNimType* Nim_OfCheck_CACHE59[2];
static TNimType* Nim_OfCheck_CACHE60[2];
static TNimType* Nim_OfCheck_CACHE61[2];
extern TNimType NTI_O2Lvje8yIZTOG9bz4MrKW7g_;
static TNimType* Nim_OfCheck_CACHE62[2];
extern TNimType NTI_DiHvgyNJFmeALM5A2LhG3w_;
static TNimType* Nim_OfCheck_CACHE63[2];
extern TNimType NTI_QaTO46vt5hgK2eu9ah2xGrA_;
static TNimType* Nim_OfCheck_CACHE64[2];
extern TNimType NTI_igsiUXBFuP9cp5KwKL5yiug_;
static TNimType* Nim_OfCheck_CACHE65[2];
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_3, "Failed to Initialize GLFW", 25);
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_4, "$levelname ", 11);
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_5, "\015\012attribute vec4 a_position;\015\012attribute vec4 a_color;\015\012attribut"
"e vec2 a_texcoord;\015\012\015\012varying vec4 v_color;\015\012varying vec2 v_texc"
"oord;\015\012\015\012void main() {\015\012    gl_Position = a_position;\015\012    v_col"
"or = a_color;\015\012    v_texcoord = a_texcoord;\015\012}", 237);
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_6, "precision mediump float;\015\012varying vec4 v_color;\015\012varying vec2 v"
"_texcoord;\015\012uniform sampler2D u_texture;\015\012\015\012void main() {\015\012    v"
"ec4 t4 = texture2D(u_texture, v_texcoord);\015\012    gl_FragColor = t"
"4 * v_color;\015\012}", 206);
STRING_LITERAL(TM_ipcYmBC9bj9a1BW35ABoB1Kw_8, "logo.png", 8);
static N_NIMCALL(void, TM_ipcYmBC9bj9a1BW35ABoB1Kw_2)(void) {
	nimGCvisit((void*)e_TTtl9bYTKPNoTGtunSBNPVg, 0);
}

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(void, rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("rtlAddZCT", "gc.nim");
	nimln_(211, "gc.nim");
	addZCT_fCDI7oO1NNVXXURtxSzsRw((&gch_IcYaEuuWivYAS86vFMTS3Q.zct), c);
	popFrame();
}

static N_INLINE(void, decRef_MV4BBk6J1qu70IbBxwEn4wsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("decRef", "gc.nim");
	nimln_(218, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(219, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*, usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem)(void* usr) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* result;
	nimfr_("usrToCell", "gc.nim");
	result = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	nimln_(132, "gc.nim");
	result = ((tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*) ((NI)((NU64)(((NI) (ptrdiff_t) (usr))) - (NU64)(((NI)sizeof(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g))))));
	popFrame();
	return result;
}

static N_INLINE(void, nimGCunrefRC1)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T1_;
	nimfr_("nimGCunrefRC1", "gc.nim");
	nimln_(258, "gc.nim");
	T1_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
	T1_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T1_);
	popFrame();
}

static N_INLINE(void, nimGCunrefNoCycle)(void* p) {
	tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c;
	nimfr_("nimGCunrefNoCycle", "gc.nim");
	nimln_(250, "gc.nim");
	c = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(p);
	nimln_(252, "gc.nim");
	{
		(*c).refcount -= ((NI) 8);
		if (!((NU64)((*c).refcount) < (NU64)(((NI) 8)))) goto LA3_;
		nimln_(253, "gc.nim");
		rtlAddZCT_MV4BBk6J1qu70IbBxwEn4w_2system(c);
	}
	LA3_: ;
	popFrame();
}

static N_INLINE(void, incRef_9cAA5YuQAAC3MVbnGeV86swsystem)(tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* c) {
	nimfr_("incRef", "gc.nim");
	nimln_(191, "gc.nim");
	(*c).refcount = (NI)((NU64)((*c).refcount) + (NU64)(((NI) 8)));
	popFrame();
}

static N_INLINE(void, asgnRef)(void** dest, void* src) {
	nimfr_("asgnRef", "gc.nim");
	nimln_(264, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T5_;
		nimln_(398, "system.nim");
		nimln_(264, "gc.nim");
		if (!!((src == NIM_NIL))) goto LA3_;
		T5_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T5_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem(src);
		incRef_9cAA5YuQAAC3MVbnGeV86swsystem(T5_);
	}
	LA3_: ;
	nimln_(265, "gc.nim");
	{
		tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g* T10_;
		nimln_(398, "system.nim");
		nimln_(265, "gc.nim");
		if (!!(((*dest) == NIM_NIL))) goto LA8_;
		T10_ = (tyObject_Cell_1zcF9cV8XIAtbN8h5HRUB8g*)0;
		T10_ = usrToCell_yB9aH5WIlwd0xkYrcdPeXrQsystem((*dest));
		decRef_MV4BBk6J1qu70IbBxwEn4wsystem(T10_);
	}
	LA8_: ;
	nimln_(266, "gc.nim");
	(*dest) = src;
	popFrame();
}

N_LIB_PRIVATE N_NIMCALL(tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw, getStandardLocations_giUqXozJi7uywizGM9a9beug)(NU32 program) {
	tyObject_ProgramLocations_w5LtLI9bobxLoIavQIQCGAw result;
	nimfr_("getStandardLocations", "test.nim");
{	memset((void*)(&result), 0, sizeof(result));
	nimln_(37, "test.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	nimln_(38, "test.nim");
	result.coords = glGetAttribLocation_oSrxPmF9cyUrVZRg4cZ4LjQ(program, "a_position");
	nimln_(39, "test.nim");
	result.colors = glGetAttribLocation_oSrxPmF9cyUrVZRg4cZ4LjQ(program, "a_color");
	nimln_(40, "test.nim");
	result.tex_coords = glGetAttribLocation_oSrxPmF9cyUrVZRg4cZ4LjQ(program, "a_texcoord");
	nimln_(41, "test.nim");
	result.texture = glGetUniformLocation_oSrxPmF9cyUrVZRg4cZ4LjQ_2(program, "u_texture");
	goto BeforeRet_;
	}BeforeRet_: ;
	popFrame();
	return result;
}
static N_NIMCALL(void, TM_ipcYmBC9bj9a1BW35ABoB1Kw_7)(void) {
	nimGCvisit((void*)png_RMrzyLJuTrkfKnEVsGKAmg, 0);
}

static N_INLINE(NI, subInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) - (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ (NI)((NU64) ~(b))));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

static N_INLINE(NIM_BOOL, isObjWithCache)(TNimType* obj, TNimType* subclass, TNimType** cache) {
	NIM_BOOL result;
{	result = (NIM_BOOL)0;
	{
		if (!(obj == subclass)) goto LA3_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA3_: ;
	{
		if (!((*obj).base == subclass)) goto LA7_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA7_: ;
	{
		if (!(cache[(((NI) 0))- 0] == obj)) goto LA11_;
		result = NIM_FALSE;
		goto BeforeRet_;
	}
	LA11_: ;
	{
		if (!(cache[(((NI) 1))- 0] == obj)) goto LA15_;
		result = NIM_TRUE;
		goto BeforeRet_;
	}
	LA15_: ;
	result = isObjSlowPath_k9bdq9bQE075AR7scLFt5wIg(obj, subclass, cache);
	goto BeforeRet_;
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, validateChunk_XjBLuFR33JWp4PM7tnVByA_2)(tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png) {
	NIM_BOOL result;
	nimfr_("validateChunk", "nimPNG.nim");
{	result = (NIM_BOOL)0;
	nimln_(425, "nimPNG.nim");
	chckNilDisp(chunk);
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_s0sPyN9atFvjezpAW8tdnmw_), Nim_OfCheck_CACHE12)))) goto LA3_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_s0sPyN9atFvjezpAW8tdnmw_));
		result = validateChunk_45LvIL0vtyWdfWB3UnhGqw(((tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_x6P7vE9cYceltKZAZDSQVuQ_), Nim_OfCheck_CACHE13)))) goto LA6_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_x6P7vE9cYceltKZAZDSQVuQ_));
		result = validateChunk_oc0WZ2tp9bbJfl0wUUjUNQA(((tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_TJdSTRO4iixkiNDLa9cshfg_), Nim_OfCheck_CACHE14)))) goto LA9_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_TJdSTRO4iixkiNDLa9cshfg_));
		result = validateChunk_nOl1j6BrGY1Z66jHbqYf8A(((tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA9_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_i9cF13cHtN9cwvMVXkTJEO1Q_), Nim_OfCheck_CACHE15)))) goto LA12_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_i9cF13cHtN9cwvMVXkTJEO1Q_));
		result = validateChunk_iINp1zhnlPxLbSRphuEN0w(((tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA12_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_nMRAAuCEC9aROxdmFdUpJtA_), Nim_OfCheck_CACHE16)))) goto LA15_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_nMRAAuCEC9aROxdmFdUpJtA_));
		result = validateChunk_SaMVSf9bJH269cOlLNbV0Kag(((tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA15_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_rMpje6gA2Q2GH0W9bTwxWbw_), Nim_OfCheck_CACHE17)))) goto LA18_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_rMpje6gA2Q2GH0W9bTwxWbw_));
		result = validateChunk_kJehw0Ir7Artp89bM9avhUYg(((tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA18_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_H9cL3h8nRRweZK9axJZKCdfQ_), Nim_OfCheck_CACHE18)))) goto LA21_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_H9cL3h8nRRweZK9axJZKCdfQ_));
		result = validateChunk_zDMhjbZAKC29cdauwRCTwxQ(((tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA21_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_XHELJVsVdBknz4Bfivv4kQ_), Nim_OfCheck_CACHE19)))) goto LA24_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_XHELJVsVdBknz4Bfivv4kQ_));
		result = validateChunk_vHWs7qbKpjD3JhdXw6DsRQ_2(((tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA24_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_DNM8loOImElj9bvoxFar9auw_), Nim_OfCheck_CACHE20)))) goto LA27_;
		result = validateChunk_mdjB58OHI6j9c07YXah9b0SA(chunk, png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA27_: ;
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, parseChunk_XjBLuFR33JWp4PM7tnVByA)(tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png) {
	NIM_BOOL result;
	nimfr_("parseChunk", "nimPNG.nim");
{	result = (NIM_BOOL)0;
	nimln_(426, "nimPNG.nim");
	chckNilDisp(chunk);
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_19ah8rXfRZMmdCeZoOyE8Hw_), Nim_OfCheck_CACHE21)))) goto LA3_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_19ah8rXfRZMmdCeZoOyE8Hw_));
		result = parseChunk_VOEemMktNEtLAnGqe2NkRQ(((tyObject_PNGStandarRGBcolonObjectType__19ah8rXfRZMmdCeZoOyE8Hw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_LT7Y9a9bsqO6qiFWdeftE0WA_), Nim_OfCheck_CACHE22)))) goto LA6_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_LT7Y9a9bsqO6qiFWdeftE0WA_));
		result = parseChunk_f1Csfw6GK8I6uZ9aReM9ax8g(((tyObject_PNGHistcolonObjectType__LT7Y9a9bsqO6qiFWdeftE0WA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_IQbkgmOSGm6kEHaEfeltDw_), Nim_OfCheck_CACHE23)))) goto LA9_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_IQbkgmOSGm6kEHaEfeltDw_));
		result = parseChunk_C3QLu189bW7TGq4XUYtiJ4Q(((tyObject_PNGSPalettecolonObjectType__IQbkgmOSGm6kEHaEfeltDw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA9_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_hMHzmPmnYaDDKI81MPfelQ_), Nim_OfCheck_CACHE24)))) goto LA12_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_hMHzmPmnYaDDKI81MPfelQ_));
		result = parseChunk_Yqr9bYNYbizHCl50cNUo0Ug(((tyObject_PNGSbitcolonObjectType__hMHzmPmnYaDDKI81MPfelQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA12_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_R7Jw9cl9cQmf0yjLYX7u8kxw_), Nim_OfCheck_CACHE25)))) goto LA15_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_R7Jw9cl9cQmf0yjLYX7u8kxw_));
		result = parseChunk_i2Erk5UJ3zJ0fXAGvMZPJw(((tyObject_APNGFrameDatacolonObjectType__R7Jw9cl9cQmf0yjLYX7u8kxw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA15_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_XHELJVsVdBknz4Bfivv4kQ_), Nim_OfCheck_CACHE26)))) goto LA18_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_XHELJVsVdBknz4Bfivv4kQ_));
		result = parseChunk_vHWs7qbKpjD3JhdXw6DsRQ(((tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA18_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_nMRAAuCEC9aROxdmFdUpJtA_), Nim_OfCheck_CACHE27)))) goto LA21_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_nMRAAuCEC9aROxdmFdUpJtA_));
		result = parseChunk_SaMVSf9bJH269cOlLNbV0Kag_2(((tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA21_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_i9cF13cHtN9cwvMVXkTJEO1Q_), Nim_OfCheck_CACHE28)))) goto LA24_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_i9cF13cHtN9cwvMVXkTJEO1Q_));
		result = parseChunk_iINp1zhnlPxLbSRphuEN0w_2(((tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA24_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_UDHAj9c34pyOZKEGUUayLSg_), Nim_OfCheck_CACHE29)))) goto LA27_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_UDHAj9c34pyOZKEGUUayLSg_));
		result = parseChunk_fS9cfD0FVS0VVKlnmc5VwOQ(((tyObject_PNGGammacolonObjectType__UDHAj9c34pyOZKEGUUayLSg*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA27_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_rMpje6gA2Q2GH0W9bTwxWbw_), Nim_OfCheck_CACHE30)))) goto LA30_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_rMpje6gA2Q2GH0W9bTwxWbw_));
		result = parseChunk_kJehw0Ir7Artp89bM9avhUYg_2(((tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA30_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_wnKS2ux9aN2yCglvRsRiPrQ_), Nim_OfCheck_CACHE31)))) goto LA33_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_wnKS2ux9aN2yCglvRsRiPrQ_));
		result = parseChunk_2a6wG1cvLN85BDnzT7Riww(((tyObject_APNGAnimationControlcolonObjectType__wnKS2ux9aN2yCglvRsRiPrQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA33_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_oJWRCuC12OxkSgyxp4G6Aw_), Nim_OfCheck_CACHE32)))) goto LA36_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_oJWRCuC12OxkSgyxp4G6Aw_));
		result = parseChunk_RsWUXX6AEMqhtRVVJUWyjg(((tyObject_PNGChromacolonObjectType__oJWRCuC12OxkSgyxp4G6Aw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA36_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_EliRKtUsLlyl0DkfPoJTCw_), Nim_OfCheck_CACHE33)))) goto LA39_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_EliRKtUsLlyl0DkfPoJTCw_));
		result = parseChunk_KlDtsoibKBOQWOEX9bF9bDGw(((tyObject_PNGPalettecolonObjectType__EliRKtUsLlyl0DkfPoJTCw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA39_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_TJdSTRO4iixkiNDLa9cshfg_), Nim_OfCheck_CACHE34)))) goto LA42_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_TJdSTRO4iixkiNDLa9cshfg_));
		result = parseChunk_WilUcM7l4auoZDrNezzfYQ(((tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA42_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_H9cL3h8nRRweZK9axJZKCdfQ_), Nim_OfCheck_CACHE35)))) goto LA45_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_H9cL3h8nRRweZK9axJZKCdfQ_));
		result = parseChunk_zDMhjbZAKC29cdauwRCTwxQ_2(((tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA45_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_x6P7vE9cYceltKZAZDSQVuQ_), Nim_OfCheck_CACHE36)))) goto LA48_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_x6P7vE9cYceltKZAZDSQVuQ_));
		result = parseChunk_oc0WZ2tp9bbJfl0wUUjUNQA_2(((tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA48_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_s0sPyN9atFvjezpAW8tdnmw_), Nim_OfCheck_CACHE37)))) goto LA51_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_s0sPyN9atFvjezpAW8tdnmw_));
		result = parseChunk_45LvIL0vtyWdfWB3UnhGqw_2(((tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA51_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_29bWwuvCwJ8KaXreO9bPK09cw_), Nim_OfCheck_CACHE38)))) goto LA54_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_29bWwuvCwJ8KaXreO9bPK09cw_));
		result = parseChunk_w9bXHZQNdsXY9a2Vl9aA9c81Ew(((tyObject_PNGBackgroundcolonObjectType__29bWwuvCwJ8KaXreO9bPK09cw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA54_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_A3ZPalS9aOltaWs09cbPoBuA_), Nim_OfCheck_CACHE39)))) goto LA57_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_A3ZPalS9aOltaWs09cbPoBuA_));
		result = parseChunk_wQnbfAKRQnaxvEGUdtchig(((tyObject_PNGTranscolonObjectType__A3ZPalS9aOltaWs09cbPoBuA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA57_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_DIdBuf9cN8oFoYRxXG4B9ccA_), Nim_OfCheck_CACHE40)))) goto LA60_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_DIdBuf9cN8oFoYRxXG4B9ccA_));
		result = parseChunk_tso9cUarLApsWLxQQMv5bnw(((tyObject_PNGPhyscolonObjectType__DIdBuf9cN8oFoYRxXG4B9ccA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA60_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_DNM8loOImElj9bvoxFar9auw_), Nim_OfCheck_CACHE41)))) goto LA63_;
		result = parseChunk_mdjB58OHI6j9c07YXah9b0SA_2(chunk, png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA63_: ;
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, writeChunk_XjBLuFR33JWp4PM7tnVByA_3)(tyObject_PNGChunkcolonObjectType__DNM8loOImElj9bvoxFar9auw* chunk, tyObject_PNGcolonObjectType__mSUjbs22gsylhzTXfKD7sw* png) {
	NIM_BOOL result;
	nimfr_("writeChunk", "nimPNG.nim");
{	result = (NIM_BOOL)0;
	nimln_(2231, "nimPNG.nim");
	chckNilDisp(chunk);
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_nMRAAuCEC9aROxdmFdUpJtA_), Nim_OfCheck_CACHE42)))) goto LA3_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_nMRAAuCEC9aROxdmFdUpJtA_));
		result = writeChunk_SaMVSf9bJH269cOlLNbV0Kag_3(((tyObject_PNGICCProfilecolonObjectType__nMRAAuCEC9aROxdmFdUpJtA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_rMpje6gA2Q2GH0W9bTwxWbw_), Nim_OfCheck_CACHE43)))) goto LA6_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_rMpje6gA2Q2GH0W9bTwxWbw_));
		result = writeChunk_kJehw0Ir7Artp89bM9avhUYg_3(((tyObject_PNGItxtcolonObjectType__rMpje6gA2Q2GH0W9bTwxWbw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_x6P7vE9cYceltKZAZDSQVuQ_), Nim_OfCheck_CACHE44)))) goto LA9_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_x6P7vE9cYceltKZAZDSQVuQ_));
		result = writeChunk_oc0WZ2tp9bbJfl0wUUjUNQA_3(((tyObject_PNGDatacolonObjectType__x6P7vE9cYceltKZAZDSQVuQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA9_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_i9cF13cHtN9cwvMVXkTJEO1Q_), Nim_OfCheck_CACHE45)))) goto LA12_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_i9cF13cHtN9cwvMVXkTJEO1Q_));
		result = writeChunk_iINp1zhnlPxLbSRphuEN0w_3(((tyObject_PNGTextcolonObjectType__i9cF13cHtN9cwvMVXkTJEO1Q*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA12_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_R7Jw9cl9cQmf0yjLYX7u8kxw_), Nim_OfCheck_CACHE46)))) goto LA15_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_R7Jw9cl9cQmf0yjLYX7u8kxw_));
		result = writeChunk_i2Erk5UJ3zJ0fXAGvMZPJw_2(((tyObject_APNGFrameDatacolonObjectType__R7Jw9cl9cQmf0yjLYX7u8kxw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA15_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_H9cL3h8nRRweZK9axJZKCdfQ_), Nim_OfCheck_CACHE47)))) goto LA18_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_H9cL3h8nRRweZK9axJZKCdfQ_));
		result = writeChunk_zDMhjbZAKC29cdauwRCTwxQ_3(((tyObject_PNGZtxtcolonObjectType__H9cL3h8nRRweZK9axJZKCdfQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA18_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_wnKS2ux9aN2yCglvRsRiPrQ_), Nim_OfCheck_CACHE48)))) goto LA21_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_wnKS2ux9aN2yCglvRsRiPrQ_));
		result = writeChunk_2a6wG1cvLN85BDnzT7Riww_2(((tyObject_APNGAnimationControlcolonObjectType__wnKS2ux9aN2yCglvRsRiPrQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA21_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_IQbkgmOSGm6kEHaEfeltDw_), Nim_OfCheck_CACHE49)))) goto LA24_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_IQbkgmOSGm6kEHaEfeltDw_));
		result = writeChunk_C3QLu189bW7TGq4XUYtiJ4Q_2(((tyObject_PNGSPalettecolonObjectType__IQbkgmOSGm6kEHaEfeltDw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA24_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_19ah8rXfRZMmdCeZoOyE8Hw_), Nim_OfCheck_CACHE50)))) goto LA27_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_19ah8rXfRZMmdCeZoOyE8Hw_));
		result = writeChunk_VOEemMktNEtLAnGqe2NkRQ_2(((tyObject_PNGStandarRGBcolonObjectType__19ah8rXfRZMmdCeZoOyE8Hw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA27_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_XHELJVsVdBknz4Bfivv4kQ_), Nim_OfCheck_CACHE51)))) goto LA30_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_XHELJVsVdBknz4Bfivv4kQ_));
		result = writeChunk_vHWs7qbKpjD3JhdXw6DsRQ_3(((tyObject_APNGFrameControlcolonObjectType__XHELJVsVdBknz4Bfivv4kQ*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA30_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_UDHAj9c34pyOZKEGUUayLSg_), Nim_OfCheck_CACHE52)))) goto LA33_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_UDHAj9c34pyOZKEGUUayLSg_));
		result = writeChunk_fS9cfD0FVS0VVKlnmc5VwOQ_2(((tyObject_PNGGammacolonObjectType__UDHAj9c34pyOZKEGUUayLSg*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA33_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_EliRKtUsLlyl0DkfPoJTCw_), Nim_OfCheck_CACHE53)))) goto LA36_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_EliRKtUsLlyl0DkfPoJTCw_));
		result = writeChunk_KlDtsoibKBOQWOEX9bF9bDGw_2(((tyObject_PNGPalettecolonObjectType__EliRKtUsLlyl0DkfPoJTCw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA36_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_TJdSTRO4iixkiNDLa9cshfg_), Nim_OfCheck_CACHE54)))) goto LA39_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_TJdSTRO4iixkiNDLa9cshfg_));
		result = writeChunk_WilUcM7l4auoZDrNezzfYQ_2(((tyObject_PNGHeadercolonObjectType__TJdSTRO4iixkiNDLa9cshfg*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA39_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_oJWRCuC12OxkSgyxp4G6Aw_), Nim_OfCheck_CACHE55)))) goto LA42_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_oJWRCuC12OxkSgyxp4G6Aw_));
		result = writeChunk_RsWUXX6AEMqhtRVVJUWyjg_2(((tyObject_PNGChromacolonObjectType__oJWRCuC12OxkSgyxp4G6Aw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA42_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_LT7Y9a9bsqO6qiFWdeftE0WA_), Nim_OfCheck_CACHE56)))) goto LA45_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_LT7Y9a9bsqO6qiFWdeftE0WA_));
		result = writeChunk_f1Csfw6GK8I6uZ9aReM9ax8g_2(((tyObject_PNGHistcolonObjectType__LT7Y9a9bsqO6qiFWdeftE0WA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA45_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_DIdBuf9cN8oFoYRxXG4B9ccA_), Nim_OfCheck_CACHE57)))) goto LA48_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_DIdBuf9cN8oFoYRxXG4B9ccA_));
		result = writeChunk_tso9cUarLApsWLxQQMv5bnw_2(((tyObject_PNGPhyscolonObjectType__DIdBuf9cN8oFoYRxXG4B9ccA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA48_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_s0sPyN9atFvjezpAW8tdnmw_), Nim_OfCheck_CACHE58)))) goto LA51_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_s0sPyN9atFvjezpAW8tdnmw_));
		result = writeChunk_45LvIL0vtyWdfWB3UnhGqw_3(((tyObject_PNGTimecolonObjectType__s0sPyN9atFvjezpAW8tdnmw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA51_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_29bWwuvCwJ8KaXreO9bPK09cw_), Nim_OfCheck_CACHE59)))) goto LA54_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_29bWwuvCwJ8KaXreO9bPK09cw_));
		result = writeChunk_w9bXHZQNdsXY9a2Vl9aA9c81Ew_2(((tyObject_PNGBackgroundcolonObjectType__29bWwuvCwJ8KaXreO9bPK09cw*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA54_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_A3ZPalS9aOltaWs09cbPoBuA_), Nim_OfCheck_CACHE60)))) goto LA57_;
		if (chunk) chckObj((*chunk).Sup.m_type, (&NTI_A3ZPalS9aOltaWs09cbPoBuA_));
		result = writeChunk_wQnbfAKRQnaxvEGUdtchig_2(((tyObject_PNGTranscolonObjectType__A3ZPalS9aOltaWs09cbPoBuA*) (chunk)), png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA57_: ;
	{
		if (!((chunk) && (isObjWithCache((*chunk).Sup.m_type, (&NTI_DNM8loOImElj9bvoxFar9auw_), Nim_OfCheck_CACHE61)))) goto LA60_;
		result = writeChunk_mdjB58OHI6j9c07YXah9b0SA_3(chunk, png);
		goto BeforeRet_;
	}
	goto LA1_;
	LA60_: ;
	LA1_: ;
	}BeforeRet_: ;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(void, log_15uDclQ9cwzr06QrR8BYZqA)(tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* logger, tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg level, NimStringDesc** args, NI argsLen_0) {
	nimfr_("log", "logging.nim");
	nimln_(149, "logging.nim");
	chckNilDisp(logger);
	{
		if (!((logger) && (isObjWithCache((*logger).Sup.m_type, (&NTI_O2Lvje8yIZTOG9bz4MrKW7g_), Nim_OfCheck_CACHE62)))) goto LA3_;
		if (logger) chckObj((*logger).Sup.m_type, (&NTI_O2Lvje8yIZTOG9bz4MrKW7g_));
		log_Z1wwTzhV8hfwxjrAweVVZQ(((tyObject_RollingFileLoggercolonObjectType__O2Lvje8yIZTOG9bz4MrKW7g*) (logger)), level, args, argsLen_0);
	}
	goto LA1_;
	LA3_: ;
	{
		if (!((logger) && (isObjWithCache((*logger).Sup.m_type, (&NTI_DiHvgyNJFmeALM5A2LhG3w_), Nim_OfCheck_CACHE63)))) goto LA6_;
		if (logger) chckObj((*logger).Sup.m_type, (&NTI_DiHvgyNJFmeALM5A2LhG3w_));
		log_ZlB8IWVc9cdlahbPdrAh0Og(((tyObject_FileLoggercolonObjectType__DiHvgyNJFmeALM5A2LhG3w*) (logger)), level, args, argsLen_0);
	}
	goto LA1_;
	LA6_: ;
	{
		if (!((logger) && (isObjWithCache((*logger).Sup.m_type, (&NTI_QaTO46vt5hgK2eu9ah2xGrA_), Nim_OfCheck_CACHE64)))) goto LA9_;
		if (logger) chckObj((*logger).Sup.m_type, (&NTI_QaTO46vt5hgK2eu9ah2xGrA_));
		log_F2wVp9bYd9alkwSwovfO9aanw(((tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*) (logger)), level, args, argsLen_0);
	}
	goto LA1_;
	LA9_: ;
	{
		if (!((logger) && (isObjWithCache((*logger).Sup.m_type, (&NTI_igsiUXBFuP9cp5KwKL5yiug_), Nim_OfCheck_CACHE65)))) goto LA12_;
		log_ickm9bT0pWcynhn7oX83aTg(logger, level, args, argsLen_0);
	}
	goto LA1_;
	LA12_: ;
	LA1_: ;
	popFrame();
}

static N_INLINE(void, initStackBottomWith)(void* locals) {
	setStackBottom(locals);
}
void PreMainInner(void) {
	systemInit000();
	glfw_glfw3DatInit000();
	stdlib_macrosDatInit000();
	stdlib_sequtilsDatInit000();
	stdlib_parseutilsDatInit000();
	stdlib_mathDatInit000();
	stdlib_algorithmDatInit000();
	stdlib_strutilsDatInit000();
	stdlib_dynlibDatInit000();
	stdlib_winleanDatInit000();
	stdlib_timesDatInit000();
	stdlib_ospathsDatInit000();
	stdlib_osDatInit000();
	opengl_openglDatInit000();
	stdlib_streamsDatInit000();
	stdlib_endiansDatInit000();
	stdlib_hashesDatInit000();
	stdlib_tablesDatInit000();
	nimPNG_bufferDatInit000();
	nimPNG_nimzDatInit000();
	nimPNG_nimPNGDatInit000();
	stdlib_loggingDatInit000();
	unknown_glutilsDatInit000();
	unknown_textureDatInit000();
	unknown_textureregionDatInit000();
	unknown_spritebatchDatInit000();
	testDatInit000();
	glfw_glfw3Init000();
	stdlib_macrosInit000();
	stdlib_sequtilsInit000();
	stdlib_parseutilsInit000();
	stdlib_mathInit000();
	stdlib_algorithmInit000();
	stdlib_strutilsInit000();
	stdlib_dynlibInit000();
	stdlib_winleanInit000();
	stdlib_timesInit000();
	stdlib_ospathsInit000();
	stdlib_osInit000();
	opengl_openglInit000();
	stdlib_streamsInit000();
	stdlib_endiansInit000();
	stdlib_hashesInit000();
	stdlib_tablesInit000();
	nimPNG_bufferInit000();
	nimPNG_nimzInit000();
	nimPNG_nimPNGInit000();
	stdlib_loggingInit000();
	unknown_glutilsInit000();
	unknown_textureInit000();
	unknown_textureregionInit000();
	unknown_spritebatchInit000();
}

void PreMain(void) {
	void (*volatile inner)(void);
	systemDatInit000();
	inner = PreMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int cmdCount;
char** cmdLine;
char** gEnv;
N_CDECL(void, NimMainInner)(void) {
	NimMainModule();
}

N_CDECL(void, NimMain)(void) {
	void (*volatile inner)(void);
	PreMain();
	inner = NimMainInner;
	initStackBottomWith((void *)&inner);
	(*inner)();
}

int main(int argc, char** args, char** env) {
	cmdLine = args;
	cmdCount = argc;
	gEnv = env;
	NimMain();
	return nim_program_result;
}

NIM_EXTERNC N_NOINLINE(void, NimMainModule)(void) {
	tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA* T7_;
	tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug* T8_;
	NU32 T9_;
	NU32 T10_;
	tyArray_Re75IspeoxXy2oCZHwcRrA T11_;
	nimfr_("test", "test.nim");
nimRegisterGlobalMarker(TM_ipcYmBC9bj9a1BW35ABoB1Kw_2);
nimRegisterGlobalMarker(TM_ipcYmBC9bj9a1BW35ABoB1Kw_7);
	nimln_(26, "test.nim");
	{
		int T3_;
		NimStringDesc* T6_;
		T3_ = (int)0;
		T3_ = Dl_108855_();
		if (!(T3_ == ((NI32) 0))) goto LA4_;
		nimln_(2811, "system.nim");
		if (e_TTtl9bYTKPNoTGtunSBNPVg) { nimGCunrefRC1(e_TTtl9bYTKPNoTGtunSBNPVg); e_TTtl9bYTKPNoTGtunSBNPVg = NIM_NIL; }
		e_TTtl9bYTKPNoTGtunSBNPVg = (Exception*) newObjRC1((&NTI_oUKtBcKRdK6usj8RWrlp6A_), sizeof(Exception));
		(*e_TTtl9bYTKPNoTGtunSBNPVg).Sup.m_type = (&NTI_bAvOj2UcojKN87yAQLs0aw_);
		nimln_(27, "test.nim");
		T6_ = (NimStringDesc*)0;
		T6_ = (*e_TTtl9bYTKPNoTGtunSBNPVg).message; (*e_TTtl9bYTKPNoTGtunSBNPVg).message = copyStringRC1(((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_3));
		if (T6_) nimGCunrefNoCycle(T6_);
		nimln_(2806, "system.nim");
		asgnRef((void**) (&(*e_TTtl9bYTKPNoTGtunSBNPVg).parent), NIM_NIL);
		nimln_(27, "test.nim");
		raiseException((Exception*)e_TTtl9bYTKPNoTGtunSBNPVg, "Exception");
	}
	LA4_: ;
	nimln_(29, "test.nim");
	nimln_(170, "logging.nim");
	T7_ = (tyObject_ConsoleLoggercolonObjectType__QaTO46vt5hgK2eu9ah2xGrA*)0;
	T7_ = newConsoleLogger_EgdHBnSBbwirQsDvEbPCdg(((tyEnum_Level_pW4mH4lipH6u2NKDGEWdGg) 0), ((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_4));
	T8_ = (tyObject_LoggercolonObjectType__igsiUXBFuP9cp5KwKL5yiug*)0;
	T8_ = &T7_->Sup;
	addHandler_tg0stk9atBM54nh79a3PBrOA(T8_);
	nimln_(31, "test.nim");
	window_dD49cxsV0oovpiv8IGDCmxA = Dl_108928_(((int) 800), ((int) 600), "GLFW3 WINDOW", NIM_NIL, NIM_NIL);
	nimln_(33, "test.nim");
	Dl_109195_(window_dD49cxsV0oovpiv8IGDCmxA);
	nimln_(34, "test.nim");
	nimLoadProcs0();
	nimln_(44, "test.nim");
	nimln_(45, "test.nim");
	T9_ = (NU32)0;
	T9_ = createShader_2AHO9c5dppd7n465CyKP18A(((NU32) 35633), ((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_5));
	nimln_(46, "test.nim");
	T10_ = (NU32)0;
	T10_ = createShader_2AHO9c5dppd7n465CyKP18A(((NU32) 35632), ((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_6));
	handle_be1PDmhwBN9aUP9b0Z9cxnyjg = createProgram_ap6cDX2l6cLS9bixaOW9cplg(T9_, T10_);
	nimln_(49, "test.nim");
	chckNil((void*)(&program_wJjMvAO7mULmp9cHljQls8Q));
	genericReset((void*)(&program_wJjMvAO7mULmp9cHljQls8Q), (&NTI_5U307oTET301CaFCP809big_));
	program_wJjMvAO7mULmp9cHljQls8Q.handle = handle_be1PDmhwBN9aUP9b0Z9cxnyjg;
	nimln_(51, "test.nim");
	program_wJjMvAO7mULmp9cHljQls8Q.locations = getStandardLocations_giUqXozJi7uywizGM9a9beug(handle_be1PDmhwBN9aUP9b0Z9cxnyjg);
	nimln_(54, "test.nim");
	asgnRef((void**) (&png_RMrzyLJuTrkfKnEVsGKAmg), loadPNG32_9bMlYZh4PdO4Rg4mqC8VJFg(((NimStringDesc*) &TM_ipcYmBC9bj9a1BW35ABoB1Kw_8), NIM_NIL));
	nimln_(55, "test.nim");
	tex_WARSAqa76GTaQHkTuw4WbA = createTexture_Xt2LvZ6NCFeQAauwyI4Xeg((*png_RMrzyLJuTrkfKnEVsGKAmg).width, (*png_RMrzyLJuTrkfKnEVsGKAmg).height, ((tyEnum_PixelFormat_8J9cBMWJgNNS8b4aTcfFdQg) 1), (&(*png_RMrzyLJuTrkfKnEVsGKAmg).data));
	nimln_(56, "test.nim");
	memset((void*)T11_, 0, sizeof(T11_));
	T11_[0] = nimIntToStr((*png_RMrzyLJuTrkfKnEVsGKAmg).width);
	T11_[1] = nimIntToStr((*png_RMrzyLJuTrkfKnEVsGKAmg).height);
	echoBinSafe(T11_, 2);
	nimln_(58, "test.nim");
	batch_2OjOVmonJdOmSkINAfqJXQ = newSpriteBatch_Rx4s9cI3qy4Qwal5QjiqUBw(program_wJjMvAO7mULmp9cHljQls8Q);
	{
		nimln_(60, "test.nim");
		while (1) {
			int T14_;
			NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_9;
			NI TM_ipcYmBC9bj9a1BW35ABoB1Kw_10;
			tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ T20_;
			T14_ = (int)0;
			T14_ = Dl_108938_(window_dD49cxsV0oovpiv8IGDCmxA);
			if (!(T14_ == ((NI32) 0))) goto LA13;
			nimln_(61, "test.nim");
			Dl_109073_();
			nimln_(62, "test.nim");
			Dl_109200_(window_dD49cxsV0oovpiv8IGDCmxA);
			nimln_(64, "test.nim");
			{
				int T17_;
				T17_ = (int)0;
				T17_ = Dl_109091_(window_dD49cxsV0oovpiv8IGDCmxA, ((int) 256));
				if (!(T17_ == ((NI32) 1))) goto LA18_;
				nimln_(65, "test.nim");
				Dl_108941_(window_dD49cxsV0oovpiv8IGDCmxA, ((int) 1));
			}
			LA18_: ;
			nimln_(67, "test.nim");
			glClearColor_f9bT9as4U8bxdkTUxJK60qlA(1.0000000000000000e+000, 0.0, 0.0, 1.0000000000000000e+000);
			nimln_(68, "test.nim");
			glClear_ecjp09clx9c7t3uIhyfuACGQ(((NU32) 16640));
			nimln_(71, "test.nim");
			TM_ipcYmBC9bj9a1BW35ABoB1Kw_9 = subInt(tex_WARSAqa76GTaQHkTuw4WbA.width, ((NI) 200));
			TM_ipcYmBC9bj9a1BW35ABoB1Kw_10 = subInt(tex_WARSAqa76GTaQHkTuw4WbA.height, ((NI) 200));
			T20_ = makeTextureRegion_10Ua2psAivWdjmRBQsvDtA(tex_WARSAqa76GTaQHkTuw4WbA, ((NI) 100), ((NI) 100), (NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_9), (NI)(TM_ipcYmBC9bj9a1BW35ABoB1Kw_10));
			draw_2FrjBHe3tWgCd1N7e15eHw((&batch_2OjOVmonJdOmSkINAfqJXQ), (&T20_), -5.0000000000000000e-001, -5.0000000000000000e-001, 1.0000000000000000e+000, 1.0000000000000000e+000);
			nimln_(72, "test.nim");
			flush_GHonqE9aQDzibr6yQNKdk3A((&batch_2OjOVmonJdOmSkINAfqJXQ));
		} LA13: ;
	}
	nimln_(74, "test.nim");
	Dl_108935_(window_dD49cxsV0oovpiv8IGDCmxA);
	nimln_(75, "test.nim");
	Dl_108857_();
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, testDatInit000)(void) {
}

