/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\textureregion.o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\textureregion.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ;
typedef struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ;
struct tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ {
NI width;
NI height;
NU32 handle;
};
struct tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ {
tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ texture;
NF u0;
NF v0;
NF u1;
NF v1;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ, makeTextureRegion_10Ua2psAivWdjmRBQsvDtA)(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NI x, NI y, NI width, NI height);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
static N_INLINE(NI, addInt)(NI a, NI b);
N_NOINLINE(void, raiseOverflow)(void);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

static N_INLINE(NF, slash__fu0hCFNNw3xnGgcs2KwTWgsystem)(NI x, NI y) {
	NF result;
	nimfr_("/", "system.nim");
	result = (NF)0;
	nimln_(3498, "system.nim");
	result = ((NF)(((double) (x))) / (NF)(((double) (y))));
	popFrame();
	return result;
}

static N_INLINE(NI, addInt)(NI a, NI b) {
	NI result;
{	result = (NI)0;
	result = (NI)((NU64)(a) + (NU64)(b));
	{
		NIM_BOOL T3_;
		T3_ = (NIM_BOOL)0;
		T3_ = (((NI) 0) <= (NI)(result ^ a));
		if (T3_) goto LA4_;
		T3_ = (((NI) 0) <= (NI)(result ^ b));
		LA4_: ;
		if (!T3_) goto LA5_;
		goto BeforeRet_;
	}
	LA5_: ;
	raiseOverflow();
	}BeforeRet_: ;
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ, makeTextureRegion_10Ua2psAivWdjmRBQsvDtA)(tyObject_Texture_rRMR38YRTFk9b55z9cSXatnQ tex, NI x, NI y, NI width, NI height) {
	tyObject_TextureRegion_G49bipZOPHX36JhICRpmI9cQ result;
	NI TM_DBdYXwLY9bi0Wza5hiEdB3g_2;
	NI TM_DBdYXwLY9bi0Wza5hiEdB3g_3;
	nimfr_("makeTextureRegion", "textureregion.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(9, "textureregion.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.texture = tex;
	nimln_(11, "textureregion.nim");
	result.u0 = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(x, tex.width);
	nimln_(12, "textureregion.nim");
	result.v0 = slash__fu0hCFNNw3xnGgcs2KwTWgsystem(y, tex.height);
	nimln_(13, "textureregion.nim");
	TM_DBdYXwLY9bi0Wza5hiEdB3g_2 = addInt(x, width);
	result.u1 = slash__fu0hCFNNw3xnGgcs2KwTWgsystem((NI)(TM_DBdYXwLY9bi0Wza5hiEdB3g_2), tex.width);
	nimln_(14, "textureregion.nim");
	TM_DBdYXwLY9bi0Wza5hiEdB3g_3 = addInt(y, height);
	result.v1 = slash__fu0hCFNNw3xnGgcs2KwTWgsystem((NI)(TM_DBdYXwLY9bi0Wza5hiEdB3g_3), tex.height);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_textureregionInit000)(void) {
	nimfr_("textureregion", "textureregion.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_textureregionDatInit000)(void) {
}

