/* Generated by Nim Compiler v0.17.3 */
/*   (c) 2018 Andreas Rumpf */
/* The generated code is subject to the original license. */
/* Compiled for: Windows, amd64, gcc */
/* Command for C compiler:
   gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IC:\nim\lib -o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\vec2.o c:\Users\Desktop-P1NKA\Desktop\nimengine\nimcache\vec2.c */
#define NIM_NEW_MANGLING_RULES
#define NIM_INTBITS 64

#include "nimbase.h"
#include <string.h>
#include <math.h>
#undef LANGUAGE_C
#undef MIPSEB
#undef MIPSEL
#undef PPC
#undef R3000
#undef R4000
#undef i386
#undef linux
#undef mips
#undef near
#undef powerpc
#undef unix
typedef struct tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w;
struct tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w {
NF x;
NF y;
};
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, vec2_z7NVGxkcNytqrcErd3MEzg)(NF x, NF y);
N_NOINLINE(void, chckNil)(void* p);
static N_INLINE(void, nimFrame)(TFrame* s);
N_LIB_PRIVATE N_NOINLINE(void, stackOverflow_II46IjNZztN9bmbxUD8dt8g)(void);
static N_INLINE(void, popFrame)(void);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, plus__Whz9avAB8516A45w7hzN4sA)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w a, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w b);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, minus__Whz9avAB8516A45w7hzN4sA_2)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w a, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w b);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, star__UvDdbyQZB8XMU1Vk4QqVOA)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v, NF k);
N_LIB_PRIVATE N_NIMCALL(NF, dot_SMqUB9csrI9aaBHY5uEjV4Wg)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w a, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w b);
N_LIB_PRIVATE N_NIMCALL(NF, len2_B9cOy6fy9aDHBizZ4MaoJznA)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v);
N_LIB_PRIVATE N_NIMCALL(NF, len_B9cOy6fy9aDHBizZ4MaoJznA_2)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, unit_x50m0afES4A2Y09ayUccaoQ)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, norm_x50m0afES4A2Y09ayUccaoQ_2)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v);
N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, unitNorm_x50m0afES4A2Y09ayUccaoQ_3)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v);
extern TFrame* framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;

static N_INLINE(void, nimFrame)(TFrame* s) {
	NI T1_;
	T1_ = (NI)0;
	{
		if (!(framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw == NIM_NIL)) goto LA4_;
		T1_ = ((NI) 0);
	}
	goto LA2_;
	LA4_: ;
	{
		T1_ = ((NI) ((NI16)((*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).calldepth + ((NI16) 1))));
	}
	LA2_: ;
	(*s).calldepth = ((NI16) (T1_));
	(*s).prev = framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw;
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = s;
	{
		if (!((*s).calldepth == ((NI16) 2000))) goto LA9_;
		stackOverflow_II46IjNZztN9bmbxUD8dt8g();
	}
	LA9_: ;
}

static N_INLINE(void, popFrame)(void) {
	framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw = (*framePtr_HRfVMH3jYeBJz6Q6X9b6Ptw).prev;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, vec2_z7NVGxkcNytqrcErd3MEzg)(NF x, NF y) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	nimfr_("vec2", "vec2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(7, "vec2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x = x;
	result.y = y;
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, plus__Whz9avAB8516A45w7hzN4sA)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w a, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w b) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	nimfr_("+", "vec2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(8, "vec2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x = ((NF)(a.x) + (NF)(b.x));
	result.y = ((NF)(a.y) + (NF)(b.y));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, minus__Whz9avAB8516A45w7hzN4sA_2)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w a, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w b) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	nimfr_("-", "vec2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(9, "vec2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x = ((NF)(a.x) - (NF)(b.x));
	result.y = ((NF)(a.y) - (NF)(b.y));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, star__UvDdbyQZB8XMU1Vk4QqVOA)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v, NF k) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	nimfr_("*", "vec2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(10, "vec2.nim");
	chckNil((void*)(&result));
	memset((void*)(&result), 0, sizeof(result));
	result.x = ((NF)(v.x) * (NF)(k));
	result.y = ((NF)(v.y) * (NF)(k));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, dot_SMqUB9csrI9aaBHY5uEjV4Wg)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w a, tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w b) {
	NF result;
	nimfr_("dot", "vec2.nim");
	result = (NF)0;
	nimln_(12, "vec2.nim");
	result = ((NF)(((NF)(a.x) * (NF)(b.x))) + (NF)(((NF)(a.y) * (NF)(b.y))));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, len2_B9cOy6fy9aDHBizZ4MaoJznA)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v) {
	NF result;
	nimfr_("len2", "vec2.nim");
	result = (NF)0;
	nimln_(13, "vec2.nim");
	result = dot_SMqUB9csrI9aaBHY5uEjV4Wg(v, v);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(NF, len_B9cOy6fy9aDHBizZ4MaoJznA_2)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v) {
	NF result;
	NF T1_;
	nimfr_("len", "vec2.nim");
	result = (NF)0;
	nimln_(14, "vec2.nim");
	T1_ = (NF)0;
	T1_ = len2_B9cOy6fy9aDHBizZ4MaoJznA(v);
	result = sqrt(T1_);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, unit_x50m0afES4A2Y09ayUccaoQ)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	NF len;
	nimfr_("unit", "vec2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(17, "vec2.nim");
	len = len_B9cOy6fy9aDHBizZ4MaoJznA_2(v);
	nimln_(18, "vec2.nim");
	result = vec2_z7NVGxkcNytqrcErd3MEzg(((NF)(v.x) / (NF)(len)), ((NF)(v.y) / (NF)(len)));
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, norm_x50m0afES4A2Y09ayUccaoQ_2)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	nimfr_("norm", "vec2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(20, "vec2.nim");
	result = vec2_z7NVGxkcNytqrcErd3MEzg(-(v.y), v.x);
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w, unitNorm_x50m0afES4A2Y09ayUccaoQ_3)(tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w v) {
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w result;
	tyObject_Vec2_IC43O51us9ahJwZ9cmVxLQ8w T1_;
	nimfr_("unitNorm", "vec2.nim");
	memset((void*)(&result), 0, sizeof(result));
	nimln_(21, "vec2.nim");
	T1_ = vec2_z7NVGxkcNytqrcErd3MEzg(-(v.y), v.y);
	result = unit_x50m0afES4A2Y09ayUccaoQ(T1_);
	popFrame();
	return result;
}
NIM_EXTERNC N_NOINLINE(void, unknown_vec2Init000)(void) {
	nimfr_("vec2", "vec2.nim");
	popFrame();
}

NIM_EXTERNC N_NOINLINE(void, unknown_vec2DatInit000)(void) {
}

